#/*------------------------------------------------*
# *   Copyright (c) SODIMAC. Mayo 2021.            *
# *   Portal web: www.sodimac.com.mx.              *
# *   Contributors:                                *
# *     Vantis S. de RL. de CV. Web: vantis.mx     *
# *     Ruben Martinez <ruben.martinez@vantis.mx>  *
#--------------------------------------------------*/

#assign port number
#server.port=7070
server.error.include-stacktrace=always

#properties thymeleaf
#spring.thymeleaf.cache=false
#spring.thymeleaf.enabled=true
#spring.thymeleaf.suffix=.html

#session
server.port=8080
server.servlet.session.timeout=30m
#server.servlet.session.timeout=60s

#properties environment
# Perfiles disponibles: dev, prod
# Lee la variable de entorno SPRING_PROFILES_ACTIVE, si no existe usa 'prod'
# Para WAR: Configurar en setenv.sh (Linux) o setenv.bat (Windows)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}

#version
cfdiVersion=3.1.0

#spring.jpa.generate-ddl=true
#cfdiUser

server.servlet.context-path=/cfdi

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

api.puntos.ces.login.url=http://10.138.153.10:8080/wspuntosces/api/login
api.puntos.ces.login.username=userWsPrmFac
api.puntos.ces.login.password=E0R9KWF482
api.puntos.ces.polizas.get.url=http://10.138.153.10:8080/wspuntosces/api/contable/obtener/config
api.puntos.ces.polizas.save.url=http://10.138.153.10:8080/wspuntosces/api/contable/registrar
api.puntos.ces.polizas.update.url=http://10.138.153.10:8080/wspuntosces/api/contable/actualizar
api.puntos.ces.polizas.delete.url=http://10.138.153.10:8080/wspuntosces/api/contable/delete
api.puntos.ces.catalogos.get=http://10.138.153.10:8080/wspuntosces/api/catalogo/obtener
api.puntos.ces.sucursales.get=http://10.138.153.10:8080/wspuntosces/api/catalogo/obtener/sucursales