# jdbc.X
jdbc.factura.driverClassName=org.mariadb.jdbc.Driver
jdbc.factura.url=jdbc:mysql://10.138.150.77:3306/facturacion?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CST6CDT
jdbc.factura.user=facturaUser
jdbc.factura.pass=facturaUser

#jdbc.factura.url=jdbc:mysql://10.138.153.10:4306/facturacion?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CST6CDT
#jdbc.factura.user=facturaUser
#jdbc.factura.pass=facturaUser


# hibernate.X
hibernate.factura.dialect=org.hibernate.dialect.MariaDBDialect
hibernate.factura.show_sql=false
hibernate.factura.hbm2ddl.auto=none
hibernate.factura.cache.use_second_level_cache=false
hibernate.factura.cache.use_query_cache=false

# c3p0.X
c3p0.factura.min_size=5
c3p0.factura.max_size=20
c3p0.factura.acquire_increment=5
c3p0.factura.timeout=1800
c3p0.factura.testConnectionOnCheckout=false
c3p0.factura.testConnectionOnCheckin=true
c3p0.factura.preferredTestQuery=SELECT 1
c3p0.factura.idleConnectionTestPeriod=300
c3p0.factura.privilegeSpawnedThreads=true
c3p0.factura.contextClassLoaderSource=library