#/*------------------------------------------------*
# *   PERFIL: DESARROLLO (DEV)                     *
# *   Base de Datos: sodimacfiscal                 *
# *   Servidor: 10.138.153.10:3306                 *
#--------------------------------------------------*/

# jdbc.X
jdbc.fiscal.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.fiscal.url=jdbc:mysql://10.138.153.10:3306/sodimacfiscal?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CST6CDT
jdbc.fiscal.user=sodimacfiscal
jdbc.fiscal.pass=s$0d1m4cFi2c4L

# hibernate.X
hibernate.fiscal.dialect=org.hibernate.dialect.MySQL5Dialect
hibernate.fiscal.show_sql=false
hibernate.fiscal.hbm2ddl.auto=none
hibernate.fiscal.cache.use_second_level_cache=false
hibernate.fiscal.cache.use_query_cache=false

# c3p0.X
c3p0.fiscal.min_size=5
c3p0.fiscal.max_size=20
c3p0.fiscal.acquire_increment=5
c3p0.fiscal.timeout=1800
c3p0.fiscal.testConnectionOnCheckout=false
c3p0.fiscal.testConnectionOnCheckin=true
c3p0.fiscal.preferredTestQuery=SELECT 1
c3p0.fiscal.idleConnectionTestPeriod=300
c3p0.fiscal.privilegeSpawnedThreads=true
c3p0.fiscal.contextClassLoaderSource=library
