# jdbc.X
jdbc.fiscal.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.fiscal.url=jdbc:mysql://10.138.150.71:3306/sodimacfiscal?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CST6CDT
jdbc.fiscal.user=dba_mysql
jdbc.fiscal.pass=Ewqasdcxz123.MYSQL

#jdbc.fiscal.url=jdbc:mysql://10.138.153.10:3306/sodimacfiscal?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CST6CDT
#jdbc.fiscal.user=sodimacfiscal
#jdbc.fiscal.pass=s$0d1m4cFi2c4L

#jdbc.fiscal.url=97fa82ef7a6718fac327ae724fa824e6defe69842ba892c36d4e724656bc1d1ca42adb4fd4273bbf3f3e0e9c7cb7ad9c20acf5b16189f49a507652403a648a0c33dc1ee5908b2314069b2a7742978bbcd714dda1cd25ae66b270a1a7955580ca4c8fb39c802ae23ab3667044f48eaf4173831ecfb77279d1bd933945fca00ab9b6cf14a8cea7eabb7b93dc7b88c29b496b15fa26dff2f508348204b306039bb4
#jdbc.fiscal.user=a7d95f5fb022c118fba5c8e8e23364c0
#jdbc.fiscal.pass=843a13dcd5789e816cc782340f8fe8e7


# hibernate.X
hibernate.fiscal.dialect=org.hibernate.dialect.MySQL5Dialect
hibernate.fiscal.show_sql=false
hibernate.fiscal.hbm2ddl.auto=none
hibernate.fiscal.cache.use_second_level_cache=false
hibernate.fiscal.cache.use_query_cache=false

# c3p0.X
c3p0.fiscal.min_size=5
c3p0.fiscal.max_size=20
c3p0.fiscal.acquire_increment=5
c3p0.fiscal.timeout=1800
c3p0.fiscal.testConnectionOnCheckout=false
c3p0.fiscal.testConnectionOnCheckin=true
c3p0.fiscal.preferredTestQuery=SELECT 1
c3p0.fiscal.idleConnectionTestPeriod=300
c3p0.fiscal.privilegeSpawnedThreads=true
c3p0.fiscal.contextClassLoaderSource=library