# jdbc.X
jdbc.reb.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

#Prod
#jdbc.reb.url=MDAwMDAwMDAwMDAwMDAwMCjJnA8lQqHiiqcZviouHzl/zpUiq4CPN6BVQTiMNBriRxbwsA3tbHldpE9avW/BkIbTq3tUZZYwrO0SZ99/nW+3hHrZUp4yehmxfNaOdYjT
#jdbc.reb.user=MDAwMDAwMDAwMDAwMDAwMG3oq0Shqsayo6U+WKNpll0=
#jdbc.reb.pass=MDAwMDAwMDAwMDAwMDAwMGcAupwfLz6j6h/+g5OpJB8=

#Dev
jdbc.reb.url=MDAwMDAwMDAwMDAwMDAwMCjJnA8lQqHiiqcZviouHzmoyir0MK6DB7azjDd0bwTfXJUCgUa7GwKRdbhLUJFVlvAkBf3TD4j74Bv44grt42r7iiAUS34VYb+wMPdYahkx
jdbc.reb.user=MDAwMDAwMDAwMDAwMDAwMKLHg6+4leSChR+BtF2Gg24=
jdbc.reb.pass=MDAwMDAwMDAwMDAwMDAwMFsaZrze/EWa0V7eQRj86MI=

# hibernate.X
hibernate.reb.dialect=org.hibernate.dialect.SQLServer2012Dialect
hibernate.reb.show_sql=false
hibernate.reb.hbm2ddl.auto=none
hibernate.reb.cache.use_second_level_cache=false
hibernate.reb.cache.use_query_cache=false

# c3p0.X
c3p0.reb.min_size=5
c3p0.reb.max_size=20
c3p0.reb.acquire_increment=5
c3p0.reb.timeout=1800
c3p0.reb.testConnectionOnCheckout=false
c3p0.reb.testConnectionOnCheckin=true
c3p0.reb.preferredTestQuery=SELECT 1
c3p0.reb.idleConnectionTestPeriod=300
c3p0.reb.privilegeSpawnedThreads=true
c3p0.reb.contextClassLoaderSource=library