# jdbc.X
jdbc.ws.driverClassName=org.mariadb.jdbc.Driver

#Prod
#jdbc.ws.url=MDAwMDAwMDAwMDAwMDAwMG9P6VRjJbgY4HNO+fz5AOsTJP5AcjsdqJTRLkGwyKMqHMBbiRSyJivGJO7FM+aa5tE5dzaLHnS8pd9ZBPhy/BmCTFBHSKsoVV72J885y3KcuEueOUjElqt6LKXYpxlC5Woztbhw2YRY7kBNjlUtflUr0a9RFYt8dQxCe9ibZL2TkUv4l3n9VAtKinr9CLHFTZUAt6BxtFUS1K969hJsvyE=
#jdbc.ws.user=MDAwMDAwMDAwMDAwMDAwMJNlPAdn5r2/nDru1ARLfgKMYWOoXXZIc7xzk0jaB+s8
#jdbc.ws.pass=MDAwMDAwMDAwMDAwMDAwMJNlPAdn5r2/nDru1ARLfgKMYWOoXXZIc7xzk0jaB+s8

#Dev        jdbc:mysql://10.138.153.10:4306/wsfacturacion
jdbc.ws.url=MDAwMDAwMDAwMDAwMDAwMG9P6VRjJbgY4HNO+fz5AOs2Uko3ENa9gmiSzbIHUDX6h275GI/3cVi0DAkG2qJMfKEGK1QC67yjDAWp0l/PP9pWX43q7bISLU0q1cZk08/IqhDgxogRHgr31jtsgPyO6WnIMrYN7BJVi7/Dt7SwVj8HgtB5IOdU2QREsKlnCX+3OZ3H1H1jW+xY3vgzMz9K3zqvX+6GGpSWlbk2IwLTyEw=
jdbc.ws.user=MDAwMDAwMDAwMDAwMDAwMJNlPAdn5r2/nDru1ARLfgKMYWOoXXZIc7xzk0jaB+s8
jdbc.ws.pass=MDAwMDAwMDAwMDAwMDAwMJNlPAdn5r2/nDru1ARLfgKMYWOoXXZIc7xzk0jaB+s8

# hibernate.X
hibernate.ws.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
hibernate.ws.show_sql=false
hibernate.ws.hbm2ddl.auto=none
hibernate.ws.cache.use_second_level_cache=false
hibernate.ws.cache.use_query_cache=false

# c3p0.X
c3p0.ws.min_size=5
c3p0.ws.max_size=20
c3p0.ws.acquire_increment=5
c3p0.ws.timeout=1800
c3p0.ws.testConnectionOnCheckout=false
c3p0.ws.testConnectionOnCheckin=true
c3p0.ws.preferredTestQuery=SELECT 1
c3p0.ws.idleConnectionTestPeriod=300
c3p0.ws.privilegeSpawnedThreads=true
c3p0.ws.contextClassLoaderSource=library