# jdbc.X
jdbc.bct.driverClassName=oracle.jdbc.driver.OracleDriver

#Prod
#jdbc.bct.url=MDAwMDAwMDAwMDAwMDAwMN/Fam0wU4E3l0nGeIXHG5D3s2FJTULbqGjobsjANE4r3+9eTOOlSGx6/29vQSI/dxTvLmXNxe4XEyLg8Phdtuw=
#jdbc.bct.user=MDAwMDAwMDAwMDAwMDAwMNnYFaPtRB1bP8yndvNibnU=
#jdbc.bct.pass=MDAwMDAwMDAwMDAwMDAwMHJ+W5VYyv2Hwqe/XGblw/M=
#Recuerda cambiar tambien url de ClienteFacturaConfirmarService y ClienteTicketObtenerService para pasar a produccion

#Dev
jdbc.bct.url=MDAwMDAwMDAwMDAwMDAwMN/Fam0wU4E3l0nGeIXHG5BEQ4Onu4VWZ/gmM4PXOy38j9mobVd8nPrZHBdczq2g/A==
jdbc.bct.user=MDAwMDAwMDAwMDAwMDAwMNnYFaPtRB1bP8yndvNibnU=
jdbc.bct.pass=MDAwMDAwMDAwMDAwMDAwMF0rKbjpqooqnUU1KlU/OFk=


# hibernate.X
hibernate.bct.dialect=org.hibernate.dialect.Oracle10gDialect
hibernate.bct.show_sql=false
hibernate.bct.hbm2ddl.auto=none
hibernate.bct.cache.use_second_level_cache=false
hibernate.bct.cache.use_query_cache=false

# c3p0.X
c3p0.bct.min_size=5
c3p0.bct.max_size=20
c3p0.bct.acquire_increment=5
c3p0.bct.timeout=1800
c3p0.bct.testConnectionOnCheckout=false
c3p0.bct.testConnectionOnCheckin=true
c3p0.bct.preferredTestQuery=SELECT 1 from dual
c3p0.bct.idleConnectionTestPeriod=300
c3p0.bct.privilegeSpawnedThreads=true
c3p0.bct.contextClassLoaderSource=library