# jdbc.X
jdbc.fis.driverClassName=com.mysql.cj.jdbc.Driver

#Prod
#jdbc.fis.url=MDAwMDAwMDAwMDAwMDAwMG9P6VRjJbgY4HNO+fz5AOtosDx0gOmhY7Plv6UMbMwqkXQjhaURS7ancVu4EK0zzOzAtZ59kCKNXa6/bCbK/GN7gN9S0Rp8aq1JUc9MWOl1XIeAI651CQqcNyvNnV84iV56wxmRzekbaIq4FFUMTQdNacU9edaPUdBIBYgElsFSC78Um4G2lGsxaXp7Z5NBVSQ+NJt1xlNCZPs7/68Td24=
#jdbc.fis.user=MDAwMDAwMDAwMDAwMDAwMJrUv71kQOoJC8YX8tz3TMk=
#jdbc.fis.pass=MDAwMDAwMDAwMDAwMDAwMBXs7b4mcFU8d1tnHrF+4SwAqI+T+KHpos7MjBhSrMP8

#Dev
jdbc.fis.url=MDAwMDAwMDAwMDAwMDAwMG9P6VRjJbgY4HNO+fz5AOuKnjsjtPFBndYbXRCT+/pWFsybNpXg0U3OVdImYZTXnATgJ97l6Sn6rjugBsPJ+AN8NHflNXbauS8ilT19BRznPwQZwhFCbKXTDnnaQHPT3I3JXZFy3y8Pg2YkYYtCBE6r4sY/+zO3h73c3s446tN8JME++Y7WltM3pn/9xeEVbb2IA3+r7/2gBMiIxXa6tts=
jdbc.fis.user=MDAwMDAwMDAwMDAwMDAwML5y97RmA+aDYJ4pTcPOA7o=
jdbc.fis.pass=MDAwMDAwMDAwMDAwMDAwMNlRDq3DRb2AhFU5mgL+rF0=

# hibernate.X
hibernate.fis.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
hibernate.fis.show_sql=false
hibernate.fis.hbm2ddl.auto=none
hibernate.fis.cache.use_second_level_cache=false
hibernate.fis.cache.use_query_cache=false

# c3p0.X
c3p0.fis.min_size=5
c3p0.fis.max_size=20
c3p0.fis.acquire_increment=5
c3p0.fis.timeout=1800
c3p0.fis.testConnectionOnCheckout=false
c3p0.fis.testConnectionOnCheckin=true
c3p0.fis.preferredTestQuery=SELECT 1
c3p0.fis.idleConnectionTestPeriod=300
c3p0.fis.privilegeSpawnedThreads=true
c3p0.fis.contextClassLoaderSource=library