# jdbc.X
jdbc.fac.driverClassName=org.mariadb.jdbc.Driver

#Prod        jdbc:mysql://localhost:3306/facturacion
#jdbc.fac.url=MDAwMDAwMDAwMDAwMDAwMG9P6VRjJbgY4HNO+fz5AOsTJP5AcjsdqJTRLkGwyKMq/YU66SGpDWNSt91/dmIgZXAA8uty7soxrZQF/+bRwEZWn37KdLUb6uhgA/oj7Biu3gkuYEenRNrUgQqCMd9IP3DlrxhEEa+qU+M8YcTjppW8ExDZnThLB4lWJlC7owMFurqtbiZ6xuGkveg78dvMQg8c5YJrStqMZYEvQNifc/o=
#jdbc.fac.user=MDAwMDAwMDAwMDAwMDAwMKG+OSYC8t9vgQT42Et+pfY=
#jdbc.fac.pass=MDAwMDAwMDAwMDAwMDAwMKG+OSYC8t9vgQT42Et+pfY=

#Dev         jdbc:mysql://10.138.153.10:4306/facturacion
jdbc.fac.url=MDAwMDAwMDAwMDAwMDAwMG9P6VRjJbgY4HNO+fz5AOs2Uko3ENa9gmiSzbIHUDX6q+p84cJzD+9BBySEk8dGR41NbddYG+L4nA6I1qKJ9k7OlNqeAE6gOAfZH73uItUhnqLTcy9yx0q0DgOKs99Y4x+phYUcJmHVoK0FVXF9/Bf3314jHgmKCksUpp1A70Sxifld/Lrm53OdHpqg9E4g0bjlJhj8pvQ7mcjuCYV6kaY=
jdbc.fac.user=MDAwMDAwMDAwMDAwMDAwMKG+OSYC8t9vgQT42Et+pfY=
jdbc.fac.pass=MDAwMDAwMDAwMDAwMDAwMKG+OSYC8t9vgQT42Et+pfY=

# hibernate.X
hibernate.fac.dialect=org.hibernate.dialect.MariaDBDialect
hibernate.fac.show_sql=false
hibernate.fac.hbm2ddl.auto=none
hibernate.fac.cache.use_second_level_cache=false
hibernate.fac.cache.use_query_cache=false

# c3p0.X
c3p0.fac.min_size=5
c3p0.fac.max_size=20
c3p0.fac.acquire_increment=5
c3p0.fac.timeout=1800
c3p0.fac.testConnectionOnCheckout=false
c3p0.fac.testConnectionOnCheckin=true
c3p0.fac.preferredTestQuery=SELECT 1
c3p0.fac.idleConnectionTestPeriod=300
c3p0.fac.privilegeSpawnedThreads=true
c3p0.fac.contextClassLoaderSource=library