import { APP_KEYS, type AppKey } from './appCodes';

export const EVENT_KEYS = {
    COMMON: {
        CLEAR_FILTERS:       'EVT001',
        DOWNLOAD_CSV:        'EVT002',
        VIEW_DETAIL:         'EVT003',
        EDIT:                'EVT004',
        LINK_INVOICE:        'EVT005',
        DOWNLOAD_CSV_DETAIL: 'EVT006',
        LINK_CREDIT_NOTE:    'EVT007',
        SEARCH:              'EVT0008',
        DOWNLOAD_XLS:        'EVT009',
        DOWNLOAD_XML:        'EVT010',
        CANCEL:              'EVT011',
        UPDATE_STATUS:       'EVT012',
        DOWNLOAD_PDF:        'EVT013',
        CONFIRM_REVIEW:      'EVT014',
        REQUEST_REVIEW:      'EVT015',
        PUBLISH:             'EVT016',
        AUTHORIZE:           'EVT017',
        REJECT:              'EVT018',
    },
    RECEPTIONS: {
        DOWNLOAD_CSV:        'EVT002',
        SEARCH:              'EVT0008',
        CLEAR_FILTERS:       'EVT001',
        VIEW_DETAIL:         'EVT003',
        EDIT_RECEPTION:      'EVT004',
        LINK_INVOICE:        'EVT005',
        LINK_CREDIT_NOTE:    'EVT007',
        DOWNLOAD_CSV_DETAIL: 'EVT006',
    },
} as const;

export type EventKey = string;

export const APP_EVENT = {
    RECEPTIONS: {
        DOWNLOAD_CSV:        { app: APP_KEYS.RECEPTIONS, event: EVENT_KEYS.RECEPTIONS.DOWNLOAD_CSV, label: 'Exportar CSV' },
        DOWNLOAD_CSV_DETAIL: { app: APP_KEYS.RECEPTIONS, event: EVENT_KEYS.RECEPTIONS.DOWNLOAD_CSV_DETAIL, label: 'Descargar CSV Detalle' },
        SEARCH:              { app: APP_KEYS.RECEPTIONS, event: EVENT_KEYS.RECEPTIONS.SEARCH, label: 'Buscar' },
        CLEAR_FILTERS:       { app: APP_KEYS.RECEPTIONS, event: EVENT_KEYS.RECEPTIONS.CLEAR_FILTERS, label: 'Limpiar' },
        VIEW_DETAIL:         { app: APP_KEYS.RECEPTIONS, event: EVENT_KEYS.RECEPTIONS.VIEW_DETAIL, label: 'Ver detalle' },
        EDIT_RECEPTION:      { app: APP_KEYS.RECEPTIONS, event: EVENT_KEYS.RECEPTIONS.EDIT_RECEPTION, label: 'Editar recepción' },
        LINK_INVOICE:        { app: APP_KEYS.RECEPTIONS, event: EVENT_KEYS.RECEPTIONS.LINK_INVOICE, label: 'Relacionar factura' },
        LINK_CREDIT_NOTE:    { app: APP_KEYS.RECEPTIONS, event: EVENT_KEYS.RECEPTIONS.LINK_CREDIT_NOTE, label: 'Relacionar nota crédito' },
    },
    CARTA_PORTE: {
        SEARCH:              { app: APP_KEYS.CARTA_PORTE, event: EVENT_KEYS.COMMON.SEARCH, label: 'Buscar' },
        CLEAR_FILTERS:       { app: APP_KEYS.CARTA_PORTE, event: EVENT_KEYS.COMMON.CLEAR_FILTERS, label: 'Limpiar' },
        DOWNLOAD_CSV:        { app: APP_KEYS.CARTA_PORTE, event: EVENT_KEYS.COMMON.DOWNLOAD_CSV, label: 'Exportar CSV' },
        DOWNLOAD_XLS:        { app: APP_KEYS.CARTA_PORTE, event: EVENT_KEYS.COMMON.DOWNLOAD_XLS, label: 'Exportar Excel' },
        DOWNLOAD_XML:        { app: APP_KEYS.CARTA_PORTE, event: EVENT_KEYS.COMMON.DOWNLOAD_XML, label: 'Descargar Carta Porte XML' },
        VIEW_DETAIL:         { app: APP_KEYS.CARTA_PORTE, event: EVENT_KEYS.COMMON.VIEW_DETAIL, label: 'Ver Detalle' },
        CANCEL:              { app: APP_KEYS.CARTA_PORTE, event: EVENT_KEYS.COMMON.CANCEL, label: 'Cancelar' },
        UPDATE_STATUS:       { app: APP_KEYS.CARTA_PORTE, event: EVENT_KEYS.COMMON.UPDATE_STATUS, label: 'Actualizar Guia' },
    },
    DISCOUNTS: {
        SEARCH:              { app: APP_KEYS.DISCOUNTS, event: EVENT_KEYS.COMMON.SEARCH, label: 'Buscar' },
        CLEAR_FILTERS:       { app: APP_KEYS.DISCOUNTS, event: EVENT_KEYS.COMMON.CLEAR_FILTERS, label: 'Limpiar' },
        DOWNLOAD_CSV:        { app: APP_KEYS.DISCOUNTS, event: EVENT_KEYS.COMMON.DOWNLOAD_CSV, label: 'Exportar CSV' },
        VIEW_DETAIL:         { app: APP_KEYS.DISCOUNTS, event: EVENT_KEYS.COMMON.VIEW_DETAIL, label: 'Ver Detalle' },
        LINK_CREDIT_NOTE:    { app: APP_KEYS.DISCOUNTS, event: EVENT_KEYS.COMMON.LINK_CREDIT_NOTE, label: 'Relacionar nota crédito' },
    },
    ACCOUNT_STATEMENT: {
        SEARCH:              { app: APP_KEYS.ACCOUNT_STATEMENT, event: EVENT_KEYS.COMMON.SEARCH, label: 'Buscar' },
        CLEAR_FILTERS:       { app: APP_KEYS.ACCOUNT_STATEMENT, event: EVENT_KEYS.COMMON.CLEAR_FILTERS, label: 'Limpiar' },
        VIEW_DETAIL:         { app: APP_KEYS.ACCOUNT_STATEMENT, event: EVENT_KEYS.COMMON.VIEW_DETAIL, label: 'Ver Estado' },
        DOWNLOAD_PDF:        { app: APP_KEYS.ACCOUNT_STATEMENT, event: EVENT_KEYS.COMMON.DOWNLOAD_PDF },
        CONFIRM_REVIEW:      { app: APP_KEYS.ACCOUNT_STATEMENT, event: EVENT_KEYS.COMMON.CONFIRM_REVIEW, label: 'Autorización' },
        REQUEST_REVIEW:      { app: APP_KEYS.ACCOUNT_STATEMENT, event: EVENT_KEYS.COMMON.REQUEST_REVIEW, label: 'Rechazo' },
    },
    THREE_WAY_MATCH: {
        SEARCH:              { app: APP_KEYS.THREE_WAY_MATCH, event: EVENT_KEYS.COMMON.SEARCH, label: 'Buscar' },
        CLEAR_FILTERS:       { app: APP_KEYS.THREE_WAY_MATCH, event: EVENT_KEYS.COMMON.CLEAR_FILTERS, label: 'Limpiar' },
        DOWNLOAD_CSV:        { app: APP_KEYS.THREE_WAY_MATCH, event: EVENT_KEYS.COMMON.DOWNLOAD_CSV, label: 'Exportar CSV' },
        DOWNLOAD_XLS:        { app: APP_KEYS.THREE_WAY_MATCH, event: EVENT_KEYS.COMMON.DOWNLOAD_XLS, label: 'Exportar Excel' },
    },
    MIGO: {
        SEARCH:              { app: APP_KEYS.MIGO, event: EVENT_KEYS.COMMON.SEARCH, label: 'Buscar' },
        CLEAR_FILTERS:       { app: APP_KEYS.MIGO, event: EVENT_KEYS.COMMON.CLEAR_FILTERS, label: 'Limpiar' },
        DOWNLOAD_CSV:        { app: APP_KEYS.MIGO, event: EVENT_KEYS.COMMON.DOWNLOAD_CSV, label: 'Exportar CSV' },
        DOWNLOAD_CSV_DETAIL: { app: APP_KEYS.MIGO, event: EVENT_KEYS.COMMON.DOWNLOAD_CSV_DETAIL, label: 'Exportar CSV Detalle' },
        VIEW_DETAIL:         { app: APP_KEYS.MIGO, event: EVENT_KEYS.COMMON.VIEW_DETAIL, label: 'Ver Detalle Recepción' },
        PUBLISH:             { app: APP_KEYS.MIGO, event: EVENT_KEYS.COMMON.PUBLISH, label: 'Publicar OC' },
        AUTHORIZE:           { app: APP_KEYS.MIGO, event: EVENT_KEYS.COMMON.AUTHORIZE, label: 'Autorizar' },
        REJECT:              { app: APP_KEYS.MIGO, event: EVENT_KEYS.COMMON.REJECT, label: 'Rechazo' },
    },
    PAYMENT_COMPLEMENTS: {
        SEARCH:              { app: APP_KEYS.PAYMENT_COMPLEMENTS, event: EVENT_KEYS.COMMON.SEARCH, label: 'Buscar' },
        CLEAR_FILTERS:       { app: APP_KEYS.PAYMENT_COMPLEMENTS, event: EVENT_KEYS.COMMON.CLEAR_FILTERS, label: 'Limpiar' },
        DOWNLOAD_CSV:        { app: APP_KEYS.PAYMENT_COMPLEMENTS, event: EVENT_KEYS.COMMON.DOWNLOAD_CSV, label: 'Exportar CSV' },
        DOWNLOAD_CSV_DETAIL: { app: APP_KEYS.PAYMENT_COMPLEMENTS, event: EVENT_KEYS.COMMON.DOWNLOAD_CSV_DETAIL },
        VIEW_DETAIL:         { app: APP_KEYS.PAYMENT_COMPLEMENTS, event: EVENT_KEYS.COMMON.VIEW_DETAIL, label: 'Ver Detalle' },
        DOWNLOAD_XML:        { app: APP_KEYS.PAYMENT_COMPLEMENTS, event: EVENT_KEYS.COMMON.DOWNLOAD_XML, label: 'Descargar XML' },
        DOWNLOAD_PDF:        { app: APP_KEYS.PAYMENT_COMPLEMENTS, event: EVENT_KEYS.COMMON.DOWNLOAD_PDF, label: 'Descargar PDF' },
        PUBLISH:             { app: APP_KEYS.PAYMENT_COMPLEMENTS, event: EVENT_KEYS.COMMON.PUBLISH, label: 'Publicar' },
    },
    INVOICES: {
        SEARCH:              { app: APP_KEYS.INVOICES, event: EVENT_KEYS.COMMON.SEARCH, label: 'Buscar' },
        CLEAR_FILTERS:       { app: APP_KEYS.INVOICES, event: EVENT_KEYS.COMMON.CLEAR_FILTERS, label: 'Limpiar' },
        DOWNLOAD_CSV:        { app: APP_KEYS.INVOICES, event: EVENT_KEYS.COMMON.DOWNLOAD_CSV, label: 'Exportar CSV' },
        VIEW_DETAIL:         { app: APP_KEYS.INVOICES, event: EVENT_KEYS.COMMON.VIEW_DETAIL },
        DOWNLOAD_XML:        { app: APP_KEYS.INVOICES, event: EVENT_KEYS.COMMON.DOWNLOAD_XML, label: 'Ver XML' },
        DOWNLOAD_PDF:        { app: APP_KEYS.INVOICES, event: EVENT_KEYS.COMMON.DOWNLOAD_PDF, label: 'Ver PDF' },
        CANCEL:              { app: APP_KEYS.INVOICES, event: EVENT_KEYS.COMMON.CANCEL, label: 'Cancelar Factura' },
        UPDATE_STATUS:       { app: APP_KEYS.INVOICES, event: EVENT_KEYS.COMMON.UPDATE_STATUS, label: 'Reproceso Contable' },
        LINK_CREDIT_NOTE:    { app: APP_KEYS.INVOICES, event: EVENT_KEYS.COMMON.LINK_CREDIT_NOTE, label: 'Ver Nota Crédito' },
    },
    CREDIT_NOTES: {
        SEARCH:              { app: APP_KEYS.CREDIT_NOTES, event: EVENT_KEYS.COMMON.SEARCH, label: 'Buscar' },
        CLEAR_FILTERS:       { app: APP_KEYS.CREDIT_NOTES, event: EVENT_KEYS.COMMON.CLEAR_FILTERS, label: 'Limpiar' },
        DOWNLOAD_CSV:        { app: APP_KEYS.CREDIT_NOTES, event: EVENT_KEYS.COMMON.DOWNLOAD_CSV, label: 'Exportar CSV' },
        VIEW_DETAIL:         { app: APP_KEYS.CREDIT_NOTES, event: EVENT_KEYS.COMMON.VIEW_DETAIL },
        DOWNLOAD_XML:        { app: APP_KEYS.CREDIT_NOTES, event: EVENT_KEYS.COMMON.DOWNLOAD_XML, label: 'Ver XML' },
        DOWNLOAD_PDF:        { app: APP_KEYS.CREDIT_NOTES, event: EVENT_KEYS.COMMON.DOWNLOAD_PDF, label: 'Ver PDF' },
        CANCEL:              { app: APP_KEYS.CREDIT_NOTES, event: EVENT_KEYS.COMMON.CANCEL, label: 'Cancelar Nota Crédito' },
        PUBLISH:             { app: APP_KEYS.CREDIT_NOTES, event: EVENT_KEYS.COMMON.PUBLISH, label: 'Agregar Nota de Crédito' },
        LINK_INVOICE:        { app: APP_KEYS.CREDIT_NOTES, event: EVENT_KEYS.COMMON.LINK_INVOICE, label: 'Ver Factura' },
    },
    PAYMENTS: {
        SEARCH:              { app: APP_KEYS.PAYMENTS, event: EVENT_KEYS.COMMON.SEARCH, label: 'Buscar' },
        CLEAR_FILTERS:       { app: APP_KEYS.PAYMENTS, event: EVENT_KEYS.COMMON.CLEAR_FILTERS, label: 'Limpiar' },
        DOWNLOAD_CSV:        { app: APP_KEYS.PAYMENTS, event: EVENT_KEYS.COMMON.DOWNLOAD_CSV, label: 'Descargar CSV' },
        DOWNLOAD_CSV_DETAIL: { app: APP_KEYS.PAYMENTS, event: EVENT_KEYS.COMMON.DOWNLOAD_CSV_DETAIL },
        VIEW_DETAIL:         { app: APP_KEYS.PAYMENTS, event: EVENT_KEYS.COMMON.VIEW_DETAIL, label: 'Ver Detalle' },
    },
} as const satisfies Record<string, Record<string, { app: AppKey; event: EventKey; label?: string }>>;

export type AppEvent = { app: AppKey; event: EventKey; label?: string };
