apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PROJECT_NAME}
spec:
  template:
    spec:
      automountServiceAccountToken: false
      containers:
        - name: ${PROJECT_NAME}
          resources:
            limits:
              memory: 512Mi
              ephemeral-storage: 500Mi
            requests:
              cpu: 100m
              memory: 256Mi
              ephemeral-storage: 100Mi
