
package com.falabella.mdwcorp.sod.corp.osb.wsdl.cliente.factura.confirmar_v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */

@WebServiceClient(name = "ClienteFacturaConfirmarService", targetNamespace = "http://mdwcorp.falabella.com/SOD/CORP/OSB/wsdl/Cliente/Factura/Confirmar-v1.0", wsdlLocation = "http://10.138.153.10:8080/wsmdlwticket/Factura/Confirmar/v1.0?wsdl")
//@WebServiceClient(name = "ClienteFacturaConfirmarService", targetNamespace = "http://mdwcorp.falabella.com/SOD/CORP/OSB/wsdl/Cliente/Factura/Confirmar-v1.0", wsdlLocation = "http://10.138.150.88:8080/wsmdlwticket/Factura/Confirmar/v1.0?wsdl")
public class ClienteFacturaConfirmarService
    extends Service
{

    private final static URL CLIENTEFACTURACONFIRMARSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIENTEFACTURACONFIRMARSERVICE_EXCEPTION;
    private final static QName CLIENTEFACTURACONFIRMARSERVICE_QNAME = new QName("http://mdwcorp.falabella.com/SOD/CORP/OSB/wsdl/Cliente/Factura/Confirmar-v1.0", "ClienteFacturaConfirmarService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.138.153.10:8080/wsmdlwticket/Factura/Confirmar/v1.0?wsdl");
            //url = new URL("http://10.138.150.88:8080/wsmdlwticket/Factura/Confirmar/v1.0?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTEFACTURACONFIRMARSERVICE_WSDL_LOCATION = url;
        CLIENTEFACTURACONFIRMARSERVICE_EXCEPTION = e;
    }

    public ClienteFacturaConfirmarService() {
        super(__getWsdlLocation(), CLIENTEFACTURACONFIRMARSERVICE_QNAME);
    }

    public ClienteFacturaConfirmarService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTEFACTURACONFIRMARSERVICE_QNAME, features);
    }

    public ClienteFacturaConfirmarService(URL wsdlLocation) {
        super(wsdlLocation, CLIENTEFACTURACONFIRMARSERVICE_QNAME);
    }

    public ClienteFacturaConfirmarService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTEFACTURACONFIRMARSERVICE_QNAME, features);
    }

    public ClienteFacturaConfirmarService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClienteFacturaConfirmarService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClienteFacturaConfirmarPt
     */
    @WebEndpoint(name = "ClienteFacturaConfirmarPort")
    public ClienteFacturaConfirmarPt getClienteFacturaConfirmarPort() {
        return super.getPort(new QName("http://mdwcorp.falabella.com/SOD/CORP/OSB/wsdl/Cliente/Factura/Confirmar-v1.0", "ClienteFacturaConfirmarPort"), ClienteFacturaConfirmarPt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClienteFacturaConfirmarPt
     */
    @WebEndpoint(name = "ClienteFacturaConfirmarPort")
    public ClienteFacturaConfirmarPt getClienteFacturaConfirmarPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mdwcorp.falabella.com/SOD/CORP/OSB/wsdl/Cliente/Factura/Confirmar-v1.0", "ClienteFacturaConfirmarPort"), ClienteFacturaConfirmarPt.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTEFACTURACONFIRMARSERVICE_EXCEPTION!= null) {
            throw CLIENTEFACTURACONFIRMARSERVICE_EXCEPTION;
        }
        return CLIENTEFACTURACONFIRMARSERVICE_WSDL_LOCATION;
    }

}
