
package com.falabella.mdwcorp.sod.corp.osb.wsdl.cliente.factura.confirmar_v1;

import javax.xml.ws.WebFault;
import org.xmlsoap.schemas.soap.envelope.Fault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Fault", targetNamespace = "http://schemas.xmlsoap.org/soap/envelope/")
public class FaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private Fault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FaultMsg(String message, Fault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public FaultMsg(String message, Fault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.xmlsoap.schemas.soap.envelope.Fault
     */
    public Fault getFaultInfo() {
        return faultInfo;
    }

}
