
package com.falabella.mdwcorp.sod.corp.osb.wsdl.cliente.ticket.obtener_v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.falabella.mdwcorp.sod.corp.osb.schema.cliente.ticket.obtener.req_v2018.ClienteTicketObtenerExpReqTYPE;
import com.falabella.mdwcorp.sod.corp.osb.schema.cliente.ticket.obtener.resp_v2018.ClienteTicketObtenerExpRespTYPE;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClienteTicketObtenerPt", targetNamespace = "http://mdwcorp.falabella.com/SOD/CORP/OSB/wsdl/Cliente/Ticket/Obtener-v1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.falabella.mdwcorp.sod.corp.osb.schema.cliente.ticket.obtener.resp_v2018.ObjectFactory.class,
    com.falabella.mdwcorp.common.schema.clientservice.ObjectFactory.class,
    com.falabella.mdwcorp.sod.corp.osb.schema.cliente.ticket.obtener.req_v2018.ObjectFactory.class,
    org.xmlsoap.schemas.soap.envelope.ObjectFactory.class
})
public interface ClienteTicketObtenerPt {


    /**
     * 
     * @param clienteTicketObtenerReqParam
     * @return
     *     returns com.falabella.mdwcorp.sod.corp.osb.schema.cliente.ticket.obtener.resp_v2018.ClienteTicketObtenerExpRespTYPE
     * @throws FaultMsg
     */
    @WebMethod(operationName = "ClienteTicketObtenerOp", action = "http://mdwcorp.falabella.com/SOD/CORP/OSB/wsdl/Cliente/Ticket/Obtener-v1.0/Op")
    @WebResult(name = "ClienteTicketObtenerExpResp", targetNamespace = "http://mdwcorp.falabella.com/SOD/CORP/OSB/schema/Cliente/Ticket/Obtener/Resp-v2018.02", partName = "ClienteTicketObtenerRespParam")
    public ClienteTicketObtenerExpRespTYPE clienteTicketObtenerOp(
        @WebParam(name = "ClienteTicketObtenerExpReq", targetNamespace = "http://mdwcorp.falabella.com/SOD/CORP/OSB/schema/Cliente/Ticket/Obtener/Req-v2018.02", partName = "ClienteTicketObtenerReqParam")
        ClienteTicketObtenerExpReqTYPE clienteTicketObtenerReqParam)
        throws FaultMsg
    ;

}
