
package com.falabella.mdwcorp.sod.corp.osb.wsdl.cliente.ticket.obtener_v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */

//@WebServiceClient(name = "ClienteTicketObtenerService", targetNamespace = "http://mdwcorp.falabella.com/SOD/CORP/OSB/wsdl/Cliente/Ticket/Obtener-v1.0", wsdlLocation = "http://10.138.150.88:8080/wsmdlwticket/Ticket/Obtener/v1.0?wsdl")
@WebServiceClient(name = "ClienteTicketObtenerService", targetNamespace = "http://mdwcorp.falabella.com/SOD/CORP/OSB/wsdl/Cliente/Ticket/Obtener-v1.0", wsdlLocation = "http://10.138.153.10:8080/wsmdlwticket/Ticket/Obtener/v1.0?wsdl")
public class ClienteTicketObtenerService
    extends Service
{

    private final static URL CLIENTETICKETOBTENERSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIENTETICKETOBTENERSERVICE_EXCEPTION;
    private final static QName CLIENTETICKETOBTENERSERVICE_QNAME = new QName("http://mdwcorp.falabella.com/SOD/CORP/OSB/wsdl/Cliente/Ticket/Obtener-v1.0", "ClienteTicketObtenerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	//url = new URL("http://10.138.150.88:8080/wsmdlwticket/Ticket/Obtener/v1.0?wsdl");
        	url = new URL("http://10.138.153.10:8080/wsmdlwticket/Ticket/Obtener/v1.0?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTETICKETOBTENERSERVICE_WSDL_LOCATION = url;
        CLIENTETICKETOBTENERSERVICE_EXCEPTION = e;
    }

    public ClienteTicketObtenerService() {
        super(__getWsdlLocation(), CLIENTETICKETOBTENERSERVICE_QNAME);
    }

    public ClienteTicketObtenerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTETICKETOBTENERSERVICE_QNAME, features);
    }

    public ClienteTicketObtenerService(URL wsdlLocation) {
        super(wsdlLocation, CLIENTETICKETOBTENERSERVICE_QNAME);
    }

    public ClienteTicketObtenerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTETICKETOBTENERSERVICE_QNAME, features);
    }

    public ClienteTicketObtenerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClienteTicketObtenerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClienteTicketObtenerPt
     */
    @WebEndpoint(name = "ClienteTicketObtenerPort")
    public ClienteTicketObtenerPt getClienteTicketObtenerPort() {
        return super.getPort(new QName("http://mdwcorp.falabella.com/SOD/CORP/OSB/wsdl/Cliente/Ticket/Obtener-v1.0", "ClienteTicketObtenerPort"), ClienteTicketObtenerPt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClienteTicketObtenerPt
     */
    @WebEndpoint(name = "ClienteTicketObtenerPort")
    public ClienteTicketObtenerPt getClienteTicketObtenerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mdwcorp.falabella.com/SOD/CORP/OSB/wsdl/Cliente/Ticket/Obtener-v1.0", "ClienteTicketObtenerPort"), ClienteTicketObtenerPt.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTETICKETOBTENERSERVICE_EXCEPTION!= null) {
            throw CLIENTETICKETOBTENERSERVICE_EXCEPTION;
        }
        return CLIENTETICKETOBTENERSERVICE_WSDL_LOCATION;
    }

}
