
package com.sodimac.fiscal.api.detecno.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "IService1", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IService1 {


    /**
     * 
     * @return
     *     returns com.sodimac.fiscal.validacion.consumingwebservice.wsdl.Resultado
     */
    @WebMethod(operationName = "TestBD", action = "http://tempuri.org/IService1/TestBD")
    @WebResult(name = "TestBDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TestBD", targetNamespace = "http://tempuri.org/", className = "com.sodimac.fiscal.validacion.consumingwebservice.wsdl.TestBD")
    @ResponseWrapper(localName = "TestBDResponse", targetNamespace = "http://tempuri.org/", className = "com.sodimac.fiscal.validacion.consumingwebservice.wsdl.TestBDResponse")
    public Resultado testBD();

    /**
     * 
     * @param password
     * @param xmlPassed
     * @param licencia
     * @param usuario
     * @return
     *     returns com.sodimac.fiscal.validacion.consumingwebservice.wsdl.Resultado
     */
    @WebMethod(action = "http://tempuri.org/IService1/validarXML")
    @WebResult(name = "validarXMLResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "validarXML", targetNamespace = "http://tempuri.org/", className = "com.sodimac.fiscal.validacion.consumingwebservice.wsdl.ValidarXML")
    @ResponseWrapper(localName = "validarXMLResponse", targetNamespace = "http://tempuri.org/", className = "com.sodimac.fiscal.validacion.consumingwebservice.wsdl.ValidarXMLResponse")
    public Resultado validarXML(
        @WebParam(name = "usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "licencia", targetNamespace = "http://tempuri.org/")
        String licencia,
        @WebParam(name = "xmlPassed", targetNamespace = "http://tempuri.org/")
        ValidarXML.XmlPassed xmlPassed);

}
