#/*------------------------------------------------*
# *   Copyright (c) SODIMAC. May 2021.             *
# *   Portal web: www.sodimac.com.mx.              *
# *   Contributors:                                *
# *     Vantis S. de RL. de CV. Web: vantis.mx     *
# *     Fabian Alvarez <fabian.alvarez@vantis.mx>  *
#--------------------------------------------------*/

#DATASOURCE
################################## SI ESTOS DATOS CAMBIAN, IGUAL SE DEBE CAMBIAR EN LA CLASE UTIL/CONEXION.JAVA
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://10.138.150.124:5319;databaseName=SODIMAC_REBATES_PROD
spring.datasource.username=SodimacUsrReb
spring.datasource.password=#50d1mac

################################## AMBIENTE DE PRUEBAS
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.datasource.url=jdbc:sqlserver://10.138.153.10;databaseName=SODIMAC_REBATES_DEV
#spring.datasource.username=SodimacDevUsr
#spring.datasource.password=Pa55wordDev


#JPA
spring.jpa.generate-ddl=false
spring.jpa.database-platform=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#MULTIPART
spring.servlet.multipart.enabled=true
spring.servlet.multipart.location=c:/tmp/
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=50MB

#SFTP
sodimac.rebates.sftp.host=10.138.150.68
sodimac.rebates.sftp.port=22
sodimac.rebates.sftp.user=rebates_admin
sodimac.rebates.sftp.password=@dm1nR3b@t3$
sodimac.rebates.sftp.remote.directory=/

#EMAIL CONFIG
spring.mail.protocol=smtp
spring.mail.host=sodimac-com-mx.mail.protection.outlook.com
spring.mail.port=25
spring.mail.username=notificaciones.ti_sod@sodimac.com.mx
spring.mail.password=#Pa55word

spring.mail.test-connection=false
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mail.smtp.starttls.enable=true
mail.smtp.starttls.required=true

#SERVER
server.port=7070
server.error.include-stacktrace=always

#VERSION
sodimac.rebates.version=3.1.5