# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: safep-sale-confirmed-sa
#   annotations:
#     iam.gke.io/gcp-service-account: safep-sale-confirmed@fal-corp-safe-platform-uat.iam.gserviceaccount.com