import { Router } from "express";
import * as ctrl from "@/controllers/rebate.controller.js";
import * as fiscalCtrl from "@/controllers/rebateFiscal.controller.js";
import { getFiscalDetail } from "@/controllers/rebateDetail.controller.js";
import { getOrders, syncOrders } from "@/controllers/rebateOrders.controller.js";

const router = Router();
router.post("/relate", fiscalCtrl.relateRebate);
router.post("/filter", fiscalCtrl.searchRebates);
router.post("/purchase-order-details/sync", syncOrders);
router.get("/published", ctrl.getPublishedRebates);
router.get("/published/export/csv", ctrl.exportPublishedRebatesToCsv);
router.get("/search", ctrl.searchRebates);
router.get("/export/csv", ctrl.exportFilteredRebatesToCsv);
router.get("/vendor/:vendorNumber", ctrl.getRebatesByVendor);
router.get("/", ctrl.list);
router.get("/:uuid/fiscal-detail", getFiscalDetail);
router.get("/:uuid/purchase-order-details", getOrders);
router.get("/:uuid", ctrl.getById);
router.post("/", ctrl.create);
router.put("/:uuid", ctrl.update);
router.delete("/:uuid", ctrl.remove);
export default router;
