/** Token decoded de ejemplo (PORCELANITE / zedlav.sd87@gmail.com). */
export const EXAMPLE_TOKEN_DECODED: Record<string, unknown> = {
  exp: 1790292160,
  iat: 1790291860,
  auth_time: 1790291858,
  jti: "onrtac:767c939d-76bc-99c8-afb8-2a80bb13763b",
  iss: "https://qa-access-key-corp.falabella.tech/auth/realms/corp",
  aud: [
    "portal",
    "fbc-market-insights",
    "rebate-management-client",
    "b2bf-fiscal",
    "vendor-backend",
    "b2bf-utilerias",
    "fbc-proforma-invoice",
    "b2bf-catalogos",
    "broker",
    "apicurio-studio",
    "b2bf-auditoria",
    "fbc-vcm-onboarding",
    "rpc-portal",
    "fbc-pom",
    "fbc-finance",
    "fulfillment-portal-public",
    "b2bf-finanzas",
    "fbc-aclaraciones",
    "fbc-vev",
    "account",
  ],
  sub: "4b36d77f-5b01-4889-bcfc-ef8abe130ade",
  typ: "Bearer",
  azp: "portal",
  sid: "QJn1gn7dWhE9fcZYV_iZgXlG",
  acr: "1",
  "allowed-origins": ["http://localhost:3000/*", "*"],
  realm_access: {
    roles: [
      "default-roles-corp",
      "offline_access",
      "FBC_NATIONAL_SUPPLIER_FINANCE_USER",
      "FBC_NATIONAL_LOGISTICS_SUPPLIER_USER",
      "uma_authorization",
      "FBC_NATIONAL_COMMERCIAL_SUPPLIER_USER",
      "sr-readonly",
    ],
  },
  resource_access: {
    "fbc-market-insights": { roles: ["view"] },
    "rebate-management-client": { roles: ["vendor-rbm-report"] },
    "b2bf-fiscal": { roles: ["ppsomx-admin", "ppsomx-vendor"] },
    "vendor-backend": { roles: ["vendor"] },
    "b2bf-utilerias": { roles: ["ppsomx-admin", "ppsomx-vendor"] },
    "fbc-proforma-invoice": { roles: ["view", "create"] },
    "b2bf-catalogos": { roles: ["ppsomx-admin", "ppsomx-vendor"] },
    broker: { roles: ["read-token"] },
    "apicurio-studio": { roles: ["read-token", "sr-readonly"] },
    "b2bf-auditoria": { roles: ["ppsomx-admin", "ppsomx-vendor"] },
    "fbc-vcm-onboarding": { roles: ["view", "edit"] },
    "rpc-portal": {
      roles: [
        "product-create",
        "product-list",
        "product-edit",
        "product-create-masXve",
        "product-download",
        "product-edit-masXve",
      ],
    },
    "fbc-pom": { roles: ["view"] },
    "fbc-finance": { roles: ["view"] },
    "fulfillment-portal-public": {
      roles: ["vendor_appointment", "vendor", "vendor_eASN", "vendor_VEV_DP"],
    },
    "b2bf-finanzas": { roles: ["ppsomx-admin", "ppsomx-vendor"] },
    "fbc-aclaraciones": { roles: ["ppsomx-vendor"] },
    "fbc-vev": { roles: ["view", "stock_upload", "stock_view"] },
    account: { roles: ["manage-account", "manage-account-links", "view-profile"] },
  },
  scope: "openid profile portal email",
  email_verified: true,
  "vendors-taxs": [
    {
      name: "BTICINO AZUL",
      taxId: "20100183588",
      operation: [
        { businessUnit: "SOD", country: ["PE"] },
        { businessUnit: "FAL", country: ["PE"] },
        { businessUnit: "TOT", country: ["PE"] },
      ],
      country: "PE",
    },
    {
      name: "E LEGTRIC S.A.S.",
      taxId: "9004801262",
      operation: [
        { businessUnit: "FAL", country: ["CO"] },
        { businessUnit: "SOD", country: ["CO"] },
      ],
      country: "CO",
    },
    {
      name: "Cela Cosmeticos",
      taxId: "969208407",
      operation: [
        { businessUnit: "SOD", country: ["CL"] },
        { businessUnit: "FAL", country: ["CL"] },
        { businessUnit: "TOT", country: ["CL"] },
      ],
      country: "CL",
    },
    {
      name: "3M ARGENTINA S.A.",
      taxId: "35529994393",
      operation: [{ businessUnit: "SOD", country: ["AR"] }],
      country: "AR",
    },
    {
      name: "KATMEN S.A.",
      taxId: "211830520013",
      operation: [{ businessUnit: "SOD", country: ["UY"] }],
      country: "UY",
    },
    {
      name: "IMPLATEC",
      taxId: "80709876000736",
      operation: [{ businessUnit: "SOD", country: ["BR"] }],
      country: "BR",
    },
    {
      name: "PORCELANITE",
      taxId: "PLA071206TS4",
      operation: [{ businessUnit: "SOD", country: ["MX"] }],
      country: "MX",
    },
  ],
  "vendors-taxs_masive": [
    '[{"name":"BTICINO AZUL","taxId":"20100183588","operation":[{"businessUnit":"SOD","country":["PE"]},{"businessUnit":"FAL","country":["PE"]},{"businessUnit":"TOT","country":["PE"]}],"country":"PE"},{"name":"E LEGTRIC S.A.S.","taxId":"9004801262","operation":[{"businessUnit":"FAL","country":["CO"]},{"businessUnit":"SOD","country":["CO"]}],"country":"CO"},{"name":"Cela Cosmeticos","taxId":"969208407","operation":[{"businessUnit":"SOD","country":["CL"]},{"businessUnit":"FAL","country":["CL"]},{"businessUnit":"TOT","country":["CL"]}],"country":"CL"},{"name":"3M ARGENTINA S.A.","taxId":"35529994393","operation":[{"businessUnit":"SOD","country":["AR"]}],"country":"AR"},{"name":"KATMEN S.A.","taxId":"211830520013","operation":[{"businessUnit":"SOD","country":["UY"]}],"country":"UY"},{"name":"IMPLATEC","taxId":"80709876000736","operation":[{"businessUnit":"SOD","country":["BR"]}],"country":"BR"},{"name":"PORCELANITE","taxId":"PLA071206TS4","operation":[{"businessUnit":"SOD","country":["MX"]}],"country":"MX"}]',
  ],
  name: "PORCELANITE PORCELANITE",
  groups: [
    "/Omnichannel-Retail/Merchandise/CORP/SOD/AR",
    "/Omnichannel-Retail/Merchandise/CORP/SOD/BR",
    "/Omnichannel-Retail/Merchandise/CORP/TOT/CL",
    "/Omnichannel-Retail/Merchandise/CORP/SOD/CL",
    "/Omnichannel-Retail/Merchandise/CORP/FAL/CL",
    "/Omnichannel-Retail/Merchandise/CORP/SOD/CO",
    "/Omnichannel-Retail/Merchandise/CORP/FAL/CO",
    "/Omnichannel-Retail/Merchandise/CORP/SOD/MX",
    "/Omnichannel-Retail/Merchandise/CORP/SOD/PE",
    "/Omnichannel-Retail/Merchandise/CORP/TOT/PE",
    "/Omnichannel-Retail/Merchandise/CORP/FAL/PE",
    "/Omnichannel-Retail/Merchandise/CORP/SOD/UY",
  ],
  preferred_username: "zedlav.sd87@gmail.com",
  given_name: "PORCELANITE",
  family_name: "PORCELANITE",
  email: "zedlav.sd87@gmail.com",
};
