-- Analisis de longitudes vs limites
SELECT 'EMPRESA' AS Campo, 5 AS Limite, MAX(LEN(ISNULL(EMPRESA, ''))) AS MaxReal,
       CASE WHEN MAX(LEN(ISNULL(EMPRESA, ''))) > 5 THEN '*** EXCEDE ***' ELSE 'OK' END AS Estado
FROM [dbo].[Envios_Ap_Temp] WHERE FLAG_ENVIADO = 0
UNION ALL
SELECT 'REFERENCIA_DOCUMENTO', 20, MAX(LEN(ISNULL(LTRIM(RTRIM(REFERENCIA_DOCUMENTO)), ''))),
       CASE WHEN MAX(LEN(ISNULL(LTRIM(RTRIM(REFERENCIA_DOCUMENTO)), ''))) > 20 THEN '*** EXCEDE ***' ELSE 'OK' END
FROM [dbo].[Envios_Ap_Temp] WHERE FLAG_ENVIADO = 0
UNION ALL
SELECT 'NUMERO_DOCUMENTO', 30, MAX(LEN(ISNULL(LTRIM(RTRIM(NUMERO_DOCUMENTO)), ''))),
       CASE WHEN MAX(LEN(ISNULL(LTRIM(RTRIM(NUMERO_DOCUMENTO)), ''))) > 30 THEN '*** EXCEDE ***' ELSE 'OK' END
FROM [dbo].[Envios_Ap_Temp] WHERE FLAG_ENVIADO = 0
UNION ALL
SELECT 'MONEDA', 3, MAX(LEN(ISNULL(LTRIM(RTRIM(MONEDA)), ''))),
       CASE WHEN MAX(LEN(ISNULL(LTRIM(RTRIM(MONEDA)), ''))) > 3 THEN '*** EXCEDE ***' ELSE 'OK' END
FROM [dbo].[Envios_Ap_Temp] WHERE FLAG_ENVIADO = 0
UNION ALL
SELECT 'CUENTA_CONTABLE', 12, MAX(LEN(ISNULL(CUENTA_CONTABLE, ''))),
       CASE WHEN MAX(LEN(ISNULL(CUENTA_CONTABLE, ''))) > 12 THEN '*** EXCEDE ***' ELSE 'OK' END
FROM [dbo].[Envios_Ap_Temp] WHERE FLAG_ENVIADO = 0
UNION ALL
SELECT 'CODIGO_PROVEEDOR', 10, MAX(LEN(ISNULL(CODIGO_PROVEEDOR, ''))),
       CASE WHEN MAX(LEN(ISNULL(CODIGO_PROVEEDOR, ''))) > 10 THEN '*** EXCEDE ***' ELSE 'OK' END
FROM [dbo].[Envios_Ap_Temp] WHERE FLAG_ENVIADO = 0
UNION ALL
SELECT 'SUCURSAL', 5, MAX(LEN(ISNULL(SUCURSAL, ''))),
       CASE WHEN MAX(LEN(ISNULL(SUCURSAL, ''))) > 5 THEN '*** EXCEDE ***' ELSE 'OK' END
FROM [dbo].[Envios_Ap_Temp] WHERE FLAG_ENVIADO = 0
UNION ALL
SELECT 'CONDICION_PAGO', 4, MAX(LEN(ISNULL(CONDICION_PAGO, ''))),
       CASE WHEN MAX(LEN(ISNULL(CONDICION_PAGO, ''))) > 4 THEN '*** EXCEDE ***' ELSE 'OK' END
FROM [dbo].[Envios_Ap_Temp] WHERE FLAG_ENVIADO = 0
UNION ALL
SELECT 'SISTEMA_ORIGEN', 30, MAX(LEN(ISNULL(SISTEMA_ORIGEN, ''))),
       CASE WHEN MAX(LEN(ISNULL(SISTEMA_ORIGEN, ''))) > 30 THEN '*** EXCEDE ***' ELSE 'OK' END
FROM [dbo].[Envios_Ap_Temp] WHERE FLAG_ENVIADO = 0
UNION ALL
SELECT 'CLASE_DOCUMENTO', 2, MAX(LEN(ISNULL(CLASE_DOCUMENTO, ''))),
       CASE WHEN MAX(LEN(ISNULL(CLASE_DOCUMENTO, ''))) > 2 THEN '*** EXCEDE ***' ELSE 'OK' END
FROM [dbo].[Envios_Ap_Temp] WHERE FLAG_ENVIADO = 0
UNION ALL
SELECT 'NUMERO_REFERENCIA', 18, MAX(LEN(ISNULL(NUMERO_REFERENCIA, ''))),
       CASE WHEN MAX(LEN(ISNULL(NUMERO_REFERENCIA, ''))) > 18 THEN '*** EXCEDE ***' ELSE 'OK' END
FROM [dbo].[Envios_Ap_Temp] WHERE FLAG_ENVIADO = 0
UNION ALL
SELECT 'CENTRO_COSTO', 10, MAX(LEN(ISNULL(CENTRO_COSTO, ''))),
       CASE WHEN MAX(LEN(ISNULL(CENTRO_COSTO, ''))) > 10 THEN '*** EXCEDE ***' ELSE 'OK' END
FROM [dbo].[Envios_Ap_Temp] WHERE FLAG_ENVIADO = 0
UNION ALL
SELECT 'CENTRO_BENEFICIO', 10, MAX(LEN(ISNULL(CENTRO_BENEFICIO, ''))),
       CASE WHEN MAX(LEN(ISNULL(CENTRO_BENEFICIO, ''))) > 10 THEN '*** EXCEDE ***' ELSE 'OK' END
FROM [dbo].[Envios_Ap_Temp] WHERE FLAG_ENVIADO = 0
UNION ALL
SELECT 'NUMERO_UUID', 36, MAX(LEN(ISNULL(LTRIM(RTRIM(NUMERO_UUID)), ''))),
       CASE WHEN MAX(LEN(ISNULL(LTRIM(RTRIM(NUMERO_UUID)), ''))) > 36 THEN '*** EXCEDE ***' ELSE 'OK' END
FROM [dbo].[Envios_Ap_Temp] WHERE FLAG_ENVIADO = 0
UNION ALL
SELECT 'TIPO_DOCUMENTO', 20, MAX(LEN(ISNULL(LTRIM(RTRIM(TIPO_DOCUMENTO)), ''))),
       CASE WHEN MAX(LEN(ISNULL(LTRIM(RTRIM(TIPO_DOCUMENTO)), ''))) > 20 THEN '*** EXCEDE ***' ELSE 'OK' END
FROM [dbo].[Envios_Ap_Temp] WHERE FLAG_ENVIADO = 0
UNION ALL
SELECT 'DEBITO_CREDITO', 1, MAX(LEN(ISNULL(DEBITO_CREDITO, ''))),
       CASE WHEN MAX(LEN(ISNULL(DEBITO_CREDITO, ''))) > 1 THEN '*** EXCEDE ***' ELSE 'OK' END
FROM [dbo].[Envios_Ap_Temp] WHERE FLAG_ENVIADO = 0
ORDER BY Estado DESC, Campo;
