apiVersion: v1
kind: ConfigMap
metadata:
  name: ${PROJECT_NAME}-configmap
data:
  LOCAL_PORT: "3800"
  LOCAL_CONTEXT: "/api/utils"
  REMOTE_URL: "http://mrch-backend-somx-utils-api:3712"
  HEALTH_PATH: "/health"
