apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PROJECT_NAME}
spec:
  template:
    spec:
      serviceAccountName: ${WORLOAD_IDENTITY_UAT}
      automountServiceAccountToken: false
      containers:
        - name: ${PROJECT_NAME}
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
              ephemeral-storage: 100Mi
            limits:
              memory: 400Mi
              ephemeral-storage: 500Mi
