# jdbc.X
jdbc.fac.driverClassName=org.mariadb.jdbc.Driver

#Prod
jdbc.fac.url=jdbc:mysql://10.138.150.77:3306/facturacion?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CST6CDT
jdbc.fac.user=facturaUser
jdbc.fac.pass=facturaUser

#Dev
#jdbc.fac.url=jdbc:mysql://10.138.153.10:4306/facturacion?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CST6CDT
#jdbc.fac.user=facturaUser
#jdbc.fac.pass=facturaUser

# hibernate.X
hibernate.fac.dialect=org.hibernate.dialect.MariaDBDialect
hibernate.fac.show_sql=false
hibernate.fac.hbm2ddl.auto=none
hibernate.fac.cache.use_second_level_cache=false
hibernate.fac.cache.use_query_cache=false

# c3p0.X
c3p0.fac.min_size=5
c3p0.fac.max_size=20
c3p0.fac.acquire_increment=5
c3p0.fac.timeout=1800
c3p0.fac.testConnectionOnCheckout=false
c3p0.fac.testConnectionOnCheckin=true
c3p0.fac.preferredTestQuery=SELECT 1
c3p0.fac.idleConnectionTestPeriod=300
c3p0.fac.privilegeSpawnedThreads=true
c3p0.fac.contextClassLoaderSource=library