# jdbc.X
jdbc.bct.driverClassName=oracle.jdbc.driver.OracleDriver

#Prod
jdbc.bct.url=jdbc:oracle:thin:@ramsay.falabella.cl:1531:arsmxpr
jdbc.bct.user=BATSW_FAC
jdbc.bct.pass=M5R89NJYVS
#Recuerda cambiar ClienteTicketObtenerService y ClienteFacturaConfirmarService

#Dev
#jdbc.bct.url=jdbc:oracle:thin:@10.242.7.48:1541:arsmxts
#jdbc.bct.user=BATSW_FAC
#jdbc.bct.pass=lAMSL01LAM2

#Dev ACTUAL
#jdbc.bct.url=jdbc:oracle:thin:@f8cloud1129:1541:arsmxts
#jdbc.bct.user=oromero
#jdbc.bct.pass=DFVGRTHJy1Gj

# hibernate.X
hibernate.bct.dialect=org.hibernate.dialect.Oracle10gDialect
hibernate.bct.show_sql=false
hibernate.bct.hbm2ddl.auto=none
hibernate.bct.cache.use_second_level_cache=false
hibernate.bct.cache.use_query_cache=false

# c3p0.X
c3p0.bct.min_size=5
c3p0.bct.max_size=20
c3p0.bct.acquire_increment=5
c3p0.bct.timeout=1800
c3p0.bct.testConnectionOnCheckout=false
c3p0.bct.testConnectionOnCheckin=true
c3p0.bct.preferredTestQuery=SELECT 1 from dual
c3p0.bct.idleConnectionTestPeriod=300
c3p0.bct.privilegeSpawnedThreads=true
c3p0.bct.contextClassLoaderSource=library