# ===============================
# CONFIGURACIÓN PARA PRODUCCIÓN
# ===============================

spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

# SECURITY CONFIGURATION
security.enabled=${FINANZAS_JWT_ENABLED:false}

pac.detecno.name=DETECNO
pac.carbajal.name=CARBAJAL

# DATABASE CONFIGURATION
spring.datasource.url=jdbc:postgresql://${DB_HOST:10.100.0.29}:${DB_PORT:5432}/${DB_NAME:b2b_portal}?currentSchema=tenant_fiscal&ssl=${DB_SSL:true}
spring.datasource.username=${DB_USER:wwwb2bportal}
spring.datasource.password=${DB_PASS:}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=tenant_fiscal

# LOGGING LEVEL (más restrictivo en prod)
logging.level.root=WARN
logging.level.Console=WARN
logging.level.com.sodimac=INFO

# ACTUATOR (más restrictivo en prod)
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when-authorized

# UTILS API CONFIGURATION
utils.api.url=${UTIL_API_URL:http://utils-api:8080}
