# ===============================
# CONFIGURACIÓN PARA DESARROLLO
# ===============================

spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

# SECURITY CONFIGURATION
security.enabled=${FINANZAS_JWT_ENABLED:false}

pac.detecno.name=DETECNO
pac.carbajal.name=CARBAJAL

spring.jpa.properties.hibernate.default_schema=tenant_fiscal

# LOGGING LEVEL (más detallado en dev)
logging.level.root=INFO
logging.level.Console=INFO
logging.level.com.sodimac=DEBUG

# ACTUATOR (completo en dev)
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

