sonar.projectKey= mrch.frontend.somx.util.spa	
sonar.projectName= mrch.frontend.somx.util.spa	
sonar.sources=.
sonar.exclusions=**/*.js,**/*.css,**/*.html,src/test/**
sonar.language=ts
sonar.sourceEncoding=UTF-8
