sonar.projectKey=mrch.backend.cross.core.chatbot
sonar.organization=falabella-merchand
sonar.exclusions=**/node_modules/**,**/dist/**,**/src/main.ts,**/src/module-config/infrastructure/firestore/firestore-config.ts, **/src/module-config/infrastructure/dependencies/container.ts, **/src/module-config/infrastructure/middleware/**, **/src/module-config/infrastructure/exceptions/**, **/src/module-config/infrastructure/security/**, **/src/module-config/infrastructure/secrets/**, **/src/module-config/infrastructure/secrets/**, **/src/module-config/infrastructure/mysql/**, **/src/module-config/infrastructure/validators/**

sonar.sources=src
sonar.tests=tests
sonar.typescript.lcov.reportPaths=coverage/lcov.info