import type { OpenAPIV3 } from "openapi-types";

const UUID_EXAMPLE = "209279be-37c7-4154-b3c6-df976fd7b6a";
const UUID_PATTERN =
    "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$";

const FOLIO_PATTERN = "^[A-Z]{2,4}-[0-9A-HJ-NP-Z]{8}$";
const FOLIO_EXAMPLE = "PROV-0000A3KF";

export const transactionIdPaths: OpenAPIV3.PathsObject = {
    "/transaction-ids": {
        post: {
            tags: ["TransactionIds"],
            summary: "Generate transaction ID",
            description:
                "Genera un folio visible único y un UUID interno para trazabilidad de acciones en el portal.",
            requestBody: {
                required: true,
                content: {
                    "application/json": {
                        schema: { $ref: "#/components/schemas/CreateTransactionIdDto" },
                        example: {
                            codigoModulo: "PROV",
                            pantallaOrigen: "ALTA_PROVEEDOR",
                            caso: "GUARDAR_PROVEEDOR",
                            metadatos: {
                                rfc: "ABC010203XYZ",
                                proveedorId: 1001,
                            },
                            idUsuario: "12345",
                            origen: "portal-proveedores",
                        },
                    },
                },
            },
            responses: {
                201: {
                    description: "Transaction ID generated successfully",
                    content: {
                        "application/json": {
                            schema: {
                                $ref: "#/components/schemas/TransactionIdApiResponse",
                            },
                            example: {
                                message: "Transaction ID generated successfully",
                                data: {
                                    folioVisible: FOLIO_EXAMPLE,
                                    uuidInterno: "550e8400-e29b-41d4-a716-446655440000",
                                    fechaHora: "2026-03-18T20:30:45.000Z",
                                    codigoModulo: "PROV",
                                    pantallaOrigen: "ALTA_PROVEEDOR",
                                    caso: "GUARDAR_PROVEEDOR",
                                    idUsuario: "12345",
                                    origen: "portal-proveedores",
                                    estatus: "GENERATED",
                                    metadatos: {
                                        rfc: "ABC010203XYZ",
                                        proveedorId: 1001,
                                    },
                                },
                                count: 0,
                                statusCode: 201,
                                success: true,
                                details: "",
                                trace_id: UUID_EXAMPLE,
                            },
                        },
                    },
                },
                400: {
                    description: "Invalid request or catalog validation error",
                },
                409: {
                    description: "Duplicate folio_visible or uuid_interno",
                },
                500: {
                    description: "Internal server error",
                },
            },
        },
    },

    "/transaction-ids/{folioVisible}": {
        get: {
            tags: ["TransactionIds"],
            summary: "Get transaction by visible folio",
            description:
                "Consulta el detalle completo de una transacción a partir del folio visible reportado por el usuario.",
            parameters: [
                {
                    in: "path",
                    name: "folioVisible",
                    required: true,
                    description: "Visible folio generated by the transaction ID service",
                    schema: {
                        type: "string",
                        pattern: FOLIO_PATTERN,
                        example: FOLIO_EXAMPLE,
                    },
                },
            ],
            responses: {
                200: {
                    description: "Transaction found",
                    content: {
                        "application/json": {
                            schema: {
                                $ref: "#/components/schemas/TransactionIdApiResponse",
                            },
                            example: {
                                message: "Transaction ID detail",
                                data: {
                                    folioVisible: FOLIO_EXAMPLE,
                                    uuidInterno: "550e8400-e29b-41d4-a716-446655440000",
                                    fechaHora: "2026-03-18T20:30:45.000Z",
                                    codigoModulo: "PROV",
                                    pantallaOrigen: "ALTA_PROVEEDOR",
                                    caso: "GUARDAR_PROVEEDOR",
                                    idUsuario: "12345",
                                    origen: "portal-proveedores",
                                    estatus: "GENERATED",
                                    metadatos: {
                                        rfc: "ABC010203XYZ",
                                        proveedorId: 1001,
                                    },
                                },
                                count: 0,
                                statusCode: 200,
                                success: true,
                                details: "",
                                trace_id: UUID_EXAMPLE,
                            },
                        },
                    },
                },
                404: {
                    description: "Transaction ID not found",
                },
            },
        },
    },
};