# jdbc.X
jdbc.bct.driverClassName=oracle.jdbc.driver.OracleDriver

#Produccion
#jdbc.bct.url=MDAwMDAwMDAwMDAwMDAwMN/Fam0wU4E3l0nGeIXHG5D3s2FJTULbqGjobsjANE4r3+9eTOOlSGx6/29vQSI/dxTvLmXNxe4XEyLg8Phdtuw=
#jdbc.bct.user=MDAwMDAwMDAwMDAwMDAwMNnYFaPtRB1bP8yndvNibnU=
#jdbc.bct.pass=MDAwMDAwMDAwMDAwMDAwMHJ+W5VYyv2Hwqe/XGblw/M=

#Desarrollo
jdbc.bct.url=MDAwMDAwMDAwMDAwMDAwMN/Fam0wU4E3l0nGeIXHG5BEQ4Onu4VWZ/gmM4PXOy38j9mobVd8nPrZHBdczq2g/A==
jdbc.bct.user=MDAwMDAwMDAwMDAwMDAwMNnYFaPtRB1bP8yndvNibnU=
jdbc.bct.pass=MDAwMDAwMDAwMDAwMDAwMF0rKbjpqooqnUU1KlU/OFk=

# hibernate.X
hibernate.bct.dialect=org.hibernate.dialect.Oracle10gDialect
hibernate.bct.show_sql=false
hibernate.bct.hbm2ddl.auto=none
hibernate.bct.cache.use_second_level_cache=false
hibernate.bct.cache.use_query_cache=false

# pool de conexiones
pool.bct.jmxEnabled=true
pool.bct.testWhileIdle=false
pool.bct.testOnBorrow=true
pool.bct.validationQuery=SELECT 1 from dual
pool.bct.testOnReturn=false
pool.bct.validationInterval=30000
pool.bct.timeBetweenEvictionRunsMillis=30000
pool.bct.maxActive=100
pool.bct.initialSize=10
pool.bct.maxWait=10000
pool.bct.removeAbandonedTimeout=300
pool.bct.minEvictableIdleTimeMillis=30000
pool.bct.minIdle=10
pool.bct.logAbandoned=true
pool.bct.removeAbandoned=true
