
package com.falabella.mdwcorp.sod.corp.osb.wsdl.cliente.factura.confirmar_v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.falabella.mdwcorp.sod.corp.osb.schema.cliente.factura.confirmar.req_v2018.ClienteFacturaConfirmarExpReqTYPE;
import com.falabella.mdwcorp.sod.corp.osb.schema.cliente.factura.confirmar.resp_v2018.ClienteFacturaConfirmarExpRespTYPE;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClienteFacturaConfirmarPt", targetNamespace = "http://mdwcorp.falabella.com/SOD/CORP/OSB/wsdl/Cliente/Factura/Confirmar-v1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.falabella.mdwcorp.common.schema.clientservice.ObjectFactory.class,
    com.falabella.mdwcorp.sod.corp.osb.schema.cliente.factura.confirmar.req_v2018.ObjectFactory.class,
    com.falabella.mdwcorp.sod.corp.osb.schema.cliente.factura.confirmar.resp_v2018.ObjectFactory.class,
    org.xmlsoap.schemas.soap.envelope.ObjectFactory.class
})
public interface ClienteFacturaConfirmarPt {


    /**
     * 
     * @param clienteFacturaConfirmarReqParam
     * @return
     *     returns com.falabella.mdwcorp.sod.corp.osb.schema.cliente.factura.confirmar.resp_v2018.ClienteFacturaConfirmarExpRespTYPE
     * @throws FaultMsg
     */
    @WebMethod(operationName = "ClienteFacturaConfirmarOp", action = "http://mdwcorp.falabella.com/SOD/CORP/OSB/wsdl/Cliente/Factura/Confirmar-v1.0/Op")
    @WebResult(name = "ClienteFacturaConfirmarExpResp", targetNamespace = "http://mdwcorp.falabella.com/SOD/CORP/OSB/schema/Cliente/Factura/Confirmar/Resp-v2018.02", partName = "ClienteFacturaConfirmarRespParam")
    public ClienteFacturaConfirmarExpRespTYPE clienteFacturaConfirmarOp(
        @WebParam(name = "ClienteFacturaConfirmarExpReq", targetNamespace = "http://mdwcorp.falabella.com/SOD/CORP/OSB/schema/Cliente/Factura/Confirmar/Req-v2018.02", partName = "ClienteFacturaConfirmarReqParam")
        ClienteFacturaConfirmarExpReqTYPE clienteFacturaConfirmarReqParam)
        throws FaultMsg
    ;

}
