import type { Parameter } from './types';

export const mockParameters: Parameter[] = [
  {
    id: 'PARAM-01',
    name: 'Egresos.Batch',
    description:
      'Egresos.Meses.ConsultaReproceso',
    module: 'EGRE',
    parameterType: 'Aplicación',
    value: '2',
    version: 1.0,
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'ACTIVE',
    createdBy: 'AGINES',
    createdAt: '2025-04-21',
    updatedBy: null,
    updatedAt: null,
  },
  {
    id: 'PARAM-01',
    name: 'Egresos.Batch',
    description:
      'Egresos.Meses.ConsultaReproceso',
    module: 'EGRE',
    parameterType: 'Aplicación',
    value: '2',
    version: 1.0,
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'ACTIVE',
    createdBy: 'AGINES',
    createdAt: '2025-04-21',
    updatedBy: null,
    updatedAt: null,
  },
  {
    id: 'PARAM-01',
    name: 'Egresos.Batch',
    description:
      'Egresos.Meses.ConsultaReproceso',
    module: 'EGRE',
    parameterType: 'Aplicación',
    value: '2',
    version: 1.0,
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'ACTIVE',
    createdBy: 'AGINES',
    createdAt: '2025-04-21',
    updatedBy: null,
    updatedAt: null,
  },
  {
    id: 'PARAM-01',
    name: 'Egresos.Batch',
    description:
      'Egresos.Meses.ConsultaReproceso',
    module: 'EGRE',
    parameterType: 'Aplicación',
    value: '2',
    version: 1.0,
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'ACTIVE',
    createdBy: 'AGINES',
    createdAt: '2025-04-21',
    updatedBy: null,
    updatedAt: null,
  },
  {
    id: 'PARAM-01',
    name: 'Egresos.Batch',
    description:
      'Egresos.Meses.ConsultaReproceso',
    module: 'EGRE',
    parameterType: 'Aplicación',
    value: '2',
    version: 1.0,
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'ACTIVE',
    createdBy: 'AGINES',
    createdAt: '2025-04-21',
    updatedBy: null,
    updatedAt: null,
  },
  {
    id: 'PARAM-01',
    name: 'Egresos.Batch',
    description:
      'Egresos.Meses.ConsultaReproceso',
    module: 'EGRE',
    parameterType: 'Aplicación',
    value: '2',
    version: 1.0,
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'ACTIVE',
    createdBy: 'AGINES',
    createdAt: '2025-04-21',
    updatedBy: null,
    updatedAt: null,
  },
  {
    id: 'PARAM-01',
    name: 'Egresos.Batch',
    description:
      'Egresos.Meses.ConsultaReproceso',
    module: 'EGRE',
    parameterType: 'Aplicación',
    value: '2',
    version: 1.0,
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'ACTIVE',
    createdBy: 'AGINES',
    createdAt: '2025-04-21',
    updatedBy: null,
    updatedAt: null,
  },
  {
    id: 'PARAM-01',
    name: 'Egresos.Batch',
    description:
      'Egresos.Meses.ConsultaReproceso',
    module: 'EGRE',
    parameterType: 'Aplicación',
    value: '2',
    version: 1.0,
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'ACTIVE',
    createdBy: 'AGINES',
    createdAt: '2025-04-21',
    updatedBy: null,
    updatedAt: null,
  },
  {
    id: 'PARAM-01',
    name: 'Egresos.Batch',
    description:
      'Egresos.Meses.ConsultaReproceso',
    module: 'EGRE',
    parameterType: 'Aplicación',
    value: '2',
    version: 1.0,
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'ACTIVE',
    createdBy: 'AGINES',
    createdAt: '2025-04-21',
    updatedBy: null,
    updatedAt: null,
  },
  {
    id: 'PARAM-01',
    name: 'Egresos.Batch',
    description:
      'Egresos.Meses.ConsultaReproceso',
    module: 'EGRE',
    parameterType: 'Aplicación',
    value: '2',
    version: 1.0,
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'ACTIVE',
    createdBy: 'AGINES',
    createdAt: '2025-04-21',
    updatedBy: null,
    updatedAt: null,
  },
  {
    id: 'PARAM-01',
    name: 'Egresos.Batch',
    description:
      'Egresos.Meses.ConsultaReproceso',
    module: 'EGRE',
    parameterType: 'Aplicación',
    value: '2',
    version: 1.0,
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'ACTIVE',
    createdBy: 'AGINES',
    createdAt: '2025-04-21',
    updatedBy: null,
    updatedAt: null,
  },
  {
    id: 'PARAM-01',
    name: 'Egresos.Batch',
    description:
      'Egresos.Meses.ConsultaReproceso',
    module: 'EGRE',
    parameterType: 'Aplicación',
    value: '2',
    version: 1.0,
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'ACTIVE',
    createdBy: 'AGINES',
    createdAt: '2025-04-21',
    updatedBy: null,
    updatedAt: null,
  },
  {
    id: 'PARAM-01',
    name: 'Egresos.Batch',
    description:
      'Egresos.Meses.ConsultaReproceso',
    module: 'EGRE',
    parameterType: 'Aplicación',
    value: '2',
    version: 1.0,
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'ACTIVE',
    createdBy: 'AGINES',
    createdAt: '2025-04-21',
    updatedBy: null,
    updatedAt: null,
  },
  {
    id: 'PARAM-01',
    name: 'Egresos.Batch',
    description:
      'Egresos.Meses.ConsultaReproceso',
    module: 'EGRE',
    parameterType: 'Aplicación',
    value: '2',
    version: 1.0,
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'ACTIVE',
    createdBy: 'AGINES',
    createdAt: '2025-04-21',
    updatedBy: null,
    updatedAt: null,
  },
  {
    id: 'PARAM-01',
    name: 'Egresos.Batch',
    description:
      'Egresos.Meses.ConsultaReproceso',
    module: 'EGRE',
    parameterType: 'Aplicación',
    value: '2',
    version: 1.0,
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'ACTIVE',
    createdBy: 'AGINES',
    createdAt: '2025-04-21',
    updatedBy: null,
    updatedAt: null,
  },
  {
    id: 'PARAM-01',
    name: 'Egresos.Batch',
    description:
      'Egresos.Meses.ConsultaReproceso',
    module: 'EGRE',
    parameterType: 'Aplicación',
    value: '2',
    version: 1.0,
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'ACTIVE',
    createdBy: 'AGINES',
    createdAt: '2025-04-21',
    updatedBy: null,
    updatedAt: null,
  },
  {
    id: 'PARAM-01',
    name: 'Egresos.Batch',
    description:
      'Egresos.Meses.ConsultaReproceso',
    module: 'EGRE',
    parameterType: 'Aplicación',
    value: '2',
    version: 1.0,
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'ACTIVE',
    createdBy: 'AGINES',
    createdAt: '2025-04-21',
    updatedBy: null,
    updatedAt: null,
  },
  {
    id: 'PARAM-01',
    name: 'Egresos.Batch',
    description:
      'Egresos.Meses.ConsultaReproceso',
    module: 'EGRE',
    parameterType: 'Aplicación',
    value: '2',
    version: 1.0,
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'ACTIVE',
    createdBy: 'AGINES',
    createdAt: '2025-04-21',
    updatedBy: null,
    updatedAt: null,
  },
];

export const moduleCatalog = [
  { value: 'EGRE', label: 'EGRE' },
  { value: 'FACT', label: 'FACT' },
  { value: 'CONF', label: 'CONF' },
];

export const parameterTypeCatalog = [
  { value: 'Aplicación', label: 'Aplicación' },
  { value: 'Batch', label: 'Batch' },
];

export const statusCatalog = [
  { value: 'ACTIVE', label: 'Activo' },
  { value: 'INACTIVE', label: 'Inactivo' },
];

