package com.falabella.mdwcorp.sod.corp.osb.wsdl.cliente.factura.confirmar_v1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.7
 * 2024-03-29T08:47:34.074-06:00
 * Generated source version: 3.4.7
 *
 */
@WebService(targetNamespace = "http://mdwcorp.falabella.com/SOD/CORP/OSB/wsdl/Cliente/Factura/Confirmar-v1.0", name = "ClienteFacturaConfirmarPt")
@XmlSeeAlso({com.falabella.mdwcorp.sod.corp.osb.schema.cliente.factura.confirmar.resp_v2018.ObjectFactory.class, com.falabella.mdwcorp.common.schema.clientservice.ObjectFactory.class, com.falabella.mdwcorp.sod.corp.osb.schema.cliente.factura.confirmar.req_v2018.ObjectFactory.class, org.xmlsoap.schemas.soap.envelope.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ClienteFacturaConfirmarPt {

    @WebMethod(operationName = "ClienteFacturaConfirmarOp", action = "http://mdwcorp.falabella.com/SOD/CORP/OSB/wsdl/Cliente/Factura/Confirmar-v1.0/Op")
    @WebResult(name = "ClienteFacturaConfirmarExpResp", targetNamespace = "http://mdwcorp.falabella.com/SOD/CORP/OSB/schema/Cliente/Factura/Confirmar/Resp-v2018.02", partName = "ClienteFacturaConfirmarRespParam")
    public com.falabella.mdwcorp.sod.corp.osb.schema.cliente.factura.confirmar.resp_v2018.ClienteFacturaConfirmarExpRespTYPE clienteFacturaConfirmarOp(

        @WebParam(partName = "ClienteFacturaConfirmarReqParam", name = "ClienteFacturaConfirmarExpReq", targetNamespace = "http://mdwcorp.falabella.com/SOD/CORP/OSB/schema/Cliente/Factura/Confirmar/Req-v2018.02")
        com.falabella.mdwcorp.sod.corp.osb.schema.cliente.factura.confirmar.req_v2018.ClienteFacturaConfirmarExpReqTYPE clienteFacturaConfirmarReqParam
    ) throws FaultMsg;
}
