
package com.falabella.mdwcorp.sod.corp.osb.wsdl.cliente.factura.confirmar_v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.7
 * 2024-03-29T08:47:34.050-06:00
 * Generated source version: 3.4.7
 */

@WebFault(name = "Fault", targetNamespace = "http://schemas.xmlsoap.org/soap/envelope/")
public class FaultMsg extends Exception {

    private org.xmlsoap.schemas.soap.envelope.Fault faultInfo;

    public FaultMsg() {
        super();
    }

    public FaultMsg(String message) {
        super(message);
    }

    public FaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public FaultMsg(String message, org.xmlsoap.schemas.soap.envelope.Fault fault) {
        super(message);
        this.faultInfo = fault;
    }

    public FaultMsg(String message, org.xmlsoap.schemas.soap.envelope.Fault fault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = fault;
    }

    public org.xmlsoap.schemas.soap.envelope.Fault getFaultInfo() {
        return this.faultInfo;
    }
}
