apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PROJECT_NAME}
spec:
  template:
    spec:
      serviceAccountName: ${WORLOAD_IDENTITY_DEV}
      containers:
        - name: ${PROJECT_NAME}

