export const CatEstatusFactura = [
    {
      "key": "EFA001",
      "internalStatus": 0,
      "externalKey": null,
      "value": null,
      "description": "Rechazo Comercial",
      "color": "Rojo",
      "sortOrder": 1,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "EFA002",
      "internalStatus": 1,
      "externalKey": null,
      "value": null,
      "description": "Pendiente Addenda",
      "color": "Amarillo",
      "sortOrder": 2,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "EFA003",
      "internalStatus": 2,
      "externalKey": null,
      "value": null,
      "description": "Recibido Parcial",
      "color": "Amarillo",
      "sortOrder": 3,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "EFA004",
      "internalStatus": 3,
      "externalKey": null,
      "value": null,
      "description": "Pendiente de Contabilizar",
      "color": "Amarillo",
      "sortOrder": 4,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "EFA005",
      "internalStatus": 4,
      "externalKey": null,
      "value": null,
      "description": "En proceso de descarga",
      "color": "Amarillo",
      "sortOrder": 5,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "EFA006",
      "internalStatus": 5,
      "externalKey": null,
      "value": null,
      "description": "Desglose de factura",
      "color": "Amarillo",
      "sortOrder": 6,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "EFA007",
      "internalStatus": 6,
      "externalKey": null,
      "value": null,
      "description": "Pendiente de envío a contabilizar",
      "color": "Amarillo",
      "sortOrder": 7,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "EFA008",
      "internalStatus": 7,
      "externalKey": null,
      "value": null,
      "description": "Pendiente de Pago",
      "color": "Amarillo",
      "sortOrder": 8,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "EFA009",
      "internalStatus": 8,
      "externalKey": null,
      "value": null,
      "description": "Pagado",
      "color": "Verde",
      "sortOrder": 9,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "EFA010",
      "internalStatus": 9,
      "externalKey": null,
      "value": null,
      "description": "Pendiente de complemento",
      "color": "Amarillo",
      "sortOrder": 10,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "EFA011",
      "internalStatus": 10,
      "externalKey": null,
      "value": null,
      "description": "Completado",
      "color": "Verde",
      "sortOrder": 11,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "EFA012",
      "internalStatus": 11,
      "externalKey": null,
      "value": null,
      "description": "Rechazo Contable",
      "color": "Rojo",
      "sortOrder": 12,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "EFA013",
      "internalStatus": 12,
      "externalKey": null,
      "value": null,
      "description": "No válido fiscal",
      "color": "Rojo",
      "sortOrder": 13,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "EFA014",
      "internalStatus": 13,
      "externalKey": null,
      "value": null,
      "description": "Pago Manual",
      "color": "Verde",
      "sortOrder": 14,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    }
  ];
 export const CatEstatusPago = [
     {
      "key": "EPA001",
      "internalStatus": 2,
      "externalKey": null,
      "value": null,
      "description": "Pendiente de complemento",
      "color": "Amarillo",
      "sortOrder": 1,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "EPA002",
      "internalStatus": 1,
      "externalKey": null,
      "value": null,
      "description": "Complemento relacionado",
      "color": "Verde",
      "sortOrder": 2,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "EPA003",
      "internalStatus": 3,
      "externalKey": null,
      "value": null,
      "description": "Pago cancelado",
      "color": "Rojo",
      "sortOrder": 3,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "EPA004",
      "internalStatus": 4,
      "externalKey": null,
      "value": null,
      "description": "Pago borrado lógico",
      "color": "Rojo",
      "sortOrder": 4,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    }
]

export const CatEstatusNotaCredito = [
    {
      "key": "ENC001",
      "internalStatus": 3,
      "externalKey": null,
      "value": null,
      "description": "Nota de crédito pendiente de contabilizar",
      "color": "Amarillo",
      "sortOrder": 1,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ENC002",
      "internalStatus": 7,
      "externalKey": null,
      "value": null,
      "description": "Nota de crédito relacionada",
      "color": "Verde",
      "sortOrder": 7,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ENC003",
      "internalStatus": 10,
      "externalKey": null,
      "value": null,
      "description": "Nota de crédito cancelada",
      "color": "Rojo",
      "sortOrder": 3,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ENC004",
      "internalStatus": 0,
      "externalKey": null,
      "value": null,
      "description": "Nota de crédito borrada",
      "color": "Rojo",
      "sortOrder": 4,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    }
  ]

export const catMsgAdverrtencia =  [
    {
      "key": "WRN301",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "No existe la Orden de compra {0} para el proveedor {1}.",
      "color": null,
      "sortOrder": 1,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN001",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "La fecha inicio no puede ser superior a la fecha final.",
      "color": null,
      "sortOrder": 1,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN302",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "la Orden de compra {0} para el proveedor {1} no tiene recepciones asignadas.",
      "color": null,
      "sortOrder": 1,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN002",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Se requiere capturar por lo menos un filtro de búsqueda.",
      "color": null,
      "sortOrder": 2,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN003",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "No existe información con los filtros de búsqueda capturados.",
      "color": null,
      "sortOrder": 3,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN004",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "No es posible publicar el complemento de pago, faltan documentos fiscales por publicar.",
      "color": null,
      "sortOrder": 4,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN005",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Se requiere publicar el complemento de pago en formato XML.",
      "color": null,
      "sortOrder": 5,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN006",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El periodo de búsqueda no puede ser superior a 6 meses, favor de validar.",
      "color": null,
      "sortOrder": 6,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN007",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "La fecha final no puede ser menor a la fecha inicio.",
      "color": null,
      "sortOrder": 7,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN008",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Se requiere publicar factura en formato XML.",
      "color": null,
      "sortOrder": 8,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN009",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El total calculado no coincide con el total declarado",
      "color": null,
      "sortOrder": 9,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN010",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Tipo de cambio no especificado, usando valor por defecto",
      "color": null,
      "sortOrder": 10,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN011",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Moneda no especificada, usando MXN por defecto",
      "color": null,
      "sortOrder": 11,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN012",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El pago es parcial, saldo pendiente",
      "color": null,
      "sortOrder": 12,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN013",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Número de operación no especificado",
      "color": null,
      "sortOrder": 13,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN014",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Información bancaria incompleta",
      "color": null,
      "sortOrder": 14,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN015",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Documento relacionado con saldo cero",
      "color": null,
      "sortOrder": 15,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN016",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El monto pagado excede el saldo del documento",
      "color": null,
      "sortOrder": 16,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN017",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Datos opcionales de CartaPorte no especificados",
      "color": null,
      "sortOrder": 17,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN018",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Figuras de transporte no especificadas",
      "color": null,
      "sortOrder": 18,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN019",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Addenda sin contenido",
      "color": null,
      "sortOrder": 19,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN020",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Campos opcionales de addenda vacíos",
      "color": null,
      "sortOrder": 20,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN021",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Emisor no existía, se creó nuevo registro",
      "color": null,
      "sortOrder": 21,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN022",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Receptor no existía, se creó nuevo registro",
      "color": null,
      "sortOrder": 22,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN023",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Archivo con nombre similar ya fue procesado",
      "color": null,
      "sortOrder": 23,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN024",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Validación SAT tardó más de lo esperado",
      "color": null,
      "sortOrder": 24,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN025",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Respuesta SAT incompleta pero válida",
      "color": null,
      "sortOrder": 25,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN026",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Versión del documento será obsoleta próximamente",
      "color": null,
      "sortOrder": 26,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN027",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Datos opcionales no especificados",
      "color": null,
      "sortOrder": 27,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN028",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Documento registrado sin número de recepción. Requiere vinculación manual",
      "color": null,
      "sortOrder": 28,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN029",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "La recepción no se encuentra disponible en el sistema",
      "color": null,
      "sortOrder": 29,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN030",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "La recepción ya se encuentra vinculada a otro documento fiscal",
      "color": null,
      "sortOrder": 30,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN100",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El parametro {0} expira en {1} dias",
      "color": null,
      "sortOrder": 100,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN101",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "La version {0} del parametro {1} esta obsoleta",
      "color": null,
      "sortOrder": 101,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN102",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Se excedio el limite de {0} registros. Mostrando primeros resultados",
      "color": null,
      "sortOrder": 102,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN103",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El estatus de la recepción no permite realizar esta actualización. Por favor, valide la información antes de continuar.",
      "color": null,
      "sortOrder": 102,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN200",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El proveedor {0} no tiene tipo de proveedor asignado",
      "color": null,
      "sortOrder": 200,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN201",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El proveedor {0} no tiene condicion de pago asignada",
      "color": null,
      "sortOrder": 201,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "INF6000",
      "internalStatus": 6000,
      "externalKey": null,
      "value": null,
      "description": "No existe información con los criterios establecidos",
      "color": "#17a2b8",
      "sortOrder": 6000,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN7012",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "La factura requiere una serie y folio para publicar el documento. Por favor, valide la información antes de continuar.",
      "color": null,
      "sortOrder": 7012,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN7013",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "La factura se encuentra previamente registrada con la misma serie y folio. Por favor, valide la información antes de continuar.",
      "color": null,
      "sortOrder": 7013,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN7014",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "La factura se encuentra previamente registrada con el mismo UUID. Por favor, valide la información antes de continuar.",
      "color": null,
      "sortOrder": 7014,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN7015",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "La nota de crédito requiere una serie y folio para publicar el documento. Por favor, valide la información antes de continuar.",
      "color": null,
      "sortOrder": 7015,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN7016",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "La nota de crédito se encuentra previamente registrada con la misma serie y folio. Por favor, valide la información antes de continuar.",
      "color": null,
      "sortOrder": 7016,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "WRN7017",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "La nota de crédito se encuentra previamente registrada con el mismo UUID. Por favor, valide la información antes de continuar.",
      "color": null,
      "sortOrder": 7017,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    }
  ]

export const catMsgNegocio = [
    {
      "key": "BUS001",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "La addenda de la factura no cumple con la estructura requerida. Por favor, verifica el formato y el nombre de los elementos.",
      "color": null,
      "sortOrder": 1,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS002",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El RFC del receptor {0} no acepta documentos fiscales. Verifica que el RFC esté autorizado para recibir comprobantes fiscales.",
      "color": null,
      "sortOrder": 2,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS003",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "La guía carta porte no contiene un archivo xml y csv asociado, favor de validar.",
      "color": null,
      "sortOrder": 3,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS004",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "No fue posible registrar la guía carta porte, falta información por completar.",
      "color": null,
      "sortOrder": 4,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS005",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "La guía de embarque se encuentra previamente registrada, favor de validar.",
      "color": null,
      "sortOrder": 5,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS006",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Las facturas no corresponden al complemento que desea publicar.",
      "color": null,
      "sortOrder": 6,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS007",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Las notas de crédito no corresponden al complemento que desea publicar.",
      "color": null,
      "sortOrder": 7,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS008",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El RFC del receptor no acepta documentos fiscales. Verifica que el RFC esté autorizado para recibir comprobantes fiscales.",
      "color": null,
      "sortOrder": 8,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS009",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El RFC del receptor no está activo en el período de vigencia especificado",
      "color": null,
      "sortOrder": 9,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS010",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El RFC del receptor no se encuentra registrado en el sistema",
      "color": null,
      "sortOrder": 10,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS011",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "La addenda debe contener el nodo Addenda_Sodimac para documentos de mercancía, servicios y transporte local",
      "color": null,
      "sortOrder": 11,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS012",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "La addenda debe contener el nodo Addenda_Sodimac_CartaPorte para transporte foráneo",
      "color": null,
      "sortOrder": 12,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS013",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El campo RFC en la addenda es obligatorio",
      "color": null,
      "sortOrder": 13,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS014",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El campo UUID en la addenda es obligatorio",
      "color": null,
      "sortOrder": 14,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS015",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El campo Folio en la addenda es obligatorio",
      "color": null,
      "sortOrder": 15,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS016",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El campo NoOC (Número de Orden de Compra) en la addenda es obligatorio",
      "color": null,
      "sortOrder": 16,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS017",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El campo Proveedor en la addenda es obligatorio",
      "color": null,
      "sortOrder": 17,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS018",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El formato del RFC en la addenda no es válido",
      "color": null,
      "sortOrder": 18,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS019",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El UUID en la addenda no coincide con el UUID del TimbreFiscalDigital",
      "color": null,
      "sortOrder": 19,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS020",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "La versión del documento no se encuentra configurada en el sistema",
      "color": null,
      "sortOrder": 20,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS021",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "La versión del documento no está vigente",
      "color": null,
      "sortOrder": 21,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS022",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El documento debe ser versión CFDI 4.0",
      "color": null,
      "sortOrder": 22,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS023",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El tipo de documento debe ser I (Factura) o E (Nota de Crédito)",
      "color": null,
      "sortOrder": 23,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS024",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El tipo de comprobante no está permitido para este proceso",
      "color": null,
      "sortOrder": 24,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS025",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Las Notas de Crédito deben incluir CFDIs relacionados con tipo de relación 01",
      "color": null,
      "sortOrder": 25,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS026",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El documento fiscal no se encuentra vigente en el SAT",
      "color": null,
      "sortOrder": 26,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS027",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El documento fiscal se encuentra cancelado en el SAT",
      "color": null,
      "sortOrder": 27,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS028",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El UUID no se encuentra registrado en el SAT",
      "color": null,
      "sortOrder": 28,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS029",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El sello digital del documento no es válido según el SAT",
      "color": null,
      "sortOrder": 29,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS030",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "No fue posible validar el estatus del documento en el SAT",
      "color": null,
      "sortOrder": 30,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS031",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El RFC del emisor no se encuentra registrado como proveedor autorizado",
      "color": null,
      "sortOrder": 31,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS032",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El emisor se encuentra inactivo en el sistema",
      "color": null,
      "sortOrder": 32,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS033",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El RFC del emisor no es válido",
      "color": null,
      "sortOrder": 33,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS034",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El documento con UUID ya se encuentra registrado en el sistema",
      "color": null,
      "sortOrder": 34,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS035",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El documento con Serie y Folio ya se encuentra registrado",
      "color": null,
      "sortOrder": 35,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS036",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El archivo ya fue procesado anteriormente",
      "color": null,
      "sortOrder": 36,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS037",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El documento debe contener al menos un concepto",
      "color": null,
      "sortOrder": 37,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS038",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El total del documento no puede ser cero",
      "color": null,
      "sortOrder": 38,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS039",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Los montos de los conceptos no coinciden con el total del documento",
      "color": null,
      "sortOrder": 39,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS040",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Los impuestos calculados no coinciden con los declarados",
      "color": null,
      "sortOrder": 40,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS041",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El documento contiene impuestos no permitidos por Sodimac",
      "color": null,
      "sortOrder": 41,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS042",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "La Nota de Crédito debe incluir al menos un CFDI relacionado en el nodo CfdiRelacionados",
      "color": null,
      "sortOrder": 42,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS043",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "La Factura relacionada no se encuentra registrada en el sistema. Debe registrar primero la Factura antes de cargar la Nota de Crédito",
      "color": null,
      "sortOrder": 43,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS044",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El CFDI relacionado no es una Factura (tipo I). Solo se pueden relacionar NC con Facturas",
      "color": null,
      "sortOrder": 44,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS045",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El tipo de relación no es válido. Para Notas de Crédito debe ser 01",
      "color": null,
      "sortOrder": 45,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS046",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El documento con UUID no se encuentra registrado en el sistema",
      "color": null,
      "sortOrder": 46,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS047",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El documento con UUID no pertenece al proveedor especificado",
      "color": null,
      "sortOrder": 47,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS048",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "La addenda del documento no se encuentra registrada en el sistema",
      "color": null,
      "sortOrder": 48,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS049",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El estatus no es válido para el tipo de documento",
      "color": null,
      "sortOrder": 49,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS050",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El estatus no existe en el catálogo de estatus",
      "color": null,
      "sortOrder": 50,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS051",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "La transición de estatus no está permitida",
      "color": null,
      "sortOrder": 51,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS052",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "No se puede actualizar un documento en estatus final alcanzado",
      "color": null,
      "sortOrder": 52,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS053",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El estatus del documento ya es el indicado. No se requiere actualización",
      "color": null,
      "sortOrder": 53,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS054",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El usuario no tiene permisos para actualizar documentos fiscales",
      "color": null,
      "sortOrder": 54,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS055",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Solo el proveedor propietario puede actualizar este documento",
      "color": null,
      "sortOrder": 55,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS056",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El documento está en proceso automático y no puede ser modificado manualmente",
      "color": null,
      "sortOrder": 56,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS100",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Ya existe un parametro con el nombre {0} y version {1}",
      "color": null,
      "sortOrder": 100,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS101",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El modulo con ID {0} no existe",
      "color": null,
      "sortOrder": 101,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS102",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El parametro con ID {0} no existe",
      "color": null,
      "sortOrder": 102,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS103",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Ya existe un mensaje con el codigo {0}",
      "color": null,
      "sortOrder": 103,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS104",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El mensaje con codigo {0} no existe",
      "color": null,
      "sortOrder": 104,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS105",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El proceso con ID {0} no existe",
      "color": null,
      "sortOrder": 105,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS106",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El tipo de elemento con ID {0} no existe",
      "color": null,
      "sortOrder": 106,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS107",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El elemento con ID {0} no existe",
      "color": null,
      "sortOrder": 107,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS108",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El parametro {0} se encuentra inactivo",
      "color": null,
      "sortOrder": 108,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS109",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El valor del parametro {0} no es valido: {1}",
      "color": null,
      "sortOrder": 109,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS110",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "La relacion mensaje {0} - aplicativo {1} ya existe",
      "color": null,
      "sortOrder": 110,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS111",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El modulo {0} no puede eliminarse porque tiene parametros asociados",
      "color": null,
      "sortOrder": 111,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS200",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Ya existe un proveedor con el numero: {0}",
      "color": null,
      "sortOrder": 200,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS204",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El tipo de proveedor con ID {0} no existe",
      "color": null,
      "sortOrder": 204,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS205",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "La condicion de pago con ID {0} no existe",
      "color": null,
      "sortOrder": 205,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS206",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Guia de embarque no encontrada",
      "color": null,
      "sortOrder": 206,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS207",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "No se pudieron registrar los documentos en google storage",
      "color": null,
      "sortOrder": 207,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS208",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El registro de la guía de embarque se realizó exitosamente",
      "color": null,
      "sortOrder": 208,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS209",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Guia de embarque no actualizada",
      "color": null,
      "sortOrder": 209,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS210",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Guia de embarque actualizada exitosamente",
      "color": null,
      "sortOrder": 210,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS211",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Orden de Compra y Guias Registradas en el sistema de FBC exitosamente",
      "color": null,
      "sortOrder": 211,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS212",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Orden de Compra creada en el sistema de FBC exitosamente",
      "color": null,
      "sortOrder": 212,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "BUS214",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "No existe el tipo de proveedor [{0}] solicitado.",
      "color": null,
      "sortOrder": 214,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    }
  ]

export const catMsgErrorSistema =  [
    {
      "key": "ERR001",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El archivo está vacío",
      "color": null,
      "sortOrder": 1,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR002",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El archivo debe tener extensión .xml",
      "color": null,
      "sortOrder": 2,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR003",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Error procesando archivo XML fiscal",
      "color": null,
      "sortOrder": 3,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR004",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El XML no tiene una estructura válida",
      "color": null,
      "sortOrder": 4,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR005",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Error leyendo archivo XML",
      "color": null,
      "sortOrder": 5,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR006",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El XML no cumple con la estructura XSD",
      "color": null,
      "sortOrder": 6,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR007",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El XML no cumple con la estructura XSD Pagos 2.0",
      "color": null,
      "sortOrder": 7,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR008",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Error configurando procesador CartaPorte",
      "color": null,
      "sortOrder": 8,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR009",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Error configurando procesador CFDI",
      "color": null,
      "sortOrder": 9,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR010",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Error configurando procesador Pagos",
      "color": null,
      "sortOrder": 10,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR011",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Error procesando CartaPorte",
      "color": null,
      "sortOrder": 11,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR012",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Error procesando CFDI",
      "color": null,
      "sortOrder": 12,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR013",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Error procesando Pagos",
      "color": null,
      "sortOrder": 13,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR014",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Error detectando tipo de documento XML",
      "color": null,
      "sortOrder": 14,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR015",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Tipo de documento fiscal no válido",
      "color": null,
      "sortOrder": 15,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR016",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Tipo de CFDI no soportado en este procesador",
      "color": null,
      "sortOrder": 16,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR017",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Se esperaba Factura (I) pero se encontró tipo diferente",
      "color": null,
      "sortOrder": 17,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR018",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Se esperaba Nota de Crédito (E) pero se encontró tipo diferente",
      "color": null,
      "sortOrder": 18,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR019",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Tipo de comprobante no válido",
      "color": null,
      "sortOrder": 19,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR020",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El tipo de comprobante debe ser P (Pago)",
      "color": null,
      "sortOrder": 20,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR021",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Datos de Pagos no pueden ser nulos",
      "color": null,
      "sortOrder": 21,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR022",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Complemento de Pago debe incluir nodo Totales",
      "color": null,
      "sortOrder": 22,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR023",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Nodo Totales debe especificar el monto total de pagos",
      "color": null,
      "sortOrder": 23,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR024",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Complemento de Pago debe contener al menos un elemento Pago",
      "color": null,
      "sortOrder": 24,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR025",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Complemento de Pago debe especificar la versión",
      "color": null,
      "sortOrder": 25,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR026",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El complemento de pago ya se encuentra registrado en el sistema",
      "color": null,
      "sortOrder": 26,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR027",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Error convirtiendo XML a Document",
      "color": null,
      "sortOrder": 27,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR028",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El tipo de addenda debe ser 5 para complementos de pago",
      "color": null,
      "sortOrder": 28,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR029",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El RFC receptor no está autorizado en el sistema",
      "color": null,
      "sortOrder": 29,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR030",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "La versión del complemento de pago no es vigente en el sistema",
      "color": null,
      "sortOrder": 30,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR031",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El documento relacionado no se encuentra registrado en el sistema",
      "color": null,
      "sortOrder": 31,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR032",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "PAC no disponible para el nivel de prioridad solicitado",
      "color": null,
      "sortOrder": 32,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR033",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Error generando PDF desde XML",
      "color": null,
      "sortOrder": 33,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR034",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Error generando PDF del Complemento de Pago",
      "color": null,
      "sortOrder": 34,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR035",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Error de validación en los campos del request",
      "color": null,
      "sortOrder": 35,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR036",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Error inesperado del sistema. Contacte al administrador",
      "color": null,
      "sortOrder": 36,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR100",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Error de conexion con la base de datos",
      "color": null,
      "sortOrder": 100,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR101",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Error al procesar el parametro {0}",
      "color": null,
      "sortOrder": 101,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR102",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Error de validacion en los datos de entrada",
      "color": null,
      "sortOrder": 102,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR103",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El recurso solicitado no fue encontrado",
      "color": null,
      "sortOrder": 103,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR104",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Error interno del servidor. Contacte al administrador",
      "color": null,
      "sortOrder": 104,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR105",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Tiempo de espera agotado para la operacion",
      "color": null,
      "sortOrder": 105,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR106",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Error al serializar/deserializar datos",
      "color": null,
      "sortOrder": 106,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "ERR107",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Error en la configuracion del sistema",
      "color": null,
      "sortOrder": 107,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    }
  ]

export const CatMsgExitoso = [
    {
      "key": "RES001",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El registro del proveedor {0} se realizó exitosamente.",
      "color": null,
      "sortOrder": 1,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "RES002",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El reporte se ha descargado exitosamente.",
      "color": null,
      "sortOrder": 2,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "RES003",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "El registro de la guía de embarque se realizó exitosamente.",
      "color": null,
      "sortOrder": 3,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "RES004",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Factura registrada exitosamente",
      "color": null,
      "sortOrder": 4,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "RES005",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Factura registrada exitosamente - Pendiente de Addenda",
      "color": null,
      "sortOrder": 5,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "RES006",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Nota de Crédito registrada exitosamente",
      "color": null,
      "sortOrder": 6,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "RES007",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Nota de Crédito registrada exitosamente - Pendiente de Addenda",
      "color": null,
      "sortOrder": 7,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "RES008",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Complemento de Pago registrado exitosamente",
      "color": null,
      "sortOrder": 8,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "RES009",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Factura actualizada exitosamente",
      "color": null,
      "sortOrder": 9,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "RES010",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Factura actualizada exitosamente - Addenda actualizada",
      "color": null,
      "sortOrder": 10,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "RES011",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Nota de Crédito actualizada exitosamente",
      "color": null,
      "sortOrder": 11,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "RES012",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Nota de Crédito actualizada exitosamente - Addenda actualizada",
      "color": null,
      "sortOrder": 12,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "RES100",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Parametro {0} creado exitosamente",
      "color": null,
      "sortOrder": 100,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "RES101",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Parametro {0} actualizado exitosamente",
      "color": null,
      "sortOrder": 101,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "RES102",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Parametro eliminado exitosamente",
      "color": null,
      "sortOrder": 102,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "RES103",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Modulo {0} creado exitosamente",
      "color": null,
      "sortOrder": 103,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "RES104",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Configuracion guardada exitosamente",
      "color": null,
      "sortOrder": 104,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "RES200",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Proveedor {0} creado exitosamente",
      "color": null,
      "sortOrder": 200,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "RES201",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Proveedor {0} actualizado exitosamente",
      "color": null,
      "sortOrder": 201,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "RES202",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Proveedor {0} eliminado exitosamente",
      "color": null,
      "sortOrder": 202,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "RES203",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Proveedor {0} activado exitosamente",
      "color": null,
      "sortOrder": 203,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "RES204",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Proveedor {0} desactivado exitosamente",
      "color": null,
      "sortOrder": 204,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "RES205",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Recepción actualizada correctamente",
      "color": null,
      "sortOrder": 205,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    }
  ]

export const CatMsgInformativo = [
    {
      "key": "INF001",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "No existe información con los criterios establecidos.",
      "color": null,
      "sortOrder": 1,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "INF100",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "No se encontraron resultados para la busqueda",
      "color": null,
      "sortOrder": 100,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "INF101",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "La operacion se esta procesando",
      "color": null,
      "sortOrder": 101,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "INF102",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Cache de parametros actualizado",
      "color": null,
      "sortOrder": 102,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "INF200",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "No se encontraron proveedores",
      "color": null,
      "sortOrder": 200,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    },
    {
      "key": "INF201",
      "internalStatus": null,
      "externalKey": null,
      "value": null,
      "description": "Se encontraron {0} proveedores",
      "color": null,
      "sortOrder": 201,
      "validFrom": null,
      "validTo": null,
      "attributes": null
    }
  ]

export const Suppliers = [
  {
    "id": 1,
    "supplierNumber": "1",
    "rfc": "ABC123456789",
    "businessName": "Proveedor ABC S.A. de C.V.",
    "supplierType": {
      "id": 1,
      "code": "MERCANCIA",
      "description": "Proveedores de mercancia ODBMS"
    },
    "logo": null,
    "paymentCondition": {
      "id": 3,
      "conditionName": "30 dias",
      "days": 30
    },
    "status": 1
  },
  {
    "id": 2,
    "supplierNumber": "2",
    "rfc": "XYZ987654321",
    "businessName": "Distribuidora XYZ S.A.",
    "supplierType": {
      "id": 1,
      "code": "MERCANCIA",
      "description": "Proveedores de mercancia ODBMS"
    },
    "logo": null,
    "paymentCondition": {
      "id": 4,
      "conditionName": "45 dias",
      "days": 45
    },
    "status": 1
  },
  {
    "id": 3,
    "supplierNumber": "3",
    "rfc": "INT555444333",
    "businessName": "International Supplies Inc.",
    "supplierType": {
      "id": 1,
      "code": "MERCANCIA",
      "description": "Proveedores de mercancia ODBMS"
    },
    "logo": null,
    "paymentCondition": {
      "id": 5,
      "conditionName": "60 dias",
      "days": 60
    },
    "status": 1
  },
  {
    "id": 7,
    "supplierNumber": "MERC001",
    "rfc": "MER010101ABC",
    "businessName": "Distribuidora de Materiales del Norte S.A.",
    "supplierType": {
      "id": 1,
      "code": "MERCANCIA",
      "description": "Proveedores de mercancia ODBMS"
    },
    "logo": null,
    "paymentCondition": {
      "id": 3,
      "conditionName": "30 dias",
      "days": 30
    },
    "status": 1
  },
  {
    "id": 8,
    "supplierNumber": "MERC002",
    "rfc": "MER020202DEF",
    "businessName": "Comercializadora Industrial Maya S.A. de C.V.",
    "supplierType": {
      "id": 1,
      "code": "MERCANCIA",
      "description": "Proveedores de mercancia ODBMS"
    },
    "logo": null,
    "paymentCondition": {
      "id": 4,
      "conditionName": "45 dias",
      "days": 45
    },
    "status": 1
  },
  {
    "id": 9,
    "supplierNumber": "MERC003",
    "rfc": "MER030303GHI",
    "businessName": "Productos Ferreteros del Centro",
    "supplierType": {
      "id": 1,
      "code": "MERCANCIA",
      "description": "Proveedores de mercancia ODBMS"
    },
    "logo": null,
    "paymentCondition": {
      "id": 5,
      "conditionName": "60 dias",
      "days": 60
    },
    "status": 1
  },
  {
    "id": 10,
    "supplierNumber": "MERC004",
    "rfc": "MER040404JKL",
    "businessName": "Aceros y Metales Monterrey",
    "supplierType": {
      "id": 1,
      "code": "MERCANCIA",
      "description": "Proveedores de mercancia ODBMS"
    },
    "logo": null,
    "paymentCondition": {
      "id": 3,
      "conditionName": "30 dias",
      "days": 30
    },
    "status": 1
  },
  {
    "id": 11,
    "supplierNumber": "MERC005",
    "rfc": "MER050505MNO",
    "businessName": "Pinturas y Recubrimientos Pacific",
    "supplierType": {
      "id": 1,
      "code": "MERCANCIA",
      "description": "Proveedores de mercancia ODBMS"
    },
    "logo": null,
    "paymentCondition": {
      "id": 6,
      "conditionName": "90 dias",
      "days": 90
    },
    "status": 1
  },
  {
    "id": 12,
    "supplierNumber": "TRANS001",
    "rfc": "TRA010101PQR",
    "businessName": "Transportes Especializados del Bajio S.A.",
    "supplierType": {
      "id": 2,
      "code": "TRANSPORTE",
      "description": "Proveedores de transporte Carta Porte"
    },
    "logo": null,
    "paymentCondition": {
      "id": 2,
      "conditionName": "15 dias",
      "days": 15
    },
    "status": 1
  },
  {
    "id": 13,
    "supplierNumber": "TRANS002",
    "rfc": "TRA020202STU",
    "businessName": "Fletes y Mudanzas Express",
    "supplierType": {
      "id": 2,
      "code": "TRANSPORTE",
      "description": "Proveedores de transporte Carta Porte"
    },
    "logo": null,
    "paymentCondition": {
      "id": 3,
      "conditionName": "30 dias",
      "days": 30
    },
    "status": 1
  },
  {
    "id": 14,
    "supplierNumber": "TRANS003",
    "rfc": "TRA030303VWX",
    "businessName": "Logistica Integral Mexicana",
    "supplierType": {
      "id": 2,
      "code": "TRANSPORTE",
      "description": "Proveedores de transporte Carta Porte"
    },
    "logo": null,
    "paymentCondition": {
      "id": 4,
      "conditionName": "45 dias",
      "days": 45
    },
    "status": 1
  },
  {
    "id": 15,
    "supplierNumber": "IND001",
    "rfc": "IND010101YZA",
    "businessName": "Suministros de Oficina Global",
    "supplierType": {
      "id": 3,
      "code": "INDIRECTOS",
      "description": "Proveedores de insumos SAP"
    },
    "logo": null,
    "paymentCondition": {
      "id": 2,
      "conditionName": "15 dias",
      "days": 15
    },
    "status": 1
  },
  {
    "id": 16,
    "supplierNumber": "IND002",
    "rfc": "IND020202BCD",
    "businessName": "Papeleria y Consumibles del Valle",
    "supplierType": {
      "id": 3,
      "code": "INDIRECTOS",
      "description": "Proveedores de insumos SAP"
    },
    "logo": null,
    "paymentCondition": {
      "id": 3,
      "conditionName": "30 dias",
      "days": 30
    },
    "status": 1
  },
  {
    "id": 17,
    "supplierNumber": "IND003",
    "rfc": "IND030303EFG",
    "businessName": "Equipos de Computo Tecnomex",
    "supplierType": {
      "id": 3,
      "code": "INDIRECTOS",
      "description": "Proveedores de insumos SAP"
    },
    "logo": null,
    "paymentCondition": {
      "id": 4,
      "conditionName": "45 dias",
      "days": 45
    },
    "status": 1
  },
  {
    "id": 18,
    "supplierNumber": "IND004",
    "rfc": "IND040404HIJ",
    "businessName": "Servicios de Limpieza Industrial",
    "supplierType": {
      "id": 3,
      "code": "INDIRECTOS",
      "description": "Proveedores de insumos SAP"
    },
    "logo": null,
    "paymentCondition": {
      "id": 2,
      "conditionName": "15 dias",
      "days": 15
    },
    "status": 1
  },
  {
    "id": 19,
    "supplierNumber": "SERV001",
    "rfc": "SRV010101KLM",
    "businessName": "Consultoria Empresarial ABC",
    "supplierType": {
      "id": 4,
      "code": "SERVICIOS",
      "description": "Proveedores de servicios"
    },
    "logo": null,
    "paymentCondition": {
      "id": 3,
      "conditionName": "30 dias",
      "days": 30
    },
    "status": 1
  },
  {
    "id": 20,
    "supplierNumber": "SERV002",
    "rfc": "SRV020202NOP",
    "businessName": "Mantenimiento Electrico Industrial",
    "supplierType": {
      "id": 4,
      "code": "SERVICIOS",
      "description": "Proveedores de servicios"
    },
    "logo": null,
    "paymentCondition": {
      "id": 4,
      "conditionName": "45 dias",
      "days": 45
    },
    "status": 1
  },
  {
    "id": 21,
    "supplierNumber": "SERV003",
    "rfc": "SRV030303QRS",
    "businessName": "Seguridad Privada Nacional",
    "supplierType": {
      "id": 4,
      "code": "SERVICIOS",
      "description": "Proveedores de servicios"
    },
    "logo": null,
    "paymentCondition": {
      "id": 5,
      "conditionName": "60 dias",
      "days": 60
    },
    "status": 1
  },
  {
    "id": 22,
    "supplierNumber": "SERV004",
    "rfc": "SRV040404TUV",
    "businessName": "Asesoria Legal Corporativa",
    "supplierType": {
      "id": 4,
      "code": "SERVICIOS",
      "description": "Proveedores de servicios"
    },
    "logo": null,
    "paymentCondition": {
      "id": 3,
      "conditionName": "30 dias",
      "days": 30
    },
    "status": 1
  }
];



export const Catalogs = {
  CatEstatusFactura,
  CatEstatusPago,
  CatEstatusNotaCredito,
  catMsgAdverrtencia,
  catMsgNegocio,
  catMsgErrorSistema,
  CatMsgExitoso,
  CatMsgInformativo
};