sonar.projectKey=boss-order-process-in
sonar.projectName=boss-order-process-in
sonar.language=java
sonar.java.binaries=./
sonar.coverage.jacoco.xmlReportPaths=build/jacocoReport/jacocoXML/jacoco.xml
sonar.java.coveragePlugin=jacoco
