package com.sodimac.rebates.enums;

public enum EMensaje {

	DOCUMENTO_CARGADO,
	EXTENSION_INCORRECTA,
	ARCHIVO_VACIO,
	ERROR_PROCESAR_ARCHIVO,
	INFORMACION_INCOMPLETA,
	CABECERA_INCORRECTA,
	
	CATALOGO_CARGADO
}
