sonar.projectKey=APP03022-mrch.backend.somx.fiscal-api
sonar.projectName=APP03022-mrch.backend.somx.fiscal-api

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

sonar.exclusions=**/target/**,**/*.xml,**/*.json,**/*.yaml,**/*.yml,**/generated/**
sonar.coverage.exclusions=**/config/**,**/dto/**,**/entity/**,**/model/**,**/generated/**,**/*Application.java

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml