# jdbc.X
jdbc.config.driverClassName=com.mysql.cj.jdbc.Driver

# DEV
jdbc.config.url=MDAwMDAwMDAwMDAwMDAwMG9P6VRjJbgY4HNO+fz5AOuKnjsjtPFBndYbXRCT+/pW5iN3P1Xn8OBWnYWrGzuRZja1VXRW8kuvPvG/2cYhYrPegOvInx/7lE27x17d9Qk69U1YRMmGDcNUFSyNHhepfLrL2G6fBKGQg/xgtox51lDjayjKniwJZakIy1r++QQ41ZeKR68S6++ZH7/LcsEFcgYJx/dFzXpaZROpvxSxfT4=
jdbc.config.user=MDAwMDAwMDAwMDAwMDAwMNHtwXog/6rKEM5kq2H6qng=
jdbc.config.pass=MDAwMDAwMDAwMDAwMDAwMNHtwXog/6rKEM5kq2H6qng=

# PROD 
#jdbc.config.url=MDAwMDAwMDAwMDAwMDAwMG9P6VRjJbgY4HNO+fz5AOtosDx0gOmhY7Plv6UMbMwqXFQdXeYPvzHtzjNyeBD2ysntelQ71hphp5fzY7duwxMiCvLu4C1c+M0sp0PehbuF5Rm+DM/o+2sacMQFGasOd/EeM/LoYEANYDxzr5ZCf/yK4UEnEYiJJY4yHC5RnKJW6RXgR8gOIEagbKzwxax7UcpG/SyrNgwEIq3HJHSsUcU=
#jdbc.config.user=MDAwMDAwMDAwMDAwMDAwMNHtwXog/6rKEM5kq2H6qng=
#jdbc.config.pass=MDAwMDAwMDAwMDAwMDAwMJAu0nLy5wPD7PDtIjLNpbU=

# hibernate.X
hibernate.config.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
hibernate.config.show_sql=true
hibernate.config.hbm2ddl.auto=none
hibernate.config.cache.use_second_level_cache=false
hibernate.config.cache.use_query_cache=false

# c3p0.X
c3p0.config.min_size=5
c3p0.config.max_size=20
c3p0.config.acquire_increment=5
c3p0.config.timeout=1800
c3p0.config.testConnectionOnCheckout=true
c3p0.config.preferredTestQuery=SELECT 1
c3p0.config.idleConnectionTestPeriod=14400
c3p0.config.privilegeSpawnedThreads=true
c3p0.config.contextClassLoaderSource=library