// src/docs/components/rebate.ts
import type { OpenAPIV3 } from "openapi-types";

export const rebateSchemas: Record<string, OpenAPIV3.SchemaObject> = {
    Rebate: {
        type: "object",
        properties: {
            id: { type: "string", format: "uuid", description: "UUID primary key" },
            documentNumber: { type: "string", description: "Document number" },
            referenceNumber: { type: "string", description: "Reference number" },
            sapDocument: { type: "string", nullable: true, description: "SAP document number" },
            vendorNumber: { type: "integer", description: "Vendor identifier" },
            amount: { type: "string", description: "Rebate amount (numeric string)" },
            source: { type: "integer", description: "Source identifier" },
            periodId: { type: "integer", description: "Period identifier (e.g., 202501)" },
            dueDate: { type: "string", format: "date-time", description: "Due date" },
            postingDate: { type: "string", format: "date-time", description: "Posting date" },
            status: { type: "integer", description: "Status code (1=pending, 2=published)" },
            createdBy: { type: "integer", description: "User ID who created the record" },
            createdAt: { type: "string", format: "date-time", description: "Creation timestamp" },
            updatedBy: { type: "integer", nullable: true, description: "User ID who updated the record" },
            updatedAt: { type: "string", format: "date-time", nullable: true, description: "Update timestamp" },
            stampedRebate: { $ref: "#/components/schemas/StampedRebate", nullable: true },
        },
        required: ["id", "documentNumber", "referenceNumber", "vendorNumber", "amount", "source", "periodId", "dueDate", "postingDate", "status", "createdBy"],
    },
    CreateRebateDto: {
        type: "object",
        properties: {
            documentNumber: { type: "string", description: "Document number" },
            referenceNumber: { type: "string", description: "Reference number" },
            sapDocument: { type: "string", nullable: true, description: "SAP document number" },
            vendorNumber: { type: "integer", description: "Vendor identifier" },
            amount: { type: "string", description: "Rebate amount (numeric string)" },
            source: { type: "integer", description: "Source identifier" },
            periodId: { type: "integer", description: "Period identifier (e.g., 202501)" },
            dueDate: { type: "string", format: "date-time", description: "Due date" },
            postingDate: { type: "string", format: "date-time", description: "Posting date" },
            status: { type: "integer", description: "Status code (1=pending, 2=published)" },
            createdBy: { type: "integer", description: "User ID who created the record" },
        },
        required: ["documentNumber", "referenceNumber", "vendorNumber", "amount", "source", "periodId", "dueDate", "postingDate", "status", "createdBy"],
    },
    UpdateRebateDto: {
        type: "object",
        properties: {
            documentNumber: { type: "string", description: "Document number" },
            referenceNumber: { type: "string", description: "Reference number" },
            sapDocument: { type: "string", nullable: true, description: "SAP document number" },
            amount: { type: "string", description: "Rebate amount (numeric string)" },
            source: { type: "integer", description: "Source identifier" },
            periodId: { type: "integer", description: "Period identifier" },
            dueDate: { type: "string", format: "date-time", description: "Due date" },
            postingDate: { type: "string", format: "date-time", description: "Posting date" },
            status: { type: "integer", description: "Status code (1=pending, 2=published)" },
            updatedBy: { type: "integer", description: "User ID who updated the record" },
        },
    },
    RebateFilterDto: {
        type: "object",
        properties: {
            vendorNumber: { type: "integer", description: "Filter by vendor number" },
            documentNumber: { type: "string", description: "Filter by document number (LIKE search)" },
            sapDocument: { type: "string", description: "Filter by SAP document (LIKE search)" },
            status: { type: "integer", description: "Filter by status code" },
            periodId: { type: "integer", description: "Filter by period ID" },
            limit: { type: "integer", default: 20, minimum: 1, maximum: 1000, description: "Results per page" },
            page: { type: "integer", default: 0, minimum: 0, description: "Page number (0-indexed)" },
        },
    },
    StampedRebate: {
        type: "object",
        properties: {
            id: { type: "string", format: "uuid", description: "UUID primary key" },
            documentNumber: { type: "string", description: "Document number" },
            vendorNumber: { type: "integer", description: "Vendor identifier" },
            status: { type: "integer", description: "Status code" },
            amount: { type: "string", description: "Total amount (numeric string)" },
            periodId: { type: "integer", description: "Period identifier" },
            createdBy: { type: "integer", description: "User ID who created the record" },
            createdAt: { type: "string", format: "date-time", description: "Creation timestamp" },
            updatedBy: { type: "integer", nullable: true, description: "User ID who updated the record" },
            updatedAt: { type: "string", format: "date-time", nullable: true, description: "Update timestamp" },
        },
        required: ["id", "documentNumber", "vendorNumber", "status", "amount", "periodId", "createdBy"],
    },
};
