// src/docs/components/shippingGuide.ts
import type { OpenAPIV3 } from "openapi-types";

export const shippingGuideSchemas: Record<string, OpenAPIV3.SchemaObject> = {
    ShippingGuide: {
        type: "object",
        properties: {
            id: { type: "string", format: "uuid", description: "UUID primary key" },
            guideNumber: { type: "string", description: "Shipping guide number" },
            vendorNumber: { type: "integer", description: "Vendor identifier" },
            truckPlate: { type: "string", description: "Truck license plate" },
            trailerPlate: { type: "string", nullable: true, description: "Trailer license plate" },
            driverName: { type: "string", description: "Driver full name" },
            driverLicense: { type: "string", description: "Driver's license number" },
            sourceId: { type: "integer", description: "Source location ID" },
            destinationId: { type: "integer", description: "Destination location ID" },
            deliveryType: { type: "integer", description: "Delivery type code" },
            amount: { type: "string", description: "Shipment amount (numeric string)" },
            currency: { type: "string", description: "Currency code" },
            status: { type: "integer", description: "Status code" },
            comments: { type: "string", nullable: true, description: "Additional comments" },
            deliveryDate: { type: "string", format: "date-time", description: "Scheduled delivery date" },
            estimatedArrival: { type: "string", format: "date-time", description: "Estimated arrival timestamp" },
            actualArrival: { type: "string", format: "date-time", nullable: true, description: "Actual arrival timestamp" },
            sentAt: { type: "string", format: "date-time", description: "Sent timestamp" },
            createdBy: { type: "integer", description: "User ID who created the record" },
            createdAt: { type: "string", format: "date-time", description: "Creation timestamp" },
            updatedBy: { type: "integer", nullable: true, description: "User ID who updated the record" },
            updatedAt: { type: "string", format: "date-time", nullable: true, description: "Update timestamp" },
        },
        required: ["id", "guideNumber", "vendorNumber", "truckPlate", "driverName", "driverLicense", "sourceId", "destinationId", "deliveryType", "amount", "currency", "status", "deliveryDate", "estimatedArrival", "sentAt", "createdBy"],
    },
    CreateShippingGuideDto: {
        type: "object",
        properties: {
            guideNumber: { type: "string" },
            vendorNumber: { type: "integer" },
            truckPlate: { type: "string" },
            trailerPlate: { type: "string", nullable: true },
            driverName: { type: "string" },
            driverLicense: { type: "string" },
            sourceId: { type: "integer" },
            destinationId: { type: "integer" },
            deliveryType: { type: "integer" },
            amount: { type: "string" },
            currency: { type: "string" },
            status: { type: "integer" },
            comments: { type: "string", nullable: true },
            deliveryDate: { type: "string", format: "date-time" },
            estimatedArrival: { type: "string", format: "date-time" },
            actualArrival: { type: "string", format: "date-time", nullable: true },
            sentAt: { type: "string", format: "date-time" },
            createdBy: { type: "integer" },
        },
        required: ["guideNumber", "vendorNumber", "truckPlate", "driverName", "driverLicense", "sourceId", "destinationId", "deliveryType", "amount", "currency", "status", "deliveryDate", "estimatedArrival", "sentAt", "createdBy"],
    },
    UpdateShippingGuideDto: {
        type: "object",
        properties: {
            status: { type: "integer" },
            actualArrival: { type: "string", format: "date-time" },
            comments: { type: "string" },
            updatedBy: { type: "integer" },
        },
    },
};
