-- src/main/resources/db/migration/V1_2__faq_alias_and_attachment.sql
CREATE TABLE PUBLIC.FAQ_ALIAS (
    ID          SERIAL PRIMARY KEY,
    FAQ_ID      BIGINT       NOT NULL REFERENCES PUBLIC.FAQ(ID),
    QUESTION    TEXT         NOT NULL,
    IS_ACTIVE   BOOLEAN      NOT NULL DEFAULT TRUE,
    CREATED_AT  TIMESTAMP    NOT NULL DEFAULT now(),
    UPDATED_AT  TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE TABLE PUBLIC.FAQ_ATTACHMENT (
    ID           SERIAL PRIMARY KEY,
    FAQ_ID       BIGINT     NOT NULL REFERENCES PUBLIC.FAQ(ID),
    FILE_NAME    VARCHAR(255) NOT NULL,
    FILE_PATH    VARCHAR(1024) NOT NULL,
    CONTENT_TYPE VARCHAR(100) NOT NULL,
    SIZE_KB      INT         NOT NULL,
    IS_ACTIVE    BOOLEAN     NOT NULL DEFAULT TRUE,
    CREATED_AT   TIMESTAMP   NOT NULL DEFAULT now(),
    UPDATED_AT   TIMESTAMP   NOT NULL DEFAULT now()
);
