CREATE PROCEDURE [dbo].[uspGeneraTableroTimbrado] 
AS

/**
* Ajuste para mejorar el performace del proceso para conocer el monto de facturación global
* por tienda y día
*
* MODIF --> 001
* MODIF <-- 001
*/
DECLARE 
@V_TICKET AS VARCHAR(20),
@V_UUID   AS VARCHAR(40),
@V_FECHA_TICKET AS DATE,
@V_TIENDA AS NUMERIC,

@V_SUBTOTAL_POS                  AS NUMERIC(18,2) = 0,
@V_NUMERO_TICKET_POS             AS NUMERIC       = 0,
@V_SUBTOTAL_FAC_GLO              AS NUMERIC(18,2) = 0,
@V_NUMERO_TICKET_FAC_GLO         AS NUMERIC       = 0,
@V_DIF_SUBTOTAL_POS_FAC_GLO      AS NUMERIC(18,3) = 0.00,
@V_DIF_TICKET_POS_FAC_GLO        AS NUMERIC       = 0,

@V_NUMERO_TICKET_FAC_CLI         AS NUMERIC       = 0,
@V_SUBTOTAL_FAC_CLI              AS NUMERIC(18,2) = 0,
@V_NUMERO_TICKET_FAC_CLI_NC_GLO  AS NUMERIC       = 0 ,
@V_SUBTOTAL_FAC_CLI_NC_GLO       AS NUMERIC(18,2) = 0,
@V_DIF_TICKET_FAC_CLI_NC_GLO     AS NUMERIC       = 0,
@V_DIF_SUBTOTAL_FAC_CLI_NC_GLO   AS NUMERIC(18,2) = 0,


@V_SUBTOTAL_POS_DEV              AS NUMERIC(18,2) = 0,
@V_NUMERO_TICKET_POS_DEV         AS NUMERIC       = 0,
@V_SUBTOTAL_NC_GLO               AS NUMERIC(18,2) = 0,
@V_NUMERO_TICKET_NC_GLO          AS NUMERIC       = 0,
@V_DIF_SUBTOTAL_POS_DEV_NC_GLO   AS NUMERIC(18,2) = 0,
@V_DIF_TICKET_POS_DEV_NC_GLO     AS NUMERIC       = 0,

@V_SUBTOTAL_NC_CLI               AS NUMERIC(18,2) = 0,
@V_NUMERO_TICKET_NC_CLI          AS NUMERIC       = 0,
@V_SUBTOTAL_FAC_GLO_NC_CLI       AS NUMERIC(18,2) = 0,
@V_NUMERO_TICKET_FAC_GLO_NC_CLI  AS NUMERIC       = 0,
@V_DIF_SUBTOTAL_FAC_GLO_NC_CLI   AS NUMERIC(18,2) = 0,
@V_DIF_TICKET_FAC_GLO_NC_CLI     AS NUMERIC       = 0,
@V_CONTADOR                      AS NUMERIC       = 0;


TRUNCATE TABLE [dbo].[TIMBRADO_DIFERENCIA];

SELECT 
FECHA_TICKET,
TIENDA,
'1' CANAL,
SUM(CONVERT(NUMERIC(18,2),SUBTOTAL)) SUBTOTAL_POS,
COUNT(1) NUMERO_TICKET_POS,
0 SUBTOTAL_FAC_GLO	,
0 NUMERO_TICKET_FAC_GLO,
0 DIF_SUBTOTAL_POS_FAC_GLO,
0 DIF_TICKET_POS_FAC_GLO,
0 SUBTOTAL_FAC_CLI,
0 NUMERO_TICKET_FAC_CLIE,
0 SUBTOTAL_FAC_CLI_NC_GLO,
0 NUMERO_TICKET_FAC_CLI_NC_GLO,
0 DIF_SUBTOTAL_FAC_CLI_NC_GLO,
0 DIF_TICKET_FAC_CLI_NC_GLO,
0 SUBTOTAL_POS_DEV,
0 NUMERO_TICKET_POS_DEV,
0 SUBTOTAL_NC_GLO,
0 NUMERO_TICKET_NC_GLO,
0 DIF_SUBTOTAL_POS_DEV_NC_GLO,
0 DIF_TICKET_POS_DEV_NC_GLO,
0 SUBTOTAL_NC_CLI,
0 NUMERO_TICKET_NC_CLI,
0 SUBTOTAL_FAC_GLO_NC_CLI,
0 NUMERO_TICKET_FAC_GLO_NC_CLI,
0 DIF_SUBTOTAL_FAC_GLO_NC_CLI,
0 DIF_TICKET_FAC_GLO_NC_CLI,
GETDATE() FECHA_REGISTRO
INTO #TABLERO_TEMP
FROM [dbo].[RELACION_VENTA_FACTURACION]
WHERE TIPO=1
AND CONVERT(NUMERIC,SUBSTRING(TICKET,1,4)) >= 2024
AND (NUM_DOC_CANAL IS NULL OR LTRIM(RTRIM(NUM_DOC_CANAL))='' OR NUM_DOC_CANAL NOT LIKE '26%') 
AND ABS(CONVERT(NUMERIC(18,2),SUBTOTAL))>0
GROUP BY FECHA_TICKET,TIENDA

    SELECT *
	INTO #FACTURACION_GLOBAL_CAB_TEMP
	FROM FACTURACION_GLOBAL_CAB

	SELECT *
	INTO #FACTURACION_GLOBAL_DET_TEMP
	FROM FACTURACION_GLOBAL_DET

	SELECT *
	INTO #VENTA_CAB_TEMP
	FROM VENTA_CAB

	SELECT *
	INTO #TIMBRADO_PAC_DETECNO_TEMP
	FROM [dbo].[TIMBRADO_PAC_DETECNO]

	SELECT A.FECHA_TIMBRADO,A.UUID,A.TRANSACCION,A.TICKET,A.SERIE,A.FOLIO,B.TIENDA,A.FechaCarga,B.SUBTOTAL,B.TOTAL,B.FECHA_TICKET
	INTO #FACTURACION_CLIENTE_TEMP
	FROM FACTURACION_CLIENTE A
	LEFT JOIN VENTA_CAB B
	ON A.TICKET = B.TICKET
	
	CREATE NONCLUSTERED INDEX ix_tempFacturacionCab ON #FACTURACION_GLOBAL_CAB_TEMP (NUM_TIENDA,F_VENTA);
	CREATE NONCLUSTERED INDEX ix_tempFacturacionDet ON #FACTURACION_GLOBAL_DET_TEMP (ID_PROCESO);
	CREATE NONCLUSTERED INDEX ix_tempVentaCab ON #VENTA_CAB_TEMP (TIENDA,FECHA_TICKET);
	CREATE NONCLUSTERED INDEX ix_tempVentaCabTicket ON #VENTA_CAB_TEMP (TICKET);
    CREATE NONCLUSTERED INDEX ix_tempTableroTimbrado ON #TABLERO_TEMP (TIENDA,FECHA_TICKET);
	CREATE NONCLUSTERED INDEX ix_tempTimbradoPacDetecno ON #TIMBRADO_PAC_DETECNO_TEMP (REGION);
	CREATE NONCLUSTERED INDEX ix_tempTimbradoCliente ON #FACTURACION_CLIENTE_TEMP (TICKET);

	DECLARE ConsultaTablero CURSOR FOR 
	SELECT FECHA_TICKET,TIENDA,SUBTOTAL_POS,NUMERO_TICKET_POS 
	FROM #TABLERO_TEMP
	ORDER BY FECHA_TICKET,TIENDA ASC
	
	OPEN ConsultaTablero
	FETCH NEXT FROM ConsultaTablero INTO @V_FECHA_TICKET,@V_TIENDA,@V_SUBTOTAL_POS,@V_NUMERO_TICKET_POS
	WHILE @@fetch_status = 0
	BEGIN
	    
	   /*--------------------------------------------------------------
		*--- Bloque para obtener las cifras de la facturación global
		*-------------------------------------------------------------*/
	    SET @V_NUMERO_TICKET_FAC_GLO=0
		SET @V_SUBTOTAL_FAC_GLO = 0

		SELECT @V_NUMERO_TICKET_FAC_GLO=COUNT(1)
		FROM #FACTURACION_GLOBAL_CAB_TEMP A
		INNER JOIN #FACTURACION_GLOBAL_DET_TEMP B
		ON A.ID_PROCESO = B.ID_PROCESO
		WHERE A.NUM_TIENDA=@V_TIENDA
		AND A.F_VENTA=@V_FECHA_TICKET
		AND A.TIPO_OPERACION='V'
		AND A.TIPO_FACTURA='G'
		
		
		-- Consulta de ticket a nivel de venta global
	    SELECT @V_NUMERO_TICKET_FAC_GLO=COUNT(1)
		FROM #FACTURACION_GLOBAL_CAB_TEMP A
		INNER JOIN #FACTURACION_GLOBAL_DET_TEMP B
		ON A.ID_PROCESO = B.ID_PROCESO
		WHERE A.NUM_TIENDA=@V_TIENDA
		AND A.F_VENTA=@V_FECHA_TICKET
		AND A.TIPO_OPERACION='V'
		AND A.TIPO_FACTURA='G'
		
		
		SELECT @V_SUBTOTAL_FAC_GLO=SUM(A.SUBTOTAL)
		FROM #FACTURACION_GLOBAL_CAB_TEMP A
		WHERE A.NUM_TIENDA=@V_TIENDA
		AND A.F_VENTA=@V_FECHA_TICKET
		AND A.TIPO_OPERACION='V'
	AND A.TIPO_FACTURA='G'
		AND EXISTS (
		    SELECT 1
			FROM #FACTURACION_GLOBAL_DET_TEMP B
			WHERE A.ID_PROCESO = B.ID_PROCESO
		)

		SET @V_NUMERO_TICKET_FAC_GLO = ISNULL(@V_NUMERO_TICKET_FAC_GLO,-999999999)
		SET @V_SUBTOTAL_FAC_GLO      = ISNULL(@V_SUBTOTAL_FAC_GLO,-999999999)
		
		SET @V_DIF_SUBTOTAL_POS_FAC_GLO = @V_SUBTOTAL_POS - (CASE WHEN @V_SUBTOTAL_FAC_GLO = -999999999 THEN 0 ELSE @V_SUBTOTAL_FAC_GLO END)
		SET @V_DIF_TICKET_POS_FAC_GLO   = @V_NUMERO_TICKET_POS - (CASE WHEN @V_NUMERO_TICKET_FAC_GLO = -999999999 THEN 0 ELSE @V_NUMERO_TICKET_FAC_GLO END)
	   
		/*--------------------------------------------------------------
		*--- Bloque para obtener las cifras de la facturación de cliente
		*--- y comparativo de nc global
		*-------------------------------------------------------------*/
		SET @V_SUBTOTAL_FAC_CLI      = 0
		SET @V_NUMERO_TICKET_FAC_CLI = 0

		-- Se deja la tabla de control de sodimac para identificar
		-- si hace falta sincronizar los folios de detecno
		SELECT @V_NUMERO_TICKET_FAC_CLI=COUNT(1) 
		FROM #FACTURACION_CLIENTE_TEMP A
		INNER JOIN #VENTA_CAB_TEMP B
		ON A.TICKET = B.TICKET
		WHERE B.TIENDA = @V_TIENDA
		AND B.FECHA_TICKET = @V_FECHA_TICKET
		AND B.TIPO='1'
		AND (A.UUID IS NOT NULL OR LTRIM(RTRIM(A.UUID)) !='')

		SELECT @V_SUBTOTAL_FAC_CLI=SUM(A.SuBTotal)
		FROM #FACTURACION_CLIENTE_TEMP A
		INNER JOIN #VENTA_CAB_TEMP B
		ON A.TICKET = B.TICKET
		WHERE B.TIENDA = @V_TIENDA
		AND B.FECHA_TICKET = @V_FECHA_TICKET
		AND B.TIPO='1'
		AND (A.UUID IS NOT NULL OR LTRIM(RTRIM(A.UUID)) !='')

		SET @V_SUBTOTAL_FAC_CLI = ISNULL(@V_SUBTOTAL_FAC_CLI,-999999999)
		SET @V_NUMERO_TICKET_FAC_CLI = ISNULL(@V_NUMERO_TICKET_FAC_CLI,-999999999)

		SET @V_SUBTOTAL_FAC_CLI_NC_GLO = 0
		SET @V_NUMERO_TICKET_FAC_CLI_NC_GLO = 0

		SELECT @V_SUBTOTAL_FAC_CLI_NC_GLO=SUM(A.SUBTOTAL)
		FROM #FACTURACION_GLOBAL_CAB_TEMP A
		WHERE A.NUM_TIENDA=@V_TIENDA
		AND A.F_VENTA=@V_FECHA_TICKET
		AND A.TIPO_OPERACION='FD'
		AND A.TIPO_FACTURA='G'
		AND EXISTS (
		   SELECT 1
		   FROM #FACTURACION_GLOBAL_DET_TEMP B
		   WHERE A.ID_PROCESO = B.ID_PROCESO
		)

		SELECT @V_NUMERO_TICKET_FAC_CLI_NC_GLO=COUNT(1)
		FROM #FACTURACION_GLOBAL_CAB_TEMP A
		INNER JOIN #FACTURACION_GLOBAL_DET_TEMP B
		ON A.ID_PROCESO = B.ID_PROCESO
		WHERE A.NUM_TIENDA=@V_TIENDA
		AND A.F_VENTA=@V_FECHA_TICKET
		AND A.TIPO_OPERACION='FD'
		AND A.TIPO_FACTURA='G'
	
	    SET @V_SUBTOTAL_FAC_CLI_NC_GLO      = ISNULL(@V_SUBTOTAL_FAC_CLI_NC_GLO,-999999999)
		SET @V_NUMERO_TICKET_FAC_CLI_NC_GLO = ISNULL(@V_NUMERO_TICKET_FAC_CLI_NC_GLO,-999999999)
		
		SET @V_DIF_TICKET_FAC_CLI_NC_GLO    = @V_NUMERO_TICKET_FAC_CLI -(CASE WHEN @V_NUMERO_TICKET_FAC_CLI_NC_GLO = -999999999 THEN 0 ELSE  @V_NUMERO_TICKET_FAC_CLI_NC_GLO END)
		SET @V_DIF_SUBTOTAL_FAC_CLI_NC_GLO  = @V_SUBTOTAL_FAC_CLI      -(CASE WHEN @V_SUBTOTAL_FAC_CLI_NC_GLO = -999999999 THEN 0 ELSE @V_SUBTOTAL_FAC_CLI_NC_GLO END)  
		
		/*--------------------------------------------------------------
		*--- Bloque para obtener las cifras de las devoluciones y 
		*--- notas de credito global
		*-------------------------------------------------------------*/
		 
		SET @V_SUBTOTAL_POS_DEV = 0
		SET @V_NUMERO_TICKET_POS_DEV = 0

		SELECT @V_SUBTOTAL_POS_DEV = SUM(A.SUBTOTAL*-1) 
		FROM #VENTA_CAB_TEMP A
		WHERE A.FECHA_TICKET=@V_FECHA_TICKET
		AND A.TIENDA = @V_TIENDA
		AND A.TIPO IN (9,10)

		SELECT @V_NUMERO_TICKET_POS_DEV = COUNT(1) 
		FROM #VENTA_CAB_TEMP A
		WHERE A.FECHA_TICKET=@V_FECHA_TICKET
		AND A.TIENDA = @V_TIENDA
		AND A.TIPO IN (9,10)

		SET @V_SUBTOTAL_POS_DEV = ISNULL(@V_SUBTOTAL_POS_DEV,-999999999)
		SET @V_NUMERO_TICKET_POS_DEV=ISNULL(@V_NUMERO_TICKET_POS_DEV,-999999999)

		SET @V_SUBTOTAL_NC_GLO = 0
		SET @V_NUMERO_TICKET_NC_GLO = 0

	    SELECT @V_SUBTOTAL_NC_GLO=SUM(SUBTOTAL)
		FROM #FACTURACION_GLOBAL_CAB_TEMP A
		WHERE A.NUM_TIENDA=@V_TIENDA
		AND A.F_VENTA=@V_FECHA_TICKET
		AND A.TIPO_OPERACION='D'
		AND A.TIPO_FACTURA='G'
		AND A.UUID IS NOT NULL 
		AND LTRIM(RTRIM(A.UUID)) !=''
				
	    SELECT @V_NUMERO_TICKET_NC_GLO=COUNT(1)
		FROM #FACTURACION_GLOBAL_CAB_TEMP A
		INNER JOIN #FACTURACION_GLOBAL_DET_TEMP B
		ON A.ID_PROCESO = B.ID_PROCESO
		WHERE A.NUM_TIENDA=@V_TIENDA
		AND A.F_VENTA=@V_FECHA_TICKET
		AND A.TIPO_OPERACION='D'
		AND A.TIPO_FACTURA='G'
		AND A.UUID IS NOT NULL 
		AND LTRIM(RTRIM(A.UUID)) !=''

		SET @V_NUMERO_TICKET_NC_GLO = ISNULL(@V_NUMERO_TICKET_NC_GLO,-999999999)
		SET @V_SUBTOTAL_NC_GLO=ISNULL(@V_SUBTOTAL_NC_GLO,-999999999)

		SET @V_DIF_SUBTOTAL_POS_DEV_NC_GLO = @V_SUBTOTAL_POS_DEV - (CASE WHEN @V_SUBTOTAL_NC_GLO = -999999999 THEN 0  ELSE @V_SUBTOTAL_NC_GLO END)
        SET @V_DIF_TICKET_POS_DEV_NC_GLO = @V_NUMERO_TICKET_POS_DEV - (CASE WHEN @V_NUMERO_TICKET_NC_GLO = -999999999 THEN 0  ELSE @V_NUMERO_TICKET_NC_GLO END)

		/*--------------------------------------------------------------
		*--- Bloque para obtener las cifras de las notas de credito cliente
		*-------------------------------------------------------------*/

		SET @V_SUBTOTAL_NC_CLI = 0
		SET @V_NUMERO_TICKET_NC_CLI = 0

		SELECT @V_NUMERO_TICKET_NC_CLI=COUNT(1) 
		FROM #FACTURACION_CLIENTE_TEMP A
		INNER JOIN #VENTA_CAB_TEMP B
		ON A.TICKET = B.TICKET
		WHERE B.TIENDA = @V_TIENDA
		AND B.FECHA_TICKET = @V_FECHA_TICKET
		AND B.TIPO IN ('9','10')
		AND (A.UUID IS NOT NULL OR LTRIM(RTRIM(A.UUID)) !='')

		SELECT @V_SUBTOTAL_NC_CLI=SUM(A.SuBTotal)
		FROM #TIMBRADO_PAC_DETECNO_TEMP A
		INNER JOIN #VENTA_CAB_TEMP B
		ON A.REGION = B.TICKET
		WHERE B.TIENDA = @V_TIENDA
		AND B.FECHA_TICKET = @V_FECHA_TICKET
		AND B.TIPO IN ('9','10')
		AND (A.UUID IS NOT NULL OR LTRIM(RTRIM(A.UUID)) !='')

		SET @V_NUMERO_TICKET_NC_CLI = ISNULL(@V_NUMERO_TICKET_NC_CLI,-999999999)
		SET @V_SUBTOTAL_NC_CLI      = ISNULL(@V_SUBTOTAL_NC_CLI,-999999999)

		SET @V_SUBTOTAL_FAC_GLO_NC_CLI = 0
		SET @V_NUMERO_TICKET_FAC_GLO_NC_CLI = 0
        SET @V_DIF_SUBTOTAL_FAC_GLO_NC_CLI = 0
        SET @V_DIF_TICKET_FAC_GLO_NC_CLI = 0
        
		UPDATE #TABLERO_TEMP SET SUBTOTAL_FAC_GLO         = @V_SUBTOTAL_FAC_GLO         ,
		                         NUMERO_TICKET_FAC_GLO    = @V_NUMERO_TICKET_FAC_GLO    ,
								 DIF_SUBTOTAL_POS_FAC_GLO = @V_DIF_SUBTOTAL_POS_FAC_GLO ,
								 DIF_TICKET_POS_FAC_GLO   = @V_DIF_TICKET_POS_FAC_GLO   ,

								 SUBTOTAL_FAC_CLI         = @V_SUBTOTAL_FAC_CLI         ,
								 NUMERO_TICKET_FAC_CLIE   = @V_NUMERO_TICKET_FAC_CLI    ,
								 SUBTOTAL_FAC_CLI_NC_GLO  = @V_SUBTOTAL_FAC_CLI_NC_GLO  ,
								 NUMERO_TICKET_FAC_CLI_NC_GLO = @V_NUMERO_TICKET_FAC_CLI_NC_GLO,
								 DIF_SUBTOTAL_FAC_CLI_NC_GLO  = @V_DIF_SUBTOTAL_FAC_CLI_NC_GLO,
								 DIF_TICKET_FAC_CLI_NC_GLO    = @V_DIF_TICKET_FAC_CLI_NC_GLO,

								 SUBTOTAL_POS_DEV             = @V_SUBTOTAL_POS_DEV,
								 NUMERO_TICKET_POS_DEV        = @V_NUMERO_TICKET_POS_DEV,
								 SUBTOTAL_NC_GLO              = @V_SUBTOTAL_NC_GLO,
								 NUMERO_TICKET_NC_GLO         = @V_NUMERO_TICKET_NC_GLO,
								 DIF_SUBTOTAL_POS_DEV_NC_GLO  = @V_DIF_SUBTOTAL_POS_DEV_NC_GLO,
								 DIF_TICKET_POS_DEV_NC_GLO    = @V_DIF_TICKET_POS_DEV_NC_GLO,

								 SUBTOTAL_NC_CLI              = @V_SUBTOTAL_NC_CLI,
								 NUMERO_TICKET_NC_CLI         = @V_NUMERO_TICKET_NC_CLI,

								 SUBTOTAL_FAC_GLO_NC_CLI      = @V_SUBTOTAL_FAC_GLO_NC_CLI,
								 NUMERO_TICKET_FAC_GLO_NC_CLI = @V_NUMERO_TICKET_FAC_GLO_NC_CLI,

								 DIF_SUBTOTAL_FAC_GLO_NC_CLI  = @V_DIF_SUBTOTAL_FAC_GLO_NC_CLI,
								 DIF_TICKET_FAC_GLO_NC_CLI    = @V_DIF_TICKET_FAC_GLO_NC_CLI

        WHERE TIENDA       =   @V_TIENDA
		AND FECHA_TICKET   =   @V_FECHA_TICKET
		
		
	    FETCH NEXT FROM ConsultaTablero INTO @V_FECHA_TICKET,@V_TIENDA,@V_SUBTOTAL_POS,@V_NUMERO_TICKET_POS

	END

	CLOSE ConsultaTablero

	DEALLOCATE ConsultaTablero
	
	-- Limpia el tablero para actualizar las cifras de timbrado 
    TRUNCATE TABLE [dbo].[TABLERO_CONTROL_TIMBRADO];

	INSERT INTO [dbo].[TABLERO_CONTROL_TIMBRADO]
	SELECT * FROM #TABLERO_TEMP
    
	DROP TABLE #TABLERO_TEMP;