-- EXEC [dbo].[uspRelacionVentaFactura]

CREATE PROCEDURE [dbo].[uspRelacionVentaFactura]
AS
BEGIN
DECLARE 
@V_TICKET AS VARCHAR(20),
@V_UUID   AS VARCHAR(40),
@V_FECHA_INICIO AS DATE,
@V_FECHA_FINAL AS DATE;

SET @V_FECHA_INICIO = CONVERT(DATE,'01/01/2026',103);
SET @V_FECHA_FINAL = CONVERT(DATE,'31/12/2026',103);

---------------------------------------------------------------------
-- Borra los registro duplicados de la tabla de insumo para evitar
-- generar información incorrecta en el reporte
---------------------------------------------------------------------
 WITH C AS
 (
  SELECT 
  FACTURA_ID,
  PAC,
  UUID,
  TICKET,
  ROW_NUMBER() OVER (
                     PARTITION BY
                       FACTURA_ID,PAC,UUID,TICKET
                     ORDER BY FACTURA_ID
					 ) AS DUPLICADO
  FROM [dbo].[TIMBRADO_INHOUSE] 
 )
 DELETE C 
 WHERE DUPLICADO > 1;

 WITH C AS
 (
  SELECT 
  TICKET,
  FECHA_TICKET,
  TIENDA,
  CAJA,
  TRANSACCION,
  TIPO,
  TOTAL,
  SUBTOTAL,
  REDONDEO,
  TICKET_ORIGEN,
  ROW_NUMBER() OVER (
                     PARTITION BY
                                  TICKET,
								  FECHA_TICKET,
								  TIENDA,
								  CAJA,
								  TRANSACCION,
								  TIPO,
								  TOTAL,
								  SUBTOTAL,
								  REDONDEO,
								  TICKET_ORIGEN
				     ORDER BY TICKET) AS DUPLICADO
  FROM [dbo].VENTA_CAB 
 )
 --SELECT * FROM  C
 DELETE C 
 WHERE DUPLICADO > 1;


 WITH C AS
 (
  SELECT 
  TICKET,
  FECHA_TICKET,
  TIENDA,
  CAJA,
  NUM_DOC_CANAL,
  CANAL_LINIO,
  TOTAL_ARTICULO,
  ROW_NUMBER() OVER (
                     PARTITION BY
								  TICKET,
								  FECHA_TICKET,
								  TIENDA,
								  CAJA,
								  NUM_DOC_CANAL,
								  CANAL_LINIO,
								  TOTAL_ARTICULO                     
					  ORDER BY TICKET) AS DUPLICADO
  FROM [dbo].VENTA_DET 
 )
 --SELECT * FROM  C
 DELETE C 
 WHERE DUPLICADO > 1;

 --WITH C AS
 --(
 -- SELECT 
 -- OC_LINIO,
 -- UUID,
 -- SERIE,
 -- FOLIO,
 -- ROW_NUMBER() OVER (
 --                    PARTITION BY
 -- OC_LINIO,
 -- UUID,
 -- SERIE,
 -- FOLIO					  ORDER BY OC_LINIO) AS DUPLICADO
 -- FROM [dbo].[TIMBRADO_PAC_LINIO] 
 --)
 ----SELECT * FROM  C
 --DELETE C 
 --WHERE DUPLICADO > 1;

  WITH C AS
 (
  SELECT 
  UUID,
  TRANSACCION,
  TICKET,
  SERIE,
  FOLIO,
  ROW_NUMBER() OVER (
                     PARTITION BY
  UUID,
  TRANSACCION,
  TICKET,
  SERIE,
  FOLIO					  ORDER BY TICKET) AS DUPLICADO
  FROM [dbo].[FACTURACION_CLIENTE] 
 )
 --SELECT * FROM  C
 DELETE C 
 WHERE DUPLICADO > 1;

 
  WITH C AS
 (
  SELECT 
  FACTURA_ID,
  ESTATUS,
  SERIE,
  FOLIO,
  RFC_EMISOR,
  RFC_RECEPTOR,
  FECHA,
  SUBTOTAL,
  TOTAL,
  UUID,
  REGION,
  ROW_NUMBER() OVER (
                     PARTITION BY
  FACTURA_ID,
  ESTATUS,
  SERIE,
  FOLIO,
  RFC_EMISOR,
  RFC_RECEPTOR,
  FECHA,
  SUBTOTAL,
  TOTAL,
  UUID,	
  REGION
  ORDER BY REGION) AS DUPLICADO
  FROM [dbo].[TIMBRADO_PAC_DETECNO_GLOBAL] 
 )
 --SELECT * FROM  C
 DELETE C 
 WHERE DUPLICADO > 1;
 
 WITH C AS
(
  SELECT 
  ID_PROCESO,
  NUM_TIENDA,
  F_VENTA,
  UUID,
  ROW_NUMBER() OVER (
                     PARTITION BY
  ID_PROCESO,
  NUM_TIENDA,
  F_VENTA,
  UUID
  ORDER BY ID_PROCESO
  ) AS DUPLICADO
  FROM [dbo].[FACTURACION_GLOBAL_CAB]
) 
 --SELECT * FROM  C
 DELETE C 
 WHERE DUPLICADO > 1;
 
 
  WITH C AS
 (
  SELECT 
  ID_PROCESO,
  NUM_TRX,
  TRX_RELACIONADA,
  ROW_NUMBER() OVER (
                     PARTITION BY
  ID_PROCESO,
  NUM_TRX,
  TRX_RELACIONADA
  ORDER BY ID_PROCESO) AS DUPLICADO
  FROM [dbo].[FACTURACION_GLOBAL_DET]
 )
 --SELECT * FROM  C
 DELETE C 
 WHERE DUPLICADO > 1;
 

  WITH C AS
 (
  SELECT 
  FACTURA_ID,
  ESTATUS,
  SERIE,
  FOLIO,
  RFC_EMISOR,
  RFC_RECEPTOR,
  FECHA,
  SUBTOTAL,
  TOTAL,
  UUID,
  REGION,
  ROW_NUMBER() OVER (
                     PARTITION BY
  FACTURA_ID,
  ESTATUS,
  SERIE,
  FOLIO,
  RFC_EMISOR,
  RFC_RECEPTOR,
  FECHA,
  SUBTOTAL,
  TOTAL,
  UUID,	
  REGION
  ORDER BY REGION) AS DUPLICADO
  FROM [dbo].[TIMBRADO_PAC_DETECNO] 
 )
 --SELECT * FROM  C
 DELETE C 
 WHERE DUPLICADO > 1;
 

 DELETE 
 --SELECT *
 FROM [dbo].[TIMBRADO_PAC_DETECNO] 
 WHERE ESTATUS not in ('CFD Valido','Cancelacion Exitosa');
 
 DELETE A
 --SELECT *
 FROM [dbo].[TIMBRADO_PAC_DETECNO] A
 WHERE EXISTS (
   SELECT 1 FROM [dbo].[FACTURA_CANCELADA] B
   WHERE A.UUID = B.UUID
 );
 

 DELETE 
 --SELECT *
 FROM [dbo].[TIMBRADO_PAC_DETECNO_GLOBAL] 
 WHERE ESTATUS not in ('CFD Valido','Cancelacion Exitosa');

 DELETE A
 --SELECT *
 FROM [dbo].[TIMBRADO_PAC_DETECNO_GLOBAL] A
 WHERE EXISTS (
   SELECT 1 FROM [dbo].[FACTURA_CANCELADA_GLOBAL] B
   WHERE A.UUID = B.UUID
 );

 
 -- Envia a null todos los articulos para colocar el canal de linio
 UPDATE VENTA_DET SET CANAL_LINIO = NULL;

 -- Coloca el numero de OC Linio
 UPDATE VENTA_DET SET CANAL_LINIO=SUBSTRING(NUM_DOC_CANAL,4,LEN(NUM_DOC_CANAL)) 
 WHERE NUM_DOC_CANAL LIKE '26%'; 


SELECT 
VEN.TICKET,	
VEN.FECHA_TICKET,	
VEN.TIENDA,	
VEN.CAJA,	
TRANSACCION,	
TIPO,	
TOTAL,	
SUBTOTAL,	
REDONDEO,	
TICKET_ORIGEN,	
VEN.FECHA_ENLACE,	
DET.NUM_DOC_CANAL,
DET.CANAL_LINIO,
'                                        ' UUID_GLOBAL,
'                                        ' FECHA_TIMBRADO_GLOBAL,
CONVERT(NUMERIC(18,2),'00000000000000000.00') TOTAL_GLOBAL,
CONVERT(NUMERIC(18,2),'00000000000000000.00') SUBTOTAL_GLOBAL,
0 REPETICION_GLOBAL,

'                                        ' UUID_CLIENTE,
'                                        ' FECHA_TIMBRADO_CLIENTE,
CONVERT(NUMERIC(18,2),'00000000000000000.00') TOTAL_CLIENTE,
CONVERT(NUMERIC(18,2),'00000000000000000.00') SUBTOTAL_CLIENTE,
0 REPETICION_CLIENTE,


'                                        ' UUID_FAC_NC_GLOBAL,
'                                        ' FECHA_TIMBRADO_FAC_NC_GLOBAL,
CONVERT(NUMERIC(18,2),'00000000000000000.00') TOTAL_FAC_NC_GLOBAL,
CONVERT(NUMERIC(18,2),'00000000000000000.00') SUBTOTAL_FAC_NC_GLOBAL,
0 REPETICION_FAC_NC_GLOBAL,

'                                        ' UUID_NC_GLOBAL,
'                                        ' FECHA_TIMBRADO_NC_GLOBAL,
CONVERT(NUMERIC(18,2),'00000000000000000.00') TOTAL_NC_GLOBAL,
CONVERT(NUMERIC(18,2),'00000000000000000.00') SUBTOTAL_NC_GLOBAL,
0 REPETICION_NC_GLOBAL,


'                                        ' UUID_NC_CLIENTE,
'                                        ' FECHA_TIMBRADO_NC_CLIENTE,
CONVERT(NUMERIC(18,2),'00000000000000000.00') TOTAL_NC_CLIENTE,
CONVERT(NUMERIC(18,2),'00000000000000000.00') SUBTOTAL_NC_CLIENTE,
0 REPETICION_NC_CLIENTE,

0 FACTURA_CLIENTE_ID,
0 FACTURA_CLIENTE_NC_ID,
0 PAC,
0 FACTURA_INHOUSE_ID,
'                                        ' UUID_IN_HOUSE,
'                                        ' UUID_LINIO,
'                                        ' UUID_RELACIONADO_GLOBAL,
'                                        ' UUID_RELACIONADO_CLIENTE,
0 FACTURA_ID_RELACIONADA,
GETDATE() FECHA_PROCESO
INTO #RELACION_VENTA_FACTURACION_TMP
-- SELECT  *
FROM [dbo].[VENTA_CAB] VEN
LEFT JOIN VENTA_DET DET
ON VEN.TICKET = DET.TICKET
AND VEN.FECHA_TICKET = DET.FECHA_TICKET
WHERE VEN.FECHA_TICKET BETWEEN @V_FECHA_INICIO AND @V_FECHA_FINAL
AND ABS(VEN.SUBTOTAL)>0;

CREATE CLUSTERED  INDEX IX_INDEX_TEMP_FAC_VENTA ON #RELACION_VENTA_FACTURACION_TMP (TICKET);
CREATE NONCLUSTERED  INDEX IX_INDEX_TEMP_FAC_VENTA_LINIO ON #RELACION_VENTA_FACTURACION_TMP (TIENDA,FECHA_TICKET);
--CREATE NONCLUSTERED  INDEX IX_INDEX_TEMP_FAC_VENTA_LINIO ON #RELACION_VENTA_FACTURACION_TMP (TIENDA,FECHA_TICKET);

UPDATE #RELACION_VENTA_FACTURACION_TMP
SET #RELACION_VENTA_FACTURACION_TMP.NUM_DOC_CANAL = VEN_DET.NUM_DOC_CANAL,
    #RELACION_VENTA_FACTURACION_TMP.CANAL_LINIO   = VEN_DET.CANAL_LINIO
FROM #RELACION_VENTA_FACTURACION_TMP VEN
INNER JOIN [dbo].[VENTA_DET] VEN_DET
ON VEN.TICKET = VEN_DET.TICKET

SELECT [REGION],UUID,FACTURA_ID,SERIE,FOLIO,RFC_RECEPTOR,RECEPTOR,FECHA,SUBTOTAL,TOTAL
INTO #TIMBRADO_PAC_DETECNO_TMP
FROM [dbo].[TIMBRADO_PAC_DETECNO];

SELECT [REGION],COUNT(1) CONTADOR
INTO #TIMBRADO_PAC_DETECNO_AGR_TMP
FROM [dbo].[TIMBRADO_PAC_DETECNO]
GROUP BY [REGION];

UPDATE #RELACION_VENTA_FACTURACION_TMP
SET #RELACION_VENTA_FACTURACION_TMP.UUID_CLIENTE =LTRIM(RTRIM(FAC_CLIENTE.UUID)),
    #RELACION_VENTA_FACTURACION_TMP.FECHA_TIMBRADO_CLIENTE = FAC_CLIENTE.FECHA,
	#RELACION_VENTA_FACTURACION_TMP.SUBTOTAL_CLIENTE       = CONVERT(NUMERIC(18,2),FAC_CLIENTE.SUBTOTAL),
    #RELACION_VENTA_FACTURACION_TMP.TOTAL_CLIENTE          = CONVERT(NUMERIC(18,2),FAC_CLIENTE.TOTAL),
	#RELACION_VENTA_FACTURACION_TMP.FACTURA_CLIENTE_ID             = FAC_CLIENTE.FACTURA_ID,
	#RELACION_VENTA_FACTURACION_TMP.PAC = 1
FROM #RELACION_VENTA_FACTURACION_TMP VEN
INNER JOIN #TIMBRADO_PAC_DETECNO_TMP FAC_CLIENTE
ON VEN.TICKET = FAC_CLIENTE.REGION
WHERE VEN.TIPO=1;

UPDATE #RELACION_VENTA_FACTURACION_TMP
SET #RELACION_VENTA_FACTURACION_TMP.REPETICION_CLIENTE = FAC_CLIENTE.CONTADOR
FROM #RELACION_VENTA_FACTURACION_TMP VEN
INNER JOIN #TIMBRADO_PAC_DETECNO_AGR_TMP FAC_CLIENTE
ON FAC_CLIENTE.REGION = VEN.TICKET
WHERE VEN.TIPO =1;

UPDATE #RELACION_VENTA_FACTURACION_TMP
SET #RELACION_VENTA_FACTURACION_TMP.UUID_NC_CLIENTE           = LTRIM(RTRIM(FAC_CLIENTE.UUID)),
    #RELACION_VENTA_FACTURACION_TMP.FECHA_TIMBRADO_NC_CLIENTE = FAC_CLIENTE.FECHA,
	#RELACION_VENTA_FACTURACION_TMP.SUBTOTAL_NC_CLIENTE       = CONVERT(NUMERIC(18,2),FAC_CLIENTE.SUBTOTAL),
    #RELACION_VENTA_FACTURACION_TMP.TOTAL_NC_CLIENTE          = CONVERT(NUMERIC(18,2),FAC_CLIENTE.TOTAL),
	#RELACION_VENTA_FACTURACION_TMP.FACTURA_CLIENTE_NC_ID     = FAC_CLIENTE.FACTURA_ID,
	#RELACION_VENTA_FACTURACION_TMP.PAC = 1
FROM #RELACION_VENTA_FACTURACION_TMP VEN
INNER JOIN #TIMBRADO_PAC_DETECNO_TMP FAC_CLIENTE
ON FAC_CLIENTE.REGION = VEN.TICKET
WHERE VEN.TIPO IN (9,10);

UPDATE #RELACION_VENTA_FACTURACION_TMP
SET #RELACION_VENTA_FACTURACION_TMP.REPETICION_NC_CLIENTE = FAC_CLIENTE.CONTADOR
FROM #RELACION_VENTA_FACTURACION_TMP VEN
INNER JOIN #TIMBRADO_PAC_DETECNO_AGR_TMP FAC_CLIENTE
ON FAC_CLIENTE.REGION = VEN.TICKET
WHERE VEN.TIPO IN (9,10);

-- Actualiza el uuid de la nota de credito relacionado a una factura
UPDATE #RELACION_VENTA_FACTURACION_TMP
SET    #RELACION_VENTA_FACTURACION_TMP.UUID_RELACIONADO_CLIENTE  = ISNULL((SELECT TOP 1 UUID FROM #TIMBRADO_PAC_DETECNO_TMP WHERE REGION = VEN.TICKET_ORIGEN),''),
       #RELACION_VENTA_FACTURACION_TMP.FACTURA_ID_RELACIONADA  = ISNULL((SELECT TOP 1 FACTURA_ID FROM #TIMBRADO_PAC_DETECNO_TMP WHERE REGION = VEN.TICKET_ORIGEN),'')
FROM #RELACION_VENTA_FACTURACION_TMP VEN
WHERE VEN.TIPO IN (9,10);

SELECT 
CAB.UUID,
CAB.F_INI_PROCESO,
CAB.F_FIN_PROCESO,
CAB.NUM_TIENDA,
CAB.TIPO_FACTURA,
CAB.SERIE,
CAB.FOLIO,
CAB.SUBTOTAL,
CAB.TOTAL,
CAB.TIPO_OPERACION,
CAB.F_VENTA,
CAB.F_TIMBRADO,
DET.NUM_TRX,
DET.TRX_RELACIONADA,
COUNT(1) CONTADOR
INTO #FACTURACION_GLOBAL_TMP
FROM [dbo].[FACTURACION_GLOBAL_CAB] CAB
INNER JOIN [dbo].[FACTURACION_GLOBAL_DET] DET
ON CAB.ID_PROCESO = DET.ID_PROCESO
WHERE CAB.UUID IS NOT NULL
AND CAB.F_VENTA BETWEEN @V_FECHA_INICIO AND @V_FECHA_FINAL
GROUP BY CAB.UUID,
CAB.F_INI_PROCESO,
CAB.F_FIN_PROCESO,
CAB.NUM_TIENDA,
CAB.TIPO_FACTURA,
CAB.SERIE,
CAB.FOLIO,
CAB.SUBTOTAL,
CAB.TOTAL,
CAB.TIPO_OPERACION,
CAB.F_VENTA,
CAB.F_TIMBRADO,
DET.NUM_TRX,
DET.TRX_RELACIONADA;

SELECT CONVERT(NUMERIC,SUBSTRING(SERIE,PATINDEX('%[0-9]%', SERIE),4)) TIENDA,REGION F_VENTA,Extra7 TIPO_OPERACION,Total,SubTotal,COUNT(DISTINCT UUID) NUMERO_REGISTRO
INTO #FACTURACION_GLOBAL_AGR_TMP
FROM TIMBRADO_PAC_DETECNO_GLOBAL
WHERE VERSION IN ('4.0')
GROUP BY CONVERT(NUMERIC,SUBSTRING(SERIE,PATINDEX('%[0-9]%', SERIE),4)),REGION,Extra7,Total,SubTotal
HAVING COUNT(DISTINCT UUID) > 1;

/*
// Creacion de indices para optimizar la consulta 
// en la actualización
// 
--CREATE NONCLUSTERED INDEX ix_tempRelacionVentaFac ON #RELACION_VENTA_FACTURACION_TMP (TICKET);
--CREATE NONCLUSTERED INDEX ix_tempFacturacionGlo ON #FACTURACION_GLOBAL_TMP (NUM_TRX);
--CREATE NONCLUSTERED INDEX ix_tempFacturacionGloAgr ON #FACTURACION_GLOBAL_AGR_TMP (F_VENTA,TIENDA);
*/

UPDATE #RELACION_VENTA_FACTURACION_TMP
SET #RELACION_VENTA_FACTURACION_TMP.UUID_NC_GLOBAL =FAC_GLOBAL.UUID,
    #RELACION_VENTA_FACTURACION_TMP.FECHA_TIMBRADO_NC_GLOBAL = FAC_GLOBAL.F_TIMBRADO,
	#RELACION_VENTA_FACTURACION_TMP.SUBTOTAL_NC_GLOBAL = FAC_GLOBAL.SUBTOTAL,
	#RELACION_VENTA_FACTURACION_TMP.TOTAL_NC_GLOBAL = FAC_GLOBAL.TOTAL,
	#RELACION_VENTA_FACTURACION_TMP.PAC = 1,
	#RELACION_VENTA_FACTURACION_TMP.UUID_RELACIONADO_GLOBAL  = ISNULL((SELECT TOP 1 UUID FROM #FACTURACION_GLOBAL_TMP WHERE NUM_TRX = VEN.TICKET_ORIGEN AND TIPO_OPERACION='V'),'')
FROM #RELACION_VENTA_FACTURACION_TMP VEN
INNER JOIN #FACTURACION_GLOBAL_TMP FAC_GLOBAL
ON FAC_GLOBAL.NUM_TRX = VEN.TICKET
WHERE FAC_GLOBAL.TIPO_OPERACION='D';


-- Relaciona el uuid de la factura global
UPDATE #RELACION_VENTA_FACTURACION_TMP
SET 	#RELACION_VENTA_FACTURACION_TMP.UUID_RELACIONADO_GLOBAL  = ISNULL((SELECT TOP 1 UUID FROM #FACTURACION_GLOBAL_TMP WHERE NUM_TRX = VEN.TICKET_ORIGEN AND TIPO_OPERACION='V' ),'')
FROM #RELACION_VENTA_FACTURACION_TMP VEN
WHERE VEN.TIPO IN (9,10);

-- Registro de notas de credito generadas por una factura de un cliente
UPDATE #RELACION_VENTA_FACTURACION_TMP
SET #RELACION_VENTA_FACTURACION_TMP.[UUID_FAC_NC_GLOBAL] =FAC_GLOBAL.UUID,
    #RELACION_VENTA_FACTURACION_TMP.FECHA_TIMBRADO_FAC_NC_GLOBAL = FAC_GLOBAL.F_TIMBRADO,
	#RELACION_VENTA_FACTURACION_TMP.SUBTOTAL_FAC_NC_GLOBAL = FAC_GLOBAL.SUBTOTAL,
	#RELACION_VENTA_FACTURACION_TMP.TOTAL_FAC_NC_GLOBAL = FAC_GLOBAL.TOTAL,
	#RELACION_VENTA_FACTURACION_TMP.PAC = 1
FROM #RELACION_VENTA_FACTURACION_TMP VEN
INNER JOIN #FACTURACION_GLOBAL_TMP FAC_GLOBAL
ON FAC_GLOBAL.NUM_TRX = VEN.TICKET
WHERE FAC_GLOBAL.TIPO_OPERACION='FD';

UPDATE #RELACION_VENTA_FACTURACION_TMP
SET #RELACION_VENTA_FACTURACION_TMP.REPETICION_FAC_NC_GLOBAL =FAC_GLOBAL.NUMERO_REGISTRO
FROM #RELACION_VENTA_FACTURACION_TMP VEN
INNER JOIN #FACTURACION_GLOBAL_AGR_TMP FAC_GLOBAL
ON CONVERT(DATE,FAC_GLOBAL.F_VENTA,103) = VEN.FECHA_TICKET
AND FAC_GLOBAL.TIENDA = VEN.TIENDA
WHERE FAC_GLOBAL.TIPO_OPERACION='FD';

-- Relacionada el uuid de las facturas de un ticket
UPDATE #RELACION_VENTA_FACTURACION_TMP
SET #RELACION_VENTA_FACTURACION_TMP.UUID_GLOBAL =FAC_GLOBAL.UUID,
    #RELACION_VENTA_FACTURACION_TMP.FECHA_TIMBRADO_GLOBAL = FAC_GLOBAL.F_TIMBRADO,
	#RELACION_VENTA_FACTURACION_TMP.SUBTOTAL_GLOBAL = FAC_GLOBAL.SUBTOTAL,
	#RELACION_VENTA_FACTURACION_TMP.TOTAL_GLOBAL = FAC_GLOBAL.TOTAL,
	#RELACION_VENTA_FACTURACION_TMP.PAC = 1
FROM #RELACION_VENTA_FACTURACION_TMP VEN
INNER JOIN #FACTURACION_GLOBAL_TMP FAC_GLOBAL
ON FAC_GLOBAL.NUM_TRX = VEN.TICKET
WHERE FAC_GLOBAL.TIPO_OPERACION='V';

UPDATE #RELACION_VENTA_FACTURACION_TMP
SET #RELACION_VENTA_FACTURACION_TMP.REPETICION_GLOBAL = FAC_GLOBAL.NUMERO_REGISTRO
FROM #RELACION_VENTA_FACTURACION_TMP VEN
INNER JOIN #FACTURACION_GLOBAL_AGR_TMP FAC_GLOBAL
ON FAC_GLOBAL.TIENDA = VEN.TIENDA
AND CONVERT(DATE,FAC_GLOBAL.F_VENTA,103) = VEN.FECHA_TICKET
WHERE FAC_GLOBAL.TIPO_OPERACION='V';

UPDATE #RELACION_VENTA_FACTURACION_TMP
SET #RELACION_VENTA_FACTURACION_TMP.FACTURA_INHOUSE_ID = FAC_INHOUSE.FACTURA_ID,
    #RELACION_VENTA_FACTURACION_TMP.UUID_IN_HOUSE = FAC_INHOUSE.UUID
FROM #RELACION_VENTA_FACTURACION_TMP VEN
INNER JOIN [dbo].[TIMBRADO_INHOUSE] FAC_INHOUSE
ON VEN.TICKET = FAC_INHOUSE.TICKET;

UPDATE #RELACION_VENTA_FACTURACION_TMP
SET #RELACION_VENTA_FACTURACION_TMP.UUID_LINIO =FAC_LINIO.UUID,
	#RELACION_VENTA_FACTURACION_TMP.PAC = 2
FROM #RELACION_VENTA_FACTURACION_TMP VEN
INNER JOIN [TIMBRADO_PAC_LINIO] FAC_LINIO
ON FAC_LINIO.OC_LINIO = SUBSTRING(VEN.NUM_DOC_CANAL, 4, 9);

WITH C AS
 (
    SELECT 
			TICKET,	
			FECHA_TICKET,
			TIENDA,	
			CAJA,	
			TRANSACCION,
			TIPO,	
			TOTAL,	
			SUBTOTAL,	
			REDONDEO,	
			TICKET_ORIGEN,	
			FECHA_ENLACE,	
			NUM_DOC_CANAL,	
			CANAL_LINIO,
			UUID_GLOBAL,	
			FECHA_TIMBRADO_GLOBAL,	
			TOTAL_GLOBAL,	
			SUBTOTAL_GLOBAL,	
			REPETICION_GLOBAL,	
			UUID_CLIENTE,	
			FECHA_TIMBRADO_CLIENTE,	
			TOTAL_CLIENTE,	
			SUBTOTAL_CLIENTE,	
			REPETICION_CLIENTE,	
			UUID_FAC_NC_GLOBAL,	
			FECHA_TIMBRADO_FAC_NC_GLOBAL,	
			TOTAL_FAC_NC_GLOBAL,	
			SUBTOTAL_FAC_NC_GLOBAL,	
			REPETICION_FAC_NC_GLOBAL,	
			UUID_NC_GLOBAL,	
			FECHA_TIMBRADO_NC_GLOBAL,	
			TOTAL_NC_GLOBAL,	
			SUBTOTAL_NC_GLOBAL,	
			REPETICION_NC_GLOBAL,	
			UUID_NC_CLIENTE,	
			FECHA_TIMBRADO_NC_CLIENTE,	
			TOTAL_NC_CLIENTE,	
			SUBTOTAL_NC_CLIENTE,	
			REPETICION_NC_CLIENTE,	
			FACTURA_CLIENTE_ID,	
			FACTURA_CLIENTE_NC_ID,
			PAC,	
			FACTURA_INHOUSE_ID,	
			UUID_IN_HOUSE,	
			UUID_LINIO,	
			UUID_RELACIONADO_GLOBAL,	
			UUID_RELACIONADO_CLIENTE,	
			FACTURA_ID_RELACIONADA,
            ROW_NUMBER() OVER ( PARTITION BY  
				TICKET,	
				FECHA_TICKET,
				TIENDA,	
				CAJA,	
				TRANSACCION,
				TIPO,	
				TOTAL,	
				SUBTOTAL,	
				REDONDEO,	
				TICKET_ORIGEN,	
				FECHA_ENLACE,	
				NUM_DOC_CANAL,	
				CANAL_LINIO,
				UUID_GLOBAL,	
				FECHA_TIMBRADO_GLOBAL,	
				TOTAL_GLOBAL,	
				SUBTOTAL_GLOBAL,	
				REPETICION_GLOBAL,	
				UUID_CLIENTE,	
				FECHA_TIMBRADO_CLIENTE,	
				TOTAL_CLIENTE,	
				SUBTOTAL_CLIENTE,	
				REPETICION_CLIENTE,	
				UUID_FAC_NC_GLOBAL,	
				FECHA_TIMBRADO_FAC_NC_GLOBAL,	
				TOTAL_FAC_NC_GLOBAL,	
				SUBTOTAL_FAC_NC_GLOBAL,	
				REPETICION_FAC_NC_GLOBAL,	
				UUID_NC_GLOBAL,	
				FECHA_TIMBRADO_NC_GLOBAL,	
				TOTAL_NC_GLOBAL,	
				SUBTOTAL_NC_GLOBAL,	
				REPETICION_NC_GLOBAL,	
				UUID_NC_CLIENTE,	
				FECHA_TIMBRADO_NC_CLIENTE,	
				TOTAL_NC_CLIENTE,	
				SUBTOTAL_NC_CLIENTE,	
				REPETICION_NC_CLIENTE,	
				FACTURA_CLIENTE_ID,	
				FACTURA_CLIENTE_NC_ID,
				PAC,	
				FACTURA_INHOUSE_ID,	
				UUID_IN_HOUSE,	
				UUID_LINIO,	
				UUID_RELACIONADO_GLOBAL,	
				UUID_RELACIONADO_CLIENTE,	
				FACTURA_ID_RELACIONADA           
  ORDER BY TICKET) AS DUPLICADO
  FROM #RELACION_VENTA_FACTURACION_TMP 
 )
 --SELECT * FROM  C
 DELETE C 
 WHERE DUPLICADO > 1;


TRUNCATE TABLE [dbo].[RELACION_VENTA_FACTURACION];

INSERT INTO [dbo].[RELACION_VENTA_FACTURACION]
SELECT * FROM #RELACION_VENTA_FACTURACION_TMP;

DROP TABLE #TIMBRADO_PAC_DETECNO_TMP;
DROP TABLE #RELACION_VENTA_FACTURACION_TMP;
DROP TABLE #TIMBRADO_PAC_DETECNO_AGR_TMP;
DROP TABLE #FACTURACION_GLOBAL_TMP;
DROP TABLE #FACTURACION_GLOBAL_AGR_TMP;

-- Obtiene el rango del factura Id que hace falta por sincronizar en la BD Local
exec uspRangoFactura;
-- Genera el tablero de timbrado
exec [dbo].[uspGeneraTableroTimbrado];


END;