package com.sodimac.facturacion.clientews.wcfemision40.org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.7
 * 2022-05-27T18:42:06.517-05:00
 * Generated source version: 3.4.7
 *
 */
@WebServiceClient(name = "Detecno",
                  wsdlLocation = "https://genera.emisiondetecno.mx/Sodimac/cfdiWcfEmision_Servicio_40_Sodimac_Test/Detecno.svc?wsdl",
                  targetNamespace = "http://tempuri.org/")
public class Detecno extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "Detecno");
    public final static QName WSHttpBindingIDetecno = new QName("http://tempuri.org/", "WSHttpBinding_IDetecno");
    static {
        URL url = null;
        try {
            url = new URL("https://genera.emisiondetecno.mx/Sodimac/cfdiWcfEmision_Servicio_40_Sodimac_Test/Detecno.svc?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Detecno.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://genera.emisiondetecno.mx/Sodimac/cfdiWcfEmision_Servicio_40_Sodimac_Test/Detecno.svc?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Detecno(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Detecno(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Detecno() {
        super(WSDL_LOCATION, SERVICE);
    }

    public Detecno(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Detecno(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Detecno(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IDetecno
     */
    @WebEndpoint(name = "WSHttpBinding_IDetecno")
    public IDetecno getWSHttpBindingIDetecno() {
        return super.getPort(WSHttpBindingIDetecno, IDetecno.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDetecno
     */
    @WebEndpoint(name = "WSHttpBinding_IDetecno")
    public IDetecno getWSHttpBindingIDetecno(WebServiceFeature... features) {
        return super.getPort(WSHttpBindingIDetecno, IDetecno.class, features);
    }

}
