package com.sodimac.facturacion.clientews.wcfemision40.org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.7
 * 2022-05-27T18:42:06.500-05:00
 * Generated source version: 3.4.7
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IDetecno")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, com.sodimac.facturacion.clientews.wcfemision40.org.datacontract.schemas._2004._07.cfdiwcfemisionservicio40_sodimac.ObjectFactory.class, ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class})
public interface IDetecno {

    @WebMethod(operationName = "Prueba", action = "http://tempuri.org/IDetecno/Prueba")
    @Action(input = "http://tempuri.org/IDetecno/Prueba", output = "http://tempuri.org/IDetecno/PruebaResponse")
    @RequestWrapper(localName = "Prueba", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Prueba")
    @ResponseWrapper(localName = "PruebaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PruebaResponse")
    @WebResult(name = "PruebaResult", targetNamespace = "http://tempuri.org/")
    public com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring prueba(

        @WebParam(name = "valor", targetNamespace = "http://tempuri.org/")
        java.lang.String valor
    );

    @WebMethod(operationName = "ComprobanteBuscar40", action = "http://tempuri.org/IDetecno/ComprobanteBuscar40")
    @Action(input = "http://tempuri.org/IDetecno/ComprobanteBuscar40", output = "http://tempuri.org/IDetecno/ComprobanteBuscar40Response")
    @RequestWrapper(localName = "ComprobanteBuscar40", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ComprobanteBuscar40")
    @ResponseWrapper(localName = "ComprobanteBuscar40Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ComprobanteBuscar40Response")
    @WebResult(name = "ComprobanteBuscar40Result", targetNamespace = "http://tempuri.org/")
    public com.sodimac.facturacion.clientews.wcfemision40.org.datacontract.schemas._2004._07.cfdiwcfemisionservicio40_sodimac.RespuestaXml comprobanteBuscar40(

        @WebParam(name = "licencia", targetNamespace = "http://tempuri.org/")
        java.lang.String licencia,
        @WebParam(name = "facturaId", targetNamespace = "http://tempuri.org/")
        java.lang.String facturaId
    );

    @WebMethod(operationName = "ComprobanteGenerar40", action = "http://tempuri.org/IDetecno/ComprobanteGenerar40")
    @Action(input = "http://tempuri.org/IDetecno/ComprobanteGenerar40", output = "http://tempuri.org/IDetecno/ComprobanteGenerar40Response")
    @RequestWrapper(localName = "ComprobanteGenerar40", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ComprobanteGenerar40")
    @ResponseWrapper(localName = "ComprobanteGenerar40Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ComprobanteGenerar40Response")
    @WebResult(name = "ComprobanteGenerar40Result", targetNamespace = "http://tempuri.org/")
    public com.sodimac.facturacion.clientews.wcfemision40.org.datacontract.schemas._2004._07.cfdiwcfemisionservicio40_sodimac.Resultado comprobanteGenerar40(

        @WebParam(name = "licencia", targetNamespace = "http://tempuri.org/")
        java.lang.String licencia,
        @WebParam(name = "cerBytes", targetNamespace = "http://tempuri.org/")
        java.lang.String cerBytes,
        @WebParam(name = "keyBytes", targetNamespace = "http://tempuri.org/")
        java.lang.String keyBytes,
        @WebParam(name = "passBytes", targetNamespace = "http://tempuri.org/")
        java.lang.String passBytes,
        @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
        java.lang.String xml
    );

    @WebMethod(operationName = "Comprobante_BuscarPdf40", action = "http://tempuri.org/IDetecno/Comprobante_BuscarPdf40")
    @Action(input = "http://tempuri.org/IDetecno/Comprobante_BuscarPdf40", output = "http://tempuri.org/IDetecno/Comprobante_BuscarPdf40Response")
    @RequestWrapper(localName = "Comprobante_BuscarPdf40", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ComprobanteBuscarPdf40")
    @ResponseWrapper(localName = "Comprobante_BuscarPdf40Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ComprobanteBuscarPdf40Response")
    @WebResult(name = "Comprobante_BuscarPdf40Result", targetNamespace = "http://tempuri.org/")
    public com.sodimac.facturacion.clientews.wcfemision40.org.datacontract.schemas._2004._07.cfdiwcfemisionservicio40_sodimac.Resultado comprobanteBuscarPdf40(

        @WebParam(name = "licencia", targetNamespace = "http://tempuri.org/")
        java.lang.String licencia,
        @WebParam(name = "facturaId", targetNamespace = "http://tempuri.org/")
        java.lang.String facturaId
    );

    @WebMethod(operationName = "ComprobanteCancelar40", action = "http://tempuri.org/IDetecno/ComprobanteCancelar40")
    @Action(input = "http://tempuri.org/IDetecno/ComprobanteCancelar40", output = "http://tempuri.org/IDetecno/ComprobanteCancelar40Response")
    @RequestWrapper(localName = "ComprobanteCancelar40", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ComprobanteCancelar40")
    @ResponseWrapper(localName = "ComprobanteCancelar40Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ComprobanteCancelar40Response")
    @WebResult(name = "ComprobanteCancelar40Result", targetNamespace = "http://tempuri.org/")
    public com.sodimac.facturacion.clientews.wcfemision40.org.datacontract.schemas._2004._07.cfdiwcfemisionservicio40_sodimac.Resultado comprobanteCancelar40(

        @WebParam(name = "licencia", targetNamespace = "http://tempuri.org/")
        java.lang.String licencia,
        @WebParam(name = "facturaId", targetNamespace = "http://tempuri.org/")
        java.lang.String facturaId,
        @WebParam(name = "motivoCancelacion", targetNamespace = "http://tempuri.org/")
        java.lang.String motivoCancelacion,
        @WebParam(name = "FolioSustitucion", targetNamespace = "http://tempuri.org/")
        java.lang.String folioSustitucion
    );
}
