
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.sodimac.facturacion.clientews.wcfemision40.org.tempuri;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.4.7
 * 2022-05-27T18:42:06.484-05:00
 * Generated source version: 3.4.7
 *
 */

@javax.jws.WebService(
                      serviceName = "Detecno",
                      portName = "WSHttpBinding_IDetecno",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "https://genera.emisiondetecno.mx/Sodimac/cfdiWcfEmision_Servicio_40_Sodimac_Test/Detecno.svc?wsdl",
                      endpointInterface = "org.tempuri.IDetecno")

public class WSHttpBinding_IDetecnoImpl implements IDetecno {

    private static final Logger LOG = Logger.getLogger(WSHttpBinding_IDetecnoImpl.class.getName());

    /* (non-Javadoc)
     * @see org.tempuri.IDetecno#prueba(java.lang.String valor)*
     */
    public com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring prueba(java.lang.String valor) {
        LOG.info("Executing operation prueba");
        System.out.println(valor);
        try {
            com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IDetecno#comprobanteBuscar40(java.lang.String licencia, java.lang.String facturaId)*
     */
    public com.sodimac.facturacion.clientews.wcfemision40.org.datacontract.schemas._2004._07.cfdiwcfemisionservicio40_sodimac.RespuestaXml comprobanteBuscar40(java.lang.String licencia, java.lang.String facturaId) {
        LOG.info("Executing operation comprobanteBuscar40");
        System.out.println(licencia);
        System.out.println(facturaId);
        try {
        	com.sodimac.facturacion.clientews.wcfemision40.org.datacontract.schemas._2004._07.cfdiwcfemisionservicio40_sodimac.RespuestaXml _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IDetecno#comprobanteGenerar40(java.lang.String licencia, java.lang.String cerBytes, java.lang.String keyBytes, java.lang.String passBytes, java.lang.String xml)*
     */
    public com.sodimac.facturacion.clientews.wcfemision40.org.datacontract.schemas._2004._07.cfdiwcfemisionservicio40_sodimac.Resultado comprobanteGenerar40(java.lang.String licencia, java.lang.String cerBytes, java.lang.String keyBytes, java.lang.String passBytes, java.lang.String xml) {
        LOG.info("Executing operation comprobanteGenerar40");
        System.out.println(licencia);
        System.out.println(cerBytes);
        System.out.println(keyBytes);
        System.out.println(passBytes);
        System.out.println(xml);
        try {
        	com.sodimac.facturacion.clientews.wcfemision40.org.datacontract.schemas._2004._07.cfdiwcfemisionservicio40_sodimac.Resultado _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IDetecno#comprobanteBuscarPdf40(java.lang.String licencia, java.lang.String facturaId)*
     */
    public com.sodimac.facturacion.clientews.wcfemision40.org.datacontract.schemas._2004._07.cfdiwcfemisionservicio40_sodimac.Resultado comprobanteBuscarPdf40(java.lang.String licencia, java.lang.String facturaId) {
        LOG.info("Executing operation comprobanteBuscarPdf40");
        System.out.println(licencia);
        System.out.println(facturaId);
        try {
        	com.sodimac.facturacion.clientews.wcfemision40.org.datacontract.schemas._2004._07.cfdiwcfemisionservicio40_sodimac.Resultado _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tempuri.IDetecno#comprobanteCancelar40(java.lang.String licencia, java.lang.String facturaId, java.lang.String motivoCancelacion, java.lang.String folioSustitucion)*
     */
    public com.sodimac.facturacion.clientews.wcfemision40.org.datacontract.schemas._2004._07.cfdiwcfemisionservicio40_sodimac.Resultado comprobanteCancelar40(java.lang.String licencia, java.lang.String facturaId, java.lang.String motivoCancelacion, java.lang.String folioSustitucion) {
        LOG.info("Executing operation comprobanteCancelar40");
        System.out.println(licencia);
        System.out.println(facturaId);
        System.out.println(motivoCancelacion);
        System.out.println(folioSustitucion);
        try {
        	com.sodimac.facturacion.clientews.wcfemision40.org.datacontract.schemas._2004._07.cfdiwcfemisionservicio40_sodimac.Resultado _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
