apiVersion: batch/v1
kind: CronJob
metadata:
  name: three-way-match-batch
spec:
  suspend: false
  schedule: "0 9 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: three-way-match-batch
              image: gcr.io/fal-corp-mrch-foundational-uat/falabella-stores-and-merchandise/app03022-mrch.backend.somx.finanzas-api:${CI_JOB_ID}-uat
              envFrom:
                - configMapRef:
                    name: ${PROJECT_NAME}-configmap
                - secretRef:
                    name: ${PROJECT_NAME}-secret
