apiVersion: apps/v1
kind: Deployment

metadata:
  name: ${PROJECT_NAME}

spec:
  template:
    spec:
      serviceAccountName: fbc-workload-identity
      automountServiceAccountToken: false

      containers:
        - name: ${PROJECT_NAME}

          resources:
            limits:
              memory: "400Mi"
            requests:
              cpu: "50m"
              memory: "200Mi"
