INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1000,1,'Guía de embarque pendiente de enviar al portal FBC'),
	 (1000,2,'Shipping guide pending to send to FBC portal'),
	 (1000,3,'Guia de embarque pendente de envio ao portal FBC'),
	 (1001,1,'Guía de embarque enviada al portal de proveedores FBC sin OC'),
	 (1001,2,'Shipping guide sent to FBC supplier portal without PO'),
	 (1001,3,'Guia de embarque enviada ao portal de fornecedores FBC sem OC'),
	 (1002,1,'Guía de embarque enviada al portal de proveedores FBC con OC'),
	 (1002,2,'Shipping guide sent to FBC supplier portal with PO'),
	 (1002,3,'Guia de embarque enviada ao portal de fornecedores FBC com OC'),
	 (1003,1,'Guía de embarque sin OC recibida en el portal FBC');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1003,2,'Shipping guide without PO received in FBC portal'),
	 (1003,3,'Guia de embarque sem OC recebida no portal FBC'),
	 (1004,1,'Guía de embarque con OC recibida en el portal de FBC'),
	 (1004,2,'Shipping guide with PO received in FBC portal'),
	 (1004,3,'Guia de embarque com OC recebida no portal FBC'),
	 (1005,1,'Guía de embarque relacionado con una factura'),
	 (1005,2,'Shipping guide related to an invoice'),
	 (1005,3,'Guia de embarque relacionada com uma fatura'),
	 (1006,1,'Guía de embarque enviada a contabilizar'),
	 (1006,2,'Shipping guide sent for accounting');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1006,3,'Guia de embarque enviada para contabilização'),
	 (1007,1,'Guía de embarque contabilizada'),
	 (1007,2,'Shipping guide accounted'),
	 (1007,3,'Guia de embarque contabilizada'),
	 (1008,1,'Guía de embarque rechazada en la contabilización'),
	 (1008,2,'Shipping guide rejected in accounting'),
	 (1008,3,'Guia de embarque rejeitada na contabilização'),
	 (1009,1,'Guía de embarque pagada'),
	 (1009,2,'Shipping guide paid'),
	 (1009,3,'Guia de embarque paga');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1010,1,'Guía de embarque rechazada en el portal de proveedores FBC'),
	 (1010,2,'Shipping guide rejected in FBC supplier portal'),
	 (1010,3,'Guia de embarque rejeitada no portal de fornecedores FBC'),
	 (1011,1,'Guía de embarque cancelada en el portal de proveedores FBC'),
	 (1011,2,'Shipping guide cancelled in FBC supplier portal'),
	 (1011,3,'Guia de embarque cancelada no portal de fornecedores FBC'),
	 (1012,1,'Guía de embarque registrada en el portal de proveedores FBC sin OC'),
	 (1012,2,'Shipping guide registered in FBC supplier portal without PO'),
	 (1012,3,'Guia de embarque registrada no portal de fornecedores FBC sem OC'),
	 (1013,1,'Guía de embarque registrada en el portal de proveedores FBC con OC');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1013,2,'Shipping guide registered in FBC supplier portal with PO'),
	 (1013,3,'Guia de embarque registrada no portal de fornecedores FBC com OC'),
	 (1014,1,'Guía de embarque relacionada con una OC y factura'),
	 (1014,2,'Shipping guide related to a PO and invoice'),
	 (1014,3,'Guia de embarque relacionada com uma OC e fatura'),
	 (1015,1,'Guía de embarque con OC enviada a contabilizar'),
	 (1015,2,'Shipping guide with PO sent for accounting'),
	 (1015,3,'Guia de embarque com OC enviada para contabilização'),
	 (1016,1,'Guía de embarque con OC contabilizada'),
	 (1016,2,'Shipping guide with PO accounted');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1016,3,'Guia de embarque com OC contabilizada'),
	 (1017,1,'Guía de embarque con OC rechazada en la contabilización'),
	 (1017,2,'Shipping guide with PO rejected in accounting'),
	 (1017,3,'Guia de embarque com OC rejeitada na contabilização'),
	 (1018,1,'Guía de embarque con OC pagada'),
	 (1018,2,'Shipping guide with PO paid'),
	 (1018,3,'Guia de embarque com OC paga'),
	 (1019,1,'Rechazo en la recepción de la guía de embarque'),
	 (1019,2,'Rejection in shipping guide reception'),
	 (1019,3,'Rejeição na recepção da guia de embarque');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1020,1,'Guía de embarque cancelada en el portal de proveedores FBC'),
	 (1020,2,'Shipping guide cancelled in FBC supplier portal'),
	 (1020,3,'Guia de embarque cancelada no portal de fornecedores FBC'),
	 (1021,1,'Inactivo'),
	 (1021,2,'Inactive'),
	 (1021,3,'Inativo'),
	 (1022,1,'Activo'),
	 (1022,2,'Active'),
	 (1022,3,'Ativo'),
	 (1023,1,'Borrado Lógico');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1023,2,'Soft Delete'),
	 (1023,3,'Exclusão Lógica'),
	 (1024,1,'Catálogo para gestionar los mensajes de éxito en el sistema'),
	 (1024,2,'Catalog to manage success messages in the system'),
	 (1024,3,'Catálogo para gerenciar mensagens de sucesso no sistema'),
	 (1025,1,'Catálogo para gestionar los mensajes de negocio del aplicativo'),
	 (1025,2,'Catalog to manage business messages of the application'),
	 (1025,3,'Catálogo para gerenciar mensagens de negócio do aplicativo'),
	 (1026,1,'Catálogo de los mensajes de error a nivel técnico del sistema'),
	 (1026,2,'Catalog of technical error messages of the system');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1026,3,'Catálogo de mensagens de erro técnico do sistema'),
	 (1027,1,'Catálogo de mensajes de errores de infraestructura'),
	 (1027,2,'Catalog of infrastructure error messages'),
	 (1027,3,'Catálogo de mensagens de erros de infraestrutura'),
	 (1028,1,'Catálogo de excepciones que genera el aplicativo'),
	 (1028,2,'Catalog of exceptions generated by the application'),
	 (1028,3,'Catálogo de exceções geradas pelo aplicativo'),
	 (1029,1,'Catálogo de los mensajes informativos que retorna el aplicativo'),
	 (1029,2,'Catalog of informational messages returned by the application'),
	 (1029,3,'Catálogo de mensagens informativas retornadas pelo aplicativo');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1030,1,'El registro del proveedor {0} se realizó exitosamente.'),
	 (5001,2,'Non-Profit Legal Entities'),
	 (1030,2,'Supplier {0} registration was successful.'),
	 (1030,3,'O registro do fornecedor {0} foi realizado com sucesso.'),
	 (1031,1,'El reporte se ha descargado exitosamente.'),
	 (1031,2,'The report was downloaded successfully.'),
	 (1031,3,'O relatório foi baixado com sucesso.'),
	 (1032,1,'El registro de la guía de embarque se realizó exitosamente.'),
	 (1032,2,'Shipping guide registration was successful.'),
	 (1032,3,'O registro da guia de embarque foi realizado com sucesso.');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1033,1,'La addenda de la factura no cumple con la estructura requerida. Por favor, verifica el formato y el nombre de los elementos.'),
	 (1033,2,'The invoice addenda does not meet the required structure. Please verify the format and element names.'),
	 (1033,3,'O adendo da fatura não atende à estrutura exigida. Por favor, verifique o formato e os nomes dos elementos.'),
	 (1034,1,'El RFC del receptor {0} no acepta documentos fiscales. Verifica que el RFC esté autorizado para recibir comprobantes fiscales.'),
	 (1034,2,'The receiver RFC {0} does not accept fiscal documents. Verify that the RFC is authorized to receive tax receipts.'),
	 (1034,3,'O RFC do receptor {0} não aceita documentos fiscais. Verifique se o RFC está autorizado a receber comprovantes fiscais.'),
	 (1035,1,'La guía carta porte no contiene un archivo xml y csv asociado, favor de validar.'),
	 (1035,2,'The bill of lading does not contain an associated xml and csv file, please validate.'),
	 (1035,3,'A carta porte não contém um arquivo xml e csv associado, favor validar.'),
	 (1036,1,'No fue posible registrar la guía carta porte, falta información por completar.');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1036,2,'It was not possible to register the bill of lading, missing information to complete.'),
	 (1036,3,'Não foi possível registrar a carta porte, faltam informações para completar.'),
	 (1037,1,'La guía de embarque se encuentra previamente registrada, favor de validar.'),
	 (1037,2,'The shipping guide is already registered, please validate.'),
	 (1037,3,'A guia de embarque já está registrada, favor validar.'),
	 (1038,1,'Las facturas no corresponden al complemento que desea publicar.'),
	 (1038,2,'The invoices do not correspond to the supplement you want to publish.'),
	 (1038,3,'As faturas não correspondem ao complemento que deseja publicar.'),
	 (1039,1,'Las notas de crédito no corresponden al complemento que desea publicar.'),
	 (1039,2,'The credit notes do not correspond to the supplement you want to publish.');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1039,3,'As notas de crédito não correspondem ao complemento que deseja publicar.'),
	 (1040,1,'No existe información con los criterios establecidos.'),
	 (1040,2,'No information exists with the established criteria.'),
	 (1040,3,'Não existe informação com os critérios estabelecidos.'),
	 (1041,1,'La fecha inicio no puede ser superior a la fecha final.'),
	 (1041,2,'The start date cannot be greater than the end date.'),
	 (1041,3,'A data de início não pode ser maior que a data final.'),
	 (1042,1,'Se requiere capturar por lo menos un filtro de búsqueda.'),
	 (1042,2,'At least one search filter is required.'),
	 (1042,3,'É necessário inserir pelo menos um filtro de busca.');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1043,1,'No existe información con los filtros de búsqueda capturados.'),
	 (1043,2,'No information exists with the captured search filters.'),
	 (1043,3,'Não existe informação com os filtros de busca inseridos.'),
	 (1044,1,'No es posible publicar el complemento de pago, faltan documentos fiscales por publicar.'),
	 (1044,2,'Cannot publish payment supplement, fiscal documents are missing.'),
	 (1044,3,'Não é possível publicar o complemento de pagamento, faltam documentos fiscais para publicar.'),
	 (1045,1,'Se requiere publicar el complemento de pago en formato XML.'),
	 (1045,2,'The payment supplement must be published in XML format.'),
	 (1045,3,'É necessário publicar o complemento de pagamento em formato XML.'),
	 (1046,1,'El periodo de búsqueda no puede ser superior a 6 meses, favor de validar.');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1046,2,'The search period cannot exceed 6 months, please validate.'),
	 (1046,3,'O período de busca não pode ser superior a 6 meses, favor validar.'),
	 (1047,1,'La fecha final no puede ser menor a la fecha inicio.'),
	 (1047,2,'The end date cannot be less than the start date.'),
	 (1047,3,'A data final não pode ser menor que a data de início.'),
	 (1048,1,'Se requiere publicar factura en formato XML.'),
	 (1048,2,'Invoice must be published in XML format.'),
	 (1048,3,'É necessário publicar a fatura em formato XML.'),
	 (1049,1,'Catálogo de respuestas del PAC Detecno de todas las validaciones que realiza en cada documento.'),
	 (1049,2,'Detecno PAC response catalog for all validations performed on each document.');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1049,3,'Catálogo de respostas do PAC Detecno de todas as validações realizadas em cada documento.'),
	 (1050,1,'Catálogo de respuestas de todas las validaciones que realiza en cada documento.'),
	 (1050,2,'Response catalog for all validations performed on each document.'),
	 (1050,3,'Catálogo de respostas de todas as validações realizadas em cada documento.'),
	 (1051,1,'Rechazo Comercial'),
	 (1051,2,'Commercial Rejection'),
	 (1051,3,'Rejeição Comercial'),
	 (1052,1,'Pendiente Addenda'),
	 (1052,2,'Pending Addenda'),
	 (1052,3,'Adendo Pendente');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1053,1,'Recibido Parcial'),
	 (1053,2,'Partial Received'),
	 (1053,3,'Recebido Parcial'),
	 (1054,1,'Pendiente de Contabilizar'),
	 (1054,2,'Pending Accounting'),
	 (1054,3,'Pendente de Contabilização'),
	 (1055,1,'En proceso de descarga'),
	 (1055,2,'Download in progress'),
	 (1055,3,'Em processo de download'),
	 (1056,1,'Desglose de factura');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1056,2,'Invoice breakdown'),
	 (1056,3,'Detalhamento de fatura'),
	 (1057,1,'Pendiente de envío a contabilizar'),
	 (1057,2,'Pending submission for accounting'),
	 (1057,3,'Pendente de envio para contabilização'),
	 (1058,1,'Pendiente de Pago'),
	 (1058,2,'Pending Payment'),
	 (1058,3,'Pendente de Pagamento'),
	 (1059,1,'Pagado'),
	 (1059,2,'Paid');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1059,3,'Pago'),
	 (1060,1,'Pendiente de complemento'),
	 (1060,2,'Pending supplement'),
	 (1060,3,'Pendente de complemento'),
	 (1061,1,'Completado'),
	 (1061,2,'Completed'),
	 (1061,3,'Completado'),
	 (1062,1,'Rechazo Contable'),
	 (1062,2,'Accounting Rejection'),
	 (1062,3,'Rejeição Contábil');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1063,1,'No válido fiscal'),
	 (1063,2,'Not fiscally valid'),
	 (1063,3,'Não válido fiscalmente'),
	 (1064,1,'Pago Manual'),
	 (1064,2,'Manual Payment'),
	 (1064,3,'Pagamento Manual'),
	 (1065,1,'Nota de crédito pendiente de relacionar'),
	 (1065,2,'Credit note pending to relate'),
	 (1065,3,'Nota de crédito pendente de relacionar'),
	 (1066,1,'Nota de crédito relacionada');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1066,2,'Credit note related'),
	 (1066,3,'Nota de crédito relacionada'),
	 (1067,1,'Nota de crédito cancelada'),
	 (1067,2,'Credit note cancelled'),
	 (1067,3,'Nota de crédito cancelada'),
	 (1068,1,'Nota de crédito borrada'),
	 (1068,2,'Credit note deleted'),
	 (1068,3,'Nota de crédito excluída'),
	 (1069,1,'Pendiente de complemento'),
	 (1069,2,'Pending supplement');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1069,3,'Pendente de complemento'),
	 (1070,1,'Complemento relacionado'),
	 (1070,2,'Related supplement'),
	 (1070,3,'Complemento relacionado'),
	 (1071,1,'Pago cancelado'),
	 (1071,2,'Payment cancelled'),
	 (1071,3,'Pagamento cancelado'),
	 (1072,1,'Pago borrado lógico'),
	 (1072,2,'Payment soft deleted'),
	 (1072,3,'Pagamento excluído logicamente');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1073,1,'Recepción disponible'),
	 (1073,2,'Reception available'),
	 (1073,3,'Recepção disponível'),
	 (1074,1,'Recepción consumida (Relación con factura)'),
	 (1074,2,'Reception consumed (Invoice relationship)'),
	 (1074,3,'Recepção consumida (Relação com fatura)'),
	 (1075,1,'Recepción consumida manual'),
	 (1075,2,'Manual consumed reception'),
	 (1075,3,'Recepção consumida manual'),
	 (1076,1,'En proceso de contabilizar factura');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1076,2,'Invoice accounting in progress'),
	 (1076,3,'Em processo de contabilização de fatura'),
	 (1077,1,'Factura rechazada'),
	 (1077,2,'Invoice rejected'),
	 (1077,3,'Fatura rejeitada'),
	 (1078,1,'Factura en proceso de pago'),
	 (1078,2,'Invoice payment in progress'),
	 (1078,3,'Fatura em processo de pagamento'),
	 (1079,1,'Recepción pagada'),
	 (1079,2,'Reception paid');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1079,3,'Recepção paga'),
	 (1080,1,'Recepción cancelada'),
	 (1080,2,'Reception cancelled'),
	 (1080,3,'Recepção cancelada'),
	 (1081,1,'Recepción borrada'),
	 (1081,2,'Reception deleted'),
	 (1081,3,'Recepção excluída'),
	 (1082,1,'Proveedores de mercancía ODBMS'),
	 (1082,2,'ODBMS merchandise suppliers'),
	 (1082,3,'Fornecedores de mercadoria ODBMS');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1083,1,'Proveedores de transporte Carta Porte'),
	 (1083,2,'Bill of Lading transport suppliers'),
	 (1083,3,'Fornecedores de transporte Carta Porte'),
	 (1084,1,'Proveedores de insumos SAP'),
	 (1084,2,'SAP supplies suppliers'),
	 (1084,3,'Fornecedores de insumos SAP'),
	 (1085,1,'Proveedores de servicios'),
	 (1085,2,'Service suppliers'),
	 (1085,3,'Fornecedores de serviços'),
	 (1086,1,'Despacho a domicilio');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1086,2,'Home delivery'),
	 (1086,3,'Entrega a domicílio'),
	 (1087,1,'Envío a tiendas desde CEDIS'),
	 (1087,2,'Shipment to stores from CEDIS'),
	 (1087,3,'Envio para lojas a partir do CEDIS'),
	 (1088,1,'Envío entre tiendas y CEDIS'),
	 (1088,2,'Shipment between stores and CEDIS'),
	 (1088,3,'Envio entre lojas e CEDIS'),
	 (1089,1,'Mercancía'),
	 (1089,2,'Merchandise');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1089,3,'Mercadoria'),
	 (1090,1,'Servicios profesionales'),
	 (1090,2,'Professional services'),
	 (1090,3,'Serviços profissionais'),
	 (1091,1,'Insumos para tienda u ODA'),
	 (1091,2,'Supplies for store or ODA'),
	 (1091,3,'Insumos para loja ou ODA'),
	 (1092,1,'Proveedores de mercancía'),
	 (1092,2,'Merchandise suppliers'),
	 (1092,3,'Fornecedores de mercadoria');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1093,1,'Proveedores de transporte'),
	 (1093,2,'Transport suppliers'),
	 (1093,3,'Fornecedores de transporte'),
	 (1094,1,'Proveedores indirectos'),
	 (1094,2,'Indirect suppliers'),
	 (1094,3,'Fornecedores indiretos'),
	 (1095,1,'Proveedores de servicios'),
	 (1095,2,'Service suppliers'),
	 (1095,3,'Fornecedores de serviços'),
	 (2000,1,'El archivo está vacío');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (2000,2,'The file is empty'),
	 (2000,3,'O arquivo está vazio'),
	 (2001,1,'El archivo debe tener extensión .xml'),
	 (2001,2,'The file must have .xml extension'),
	 (2001,3,'O arquivo deve ter extensão .xml'),
	 (2002,1,'Error procesando archivo XML fiscal'),
	 (2002,2,'Error processing fiscal XML file'),
	 (2002,3,'Erro ao processar arquivo XML fiscal'),
	 (2003,1,'El XML no tiene una estructura válida'),
	 (2003,2,'The XML does not have a valid structure');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (2003,3,'O XML não tem uma estrutura válida'),
	 (2004,1,'Error leyendo archivo XML'),
	 (2004,2,'Error reading XML file'),
	 (2004,3,'Erro ao ler arquivo XML'),
	 (2010,1,'El XML no cumple con la estructura XSD'),
	 (2010,2,'The XML does not comply with XSD structure'),
	 (2010,3,'O XML não cumpre com a estrutura XSD'),
	 (2011,1,'El XML no cumple con la estructura XSD Pagos 2.0'),
	 (2011,2,'The XML does not comply with XSD Pagos 2.0 structure'),
	 (2011,3,'O XML não cumpre com a estrutura XSD Pagos 2.0');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (2020,1,'Error configurando procesador CartaPorte'),
	 (2020,2,'Error configuring CartaPorte processor'),
	 (2020,3,'Erro ao configurar processador CartaPorte'),
	 (2021,1,'Error configurando procesador CFDI'),
	 (2021,2,'Error configuring CFDI processor'),
	 (2021,3,'Erro ao configurar processador CFDI'),
	 (2022,1,'Error configurando procesador Pagos'),
	 (2022,2,'Error configuring Pagos processor'),
	 (2022,3,'Erro ao configurar processador Pagos'),
	 (2023,1,'Error procesando CartaPorte');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (2023,2,'Error processing CartaPorte'),
	 (2023,3,'Erro ao processar CartaPorte'),
	 (2024,1,'Error procesando CFDI'),
	 (2024,2,'Error processing CFDI'),
	 (2024,3,'Erro ao processar CFDI'),
	 (2025,1,'Error procesando Pagos'),
	 (2025,2,'Error processing Pagos'),
	 (2025,3,'Erro ao processar Pagos'),
	 (2040,1,'Error detectando tipo de documento XML'),
	 (2040,2,'Error detecting XML document type');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (2040,3,'Erro ao detectar tipo de documento XML'),
	 (2041,1,'Tipo de documento fiscal no válido'),
	 (2041,2,'Invalid fiscal document type'),
	 (2041,3,'Tipo de documento fiscal não válido'),
	 (2042,1,'Tipo de CFDI no soportado en este procesador'),
	 (2042,2,'CFDI type not supported in this processor'),
	 (2042,3,'Tipo de CFDI não suportado neste processador'),
	 (2043,1,'Se esperaba Factura (I) pero se encontró tipo diferente'),
	 (2043,2,'Expected Invoice (I) but found different type'),
	 (2043,3,'Esperava-se Fatura (I) mas encontrou tipo diferente');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (2044,1,'Se esperaba Nota de Crédito (E) pero se encontró tipo diferente'),
	 (2044,2,'Expected Credit Note (E) but found different type'),
	 (2044,3,'Esperava-se Nota de Crédito (E) mas encontrou tipo diferente'),
	 (2045,1,'Tipo de comprobante no válido'),
	 (2045,2,'Invalid voucher type'),
	 (2045,3,'Tipo de comprovante não válido'),
	 (2046,1,'El tipo de comprobante debe ser P (Pago)'),
	 (2046,2,'The voucher type must be P (Payment)'),
	 (2046,3,'O tipo de comprovante deve ser P (Pagamento)'),
	 (2060,1,'Datos de Pagos no pueden ser nulos');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (2060,2,'Payment data cannot be null'),
	 (2060,3,'Dados de Pagos não podem ser nulos'),
	 (2061,1,'Complemento de Pago debe incluir nodo Totales'),
	 (2061,2,'Payment Complement must include Totales node'),
	 (2061,3,'Complemento de Pagamento deve incluir nó Totales'),
	 (2062,1,'Nodo Totales debe especificar el monto total de pagos'),
	 (2062,2,'Totales node must specify total payment amount'),
	 (2062,3,'Nó Totales deve especificar o valor total de pagamentos'),
	 (2063,1,'Complemento de Pago debe contener al menos un elemento Pago'),
	 (2063,2,'Payment Complement must contain at least one Pago element');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (2063,3,'Complemento de Pagamento deve conter ao menos um elemento Pago'),
	 (2064,1,'Complemento de Pago debe especificar la versión'),
	 (2064,2,'Payment Complement must specify version'),
	 (2064,3,'Complemento de Pagamento deve especificar a versão'),
	 (2065,1,'El complemento de pago ya se encuentra registrado en el sistema'),
	 (2065,2,'The payment complement is already registered in the system'),
	 (2065,3,'O complemento de pagamento já está registrado no sistema'),
	 (2066,1,'Error convirtiendo XML a Document'),
	 (2066,2,'Error converting XML to Document'),
	 (2066,3,'Erro ao converter XML para Document');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (2080,1,'El tipo de addenda debe ser 5 para complementos de pago'),
	 (2080,2,'Addenda type must be 5 for payment complements'),
	 (2080,3,'O tipo de addenda deve ser 5 para complementos de pagamento'),
	 (2081,1,'El RFC receptor no está autorizado en el sistema'),
	 (2081,2,'The receiver RFC is not authorized in the system'),
	 (2081,3,'O RFC receptor não está autorizado no sistema'),
	 (2082,1,'La versión del complemento de pago no es vigente en el sistema'),
	 (2082,2,'The payment complement version is not current in the system'),
	 (2082,3,'A versão do complemento de pagamento não está vigente no sistema'),
	 (2083,1,'El documento relacionado no se encuentra registrado en el sistema');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (2083,2,'The related document is not registered in the system'),
	 (2083,3,'O documento relacionado não está registrado no sistema'),
	 (3000,1,'El RFC del receptor no acepta documentos fiscales. Verifica que el RFC esté autorizado para recibir comprobantes fiscales.'),
	 (3000,2,'The receiver RFC does not accept fiscal documents. Verify that the RFC is authorized to receive tax receipts.'),
	 (3000,3,'O RFC do receptor não aceita documentos fiscais. Verifique se o RFC está autorizado a receber comprovantes fiscais.'),
	 (3001,1,'El RFC del receptor no está activo en el período de vigencia especificado'),
	 (3001,2,'The receiver RFC is not active in the specified validity period'),
	 (3001,3,'O RFC do receptor não está ativo no período de vigência especificado'),
	 (3002,1,'El RFC del receptor no se encuentra registrado en el sistema'),
	 (3002,2,'The receiver RFC is not registered in the system');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (3002,3,'O RFC do receptor não está registrado no sistema'),
	 (3003,1,'La addenda debe contener el nodo Addenda_Sodimac para documentos de mercancía, servicios y transporte local'),
	 (3003,2,'The addenda must contain the Addenda_Sodimac node for merchandise, services and local transport documents'),
	 (3003,3,'A addenda deve conter o nó Addenda_Sodimac para documentos de mercadoria, serviços e transporte local'),
	 (3004,1,'La addenda debe contener el nodo Addenda_Sodimac_CartaPorte para transporte foráneo'),
	 (3004,2,'The addenda must contain the Addenda_Sodimac_CartaPorte node for external transport'),
	 (3004,3,'A addenda deve conter o nó Addenda_Sodimac_CartaPorte para transporte externo'),
	 (3005,1,'El campo RFC en la addenda es obligatorio'),
	 (3005,2,'The RFC field in the addenda is required'),
	 (3005,3,'O campo RFC na addenda é obrigatório');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (3006,1,'El campo UUID en la addenda es obligatorio'),
	 (3006,2,'The UUID field in the addenda is required'),
	 (3006,3,'O campo UUID na addenda é obrigatório'),
	 (3007,1,'El campo Folio en la addenda es obligatorio'),
	 (3007,2,'The Folio field in the addenda is required'),
	 (3007,3,'O campo Folio na addenda é obrigatório'),
	 (3008,1,'El campo NoOC (Número de Orden de Compra) en la addenda es obligatorio'),
	 (3008,2,'The NoOC (Purchase Order Number) field in the addenda is required'),
	 (3008,3,'O campo NoOC (Número de Ordem de Compra) na addenda é obrigatório'),
	 (3009,1,'El campo Proveedor en la addenda es obligatorio');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (3009,2,'The Provider field in the addenda is required'),
	 (3009,3,'O campo Fornecedor na addenda é obrigatório'),
	 (3010,1,'El formato del RFC en la addenda no es válido'),
	 (3010,2,'The RFC format in the addenda is not valid'),
	 (3010,3,'O formato do RFC na addenda não é válido'),
	 (3011,1,'El UUID en la addenda no coincide con el UUID del TimbreFiscalDigital'),
	 (3011,2,'The UUID in the addenda does not match the TimbreFiscalDigital UUID'),
	 (3011,3,'O UUID na addenda não coincide com o UUID do TimbreFiscalDigital'),
	 (3012,1,'La versión del documento no se encuentra configurada en el sistema'),
	 (3012,2,'The document version is not configured in the system');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (3012,3,'A versão do documento não está configurada no sistema'),
	 (3013,1,'La versión del documento no está vigente'),
	 (3013,2,'The document version is not current'),
	 (3013,3,'A versão do documento não está vigente'),
	 (3014,1,'El documento debe ser versión CFDI 4.0'),
	 (3014,2,'The document must be CFDI version 4.0'),
	 (3014,3,'O documento deve ser versão CFDI 4.0'),
	 (3015,1,'El tipo de documento debe ser I (Factura) o E (Nota de Crédito)'),
	 (3015,2,'The document type must be I (Invoice) or E (Credit Note)'),
	 (3015,3,'O tipo de documento deve ser I (Fatura) ou E (Nota de Crédito)');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (3016,1,'El tipo de comprobante no está permitido para este proceso'),
	 (3016,2,'The voucher type is not allowed for this process'),
	 (3016,3,'O tipo de comprovante não é permitido para este processo'),
	 (3017,1,'Las Notas de Crédito deben incluir CFDIs relacionados con tipo de relación 01'),
	 (3017,2,'Credit Notes must include related CFDIs with relation type 01'),
	 (3017,3,'As Notas de Crédito devem incluir CFDIs relacionados com tipo de relação 01'),
	 (3018,1,'El documento fiscal no se encuentra vigente en el SAT'),
	 (3018,2,'The fiscal document is not current in SAT'),
	 (3018,3,'O documento fiscal não está vigente no SAT'),
	 (3019,1,'El documento fiscal se encuentra cancelado en el SAT');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (3019,2,'The fiscal document is cancelled in SAT'),
	 (3019,3,'O documento fiscal está cancelado no SAT'),
	 (3020,1,'El UUID no se encuentra registrado en el SAT'),
	 (3020,2,'The UUID is not registered in SAT'),
	 (3020,3,'O UUID não está registrado no SAT'),
	 (3021,1,'El sello digital del documento no es válido según el SAT'),
	 (3021,2,'The document digital seal is not valid according to SAT'),
	 (3021,3,'O selo digital do documento não é válido segundo o SAT'),
	 (3022,1,'No fue posible validar el estatus del documento en el SAT'),
	 (3022,2,'It was not possible to validate the document status in SAT');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (3022,3,'Não foi possível validar o status do documento no SAT'),
	 (3023,1,'El RFC del emisor no se encuentra registrado como proveedor autorizado'),
	 (3023,2,'The issuer RFC is not registered as an authorized supplier'),
	 (3023,3,'O RFC do emissor não está registrado como fornecedor autorizado'),
	 (3024,1,'El emisor se encuentra inactivo en el sistema'),
	 (3024,2,'The issuer is inactive in the system'),
	 (3024,3,'O emissor está inativo no sistema'),
	 (3025,1,'El RFC del emisor no es válido'),
	 (3025,2,'The issuer RFC is not valid'),
	 (3025,3,'O RFC do emissor não é válido');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (3026,1,'El documento con UUID ya se encuentra registrado en el sistema'),
	 (3026,2,'The document with UUID is already registered in the system'),
	 (3026,3,'O documento com UUID já está registrado no sistema'),
	 (3027,1,'El documento con Serie y Folio ya se encuentra registrado'),
	 (3027,2,'The document with Series and Folio is already registered'),
	 (3027,3,'O documento com Série e Folio já está registrado'),
	 (3028,1,'El archivo ya fue procesado anteriormente'),
	 (3028,2,'The file was already processed previously'),
	 (3028,3,'O arquivo já foi processado anteriormente'),
	 (3029,1,'El documento debe contener al menos un concepto');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (3029,2,'The document must contain at least one concept'),
	 (3029,3,'O documento deve conter ao menos um conceito'),
	 (3030,1,'El total del documento no puede ser cero'),
	 (3030,2,'The document total cannot be zero'),
	 (3030,3,'O total do documento não pode ser zero'),
	 (3031,1,'Los montos de los conceptos no coinciden con el total del documento'),
	 (3031,2,'The concept amounts do not match the document total'),
	 (3031,3,'Os valores dos conceitos não coincidem com o total do documento'),
	 (3032,1,'Los impuestos calculados no coinciden con los declarados'),
	 (3032,2,'The calculated taxes do not match the declared ones');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (3032,3,'Os impostos calculados não coincidem com os declarados'),
	 (3033,1,'El documento contiene impuestos no permitidos por Sodimac'),
	 (3033,2,'The document contains taxes not allowed by Sodimac'),
	 (3033,3,'O documento contém impostos não permitidos pela Sodimac'),
	 (3034,1,'La Nota de Crédito debe incluir al menos un CFDI relacionado en el nodo CfdiRelacionados'),
	 (3034,2,'The Credit Note must include at least one related CFDI in the CfdiRelacionados node'),
	 (3034,3,'A Nota de Crédito deve incluir ao menos um CFDI relacionado no nó CfdiRelacionados'),
	 (3035,1,'La Factura relacionada no se encuentra registrada en el sistema. Debe registrar primero la Factura antes de cargar la Nota de Crédito'),
	 (3035,2,'The related Invoice is not registered in the system. You must register the Invoice first before loading the Credit Note'),
	 (3035,3,'A Fatura relacionada não está registrada no sistema. Deve registrar primeiro a Fatura antes de carregar a Nota de Crédito');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (3036,1,'El CFDI relacionado no es una Factura (tipo I). Solo se pueden relacionar NC con Facturas'),
	 (3036,2,'The related CFDI is not an Invoice (type I). Only Credit Notes can be related to Invoices'),
	 (3036,3,'O CFDI relacionado não é uma Fatura (tipo I). Só podem ser relacionadas NC com Faturas'),
	 (3037,1,'El tipo de relación no es válido. Para Notas de Crédito debe ser 01'),
	 (3037,2,'The relation type is not valid. For Credit Notes it must be 01'),
	 (3037,3,'O tipo de relação não é válido. Para Notas de Crédito deve ser 01'),
	 (3038,1,'El documento con UUID no se encuentra registrado en el sistema'),
	 (3038,2,'The document with UUID is not registered in the system'),
	 (3038,3,'O documento com UUID não está registrado no sistema'),
	 (3039,1,'El documento con UUID no pertenece al proveedor especificado');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (3039,2,'The document with UUID does not belong to the specified supplier'),
	 (3039,3,'O documento com UUID não pertence ao fornecedor especificado'),
	 (3040,1,'La addenda del documento no se encuentra registrada en el sistema'),
	 (3040,2,'The document addenda is not registered in the system'),
	 (3040,3,'A addenda do documento não está registrada no sistema'),
	 (3041,1,'El estatus no es válido para el tipo de documento'),
	 (3041,2,'The status is not valid for the document type'),
	 (3041,3,'O status não é válido para o tipo de documento'),
	 (3042,1,'El estatus no existe en el catálogo de estatus'),
	 (3042,2,'The status does not exist in the status catalog');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (3042,3,'O status não existe no catálogo de status'),
	 (3043,1,'La transición de estatus no está permitida'),
	 (3043,2,'The status transition is not allowed'),
	 (3043,3,'A transição de status não é permitida'),
	 (3044,1,'No se puede actualizar un documento en estatus final alcanzado'),
	 (3044,2,'Cannot update a document in final status'),
	 (3044,3,'Não é possível atualizar um documento em status final'),
	 (3045,1,'El estatus del documento ya es el indicado. No se requiere actualización'),
	 (3045,2,'The document status is already the indicated one. No update required'),
	 (3045,3,'O status do documento já é o indicado. Não é necessária atualização');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (3046,1,'El usuario no tiene permisos para actualizar documentos fiscales'),
	 (3046,2,'The user does not have permissions to update fiscal documents'),
	 (3046,3,'O usuário não tem permissões para atualizar documentos fiscais'),
	 (3047,1,'Solo el proveedor propietario puede actualizar este documento'),
	 (3047,2,'Only the owner supplier can update this document'),
	 (3047,3,'Somente o fornecedor proprietário pode atualizar este documento'),
	 (3048,1,'El documento está en proceso automático y no puede ser modificado manualmente'),
	 (3048,2,'The document is in automatic process and cannot be modified manually'),
	 (3048,3,'O documento está em processo automático e não pode ser modificado manualmente'),
	 (4000,1,'Factura registrada exitosamente');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (4000,2,'Invoice registered successfully'),
	 (4000,3,'Fatura registrada com sucesso'),
	 (4001,1,'Factura registrada exitosamente - Pendiente de Addenda'),
	 (4001,2,'Invoice registered successfully - Pending Addenda'),
	 (4001,3,'Fatura registrada com sucesso - Pendente de Addenda'),
	 (4002,1,'Nota de Crédito registrada exitosamente'),
	 (4002,2,'Credit Note registered successfully'),
	 (4002,3,'Nota de Crédito registrada com sucesso'),
	 (4003,1,'Nota de Crédito registrada exitosamente - Pendiente de Addenda'),
	 (4003,2,'Credit Note registered successfully - Pending Addenda');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (4003,3,'Nota de Crédito registrada com sucesso - Pendente de Addenda'),
	 (4004,1,'Complemento de Pago registrado exitosamente'),
	 (4004,2,'Payment Complement registered successfully'),
	 (4004,3,'Complemento de Pagamento registrado com sucesso'),
	 (4005,1,'Factura actualizada exitosamente'),
	 (4005,2,'Invoice updated successfully'),
	 (4005,3,'Fatura atualizada com sucesso'),
	 (5308,2,'Subrogation payment'),
	 (4006,1,'Factura actualizada exitosamente - Addenda actualizada'),
	 (4006,2,'Invoice updated successfully - Addenda updated');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (4006,3,'Fatura atualizada com sucesso - Addenda atualizada'),
	 (4007,1,'Nota de Crédito actualizada exitosamente'),
	 (4007,2,'Credit Note updated successfully'),
	 (4007,3,'Nota de Crédito atualizada com sucesso'),
	 (4008,1,'Nota de Crédito actualizada exitosamente - Addenda actualizada'),
	 (4008,2,'Credit Note updated successfully - Addenda updated'),
	 (4008,3,'Nota de Crédito atualizada com sucesso - Addenda atualizada'),
	 (4100,1,'El total calculado no coincide con el total declarado'),
	 (4100,2,'The calculated total does not match the declared total'),
	 (4100,3,'O total calculado não coincide com o total declarado');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (4101,1,'Tipo de cambio no especificado, usando valor por defecto'),
	 (4101,2,'Exchange rate not specified, using default value'),
	 (4101,3,'Taxa de câmbio não especificada, usando valor padrão'),
	 (4102,1,'Moneda no especificada, usando MXN por defecto'),
	 (4102,2,'Currency not specified, using MXN by default'),
	 (4102,3,'Moeda não especificada, usando MXN por padrão'),
	 (4103,1,'El pago es parcial, saldo pendiente'),
	 (4103,2,'The payment is partial, pending balance'),
	 (4103,3,'O pagamento é parcial, saldo pendente'),
	 (4104,1,'Número de operación no especificado');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (4104,2,'Operation number not specified'),
	 (4104,3,'Número de operação não especificado'),
	 (4105,1,'Información bancaria incompleta'),
	 (4105,2,'Incomplete bank information'),
	 (4105,3,'Informação bancária incompleta'),
	 (4106,1,'Documento relacionado con saldo cero'),
	 (4106,2,'Related document with zero balance'),
	 (4106,3,'Documento relacionado com saldo zero'),
	 (4107,1,'El monto pagado excede el saldo del documento'),
	 (4107,2,'The paid amount exceeds the document balance');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (4107,3,'O valor pago excede o saldo do documento'),
	 (4108,1,'Datos opcionales de CartaPorte no especificados'),
	 (4108,2,'Optional CartaPorte data not specified'),
	 (4108,3,'Dados opcionais de CartaPorte não especificados'),
	 (4109,1,'Figuras de transporte no especificadas'),
	 (4109,2,'Transport figures not specified'),
	 (4109,3,'Figuras de transporte não especificadas'),
	 (4110,1,'Addenda sin contenido'),
	 (4110,2,'Addenda without content'),
	 (4110,3,'Addenda sem conteúdo');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (4111,1,'Campos opcionales de addenda vacíos'),
	 (4111,2,'Optional addenda fields empty'),
	 (4111,3,'Campos opcionais de addenda vazios'),
	 (4112,1,'Emisor no existía, se creó nuevo registro'),
	 (4112,2,'Issuer did not exist, new record created'),
	 (4112,3,'Emissor não existia, novo registro criado'),
	 (4113,1,'Receptor no existía, se creó nuevo registro'),
	 (4113,2,'Receiver did not exist, new record created'),
	 (4113,3,'Receptor não existia, novo registro criado'),
	 (4114,1,'Archivo con nombre similar ya fue procesado');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (4114,2,'File with similar name was already processed'),
	 (4114,3,'Arquivo com nome similar já foi processado'),
	 (4115,1,'Validación SAT tardó más de lo esperado'),
	 (4115,2,'SAT validation took longer than expected'),
	 (4115,3,'Validação SAT demorou mais do que o esperado'),
	 (4116,1,'Respuesta SAT incompleta pero válida'),
	 (4116,2,'Incomplete but valid SAT response'),
	 (4116,3,'Resposta SAT incompleta mas válida'),
	 (4117,1,'Versión del documento será obsoleta próximamente'),
	 (4117,2,'Document version will become obsolete soon');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (4117,3,'Versão do documento será obsoleta em breve'),
	 (4118,1,'Datos opcionales no especificados'),
	 (4118,2,'Optional data not specified'),
	 (4118,3,'Dados opcionais não especificados'),
	 (4119,1,'Documento registrado sin número de recepción. Requiere vinculación manual'),
	 (4119,2,'Document registered without reception number. Requires manual linking'),
	 (4119,3,'Documento registrado sem número de recepção. Requer vinculação manual'),
	 (4120,1,'La recepción no se encuentra disponible en el sistema'),
	 (4120,2,'The reception is not available in the system'),
	 (4120,3,'A recepção não está disponível no sistema');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (4121,1,'La recepción ya se encuentra vinculada a otro documento fiscal'),
	 (4121,2,'The reception is already linked to another fiscal document'),
	 (4121,3,'A recepção já está vinculada a outro documento fiscal'),
	 (2090,1,'PAC no disponible para el nivel de prioridad solicitado'),
	 (2090,2,'PAC not available for the requested priority level'),
	 (2090,3,'PAC não disponível para o nível de prioridade solicitado'),
	 (2091,1,'Error generando PDF desde XML'),
	 (2091,2,'Error generating PDF from XML'),
	 (2091,3,'Erro ao gerar PDF a partir do XML'),
	 (2092,1,'Error generando PDF del Complemento de Pago');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (2092,2,'Error generating Payment Complement PDF'),
	 (2092,3,'Erro ao gerar PDF do Complemento de Pagamento'),
	 (2093,1,'Error de validación en los campos del request'),
	 (2093,2,'Validation error in request fields'),
	 (2093,3,'Erro de validação nos campos do request'),
	 (2094,1,'Error inesperado del sistema. Contacte al administrador'),
	 (2094,2,'Unexpected system error. Contact the administrator'),
	 (2094,3,'Erro inesperado do sistema. Contate o administrador'),
	 (5000,1,'General de Ley Personas Morales'),
	 (5000,2,'General Law Legal Entities');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (5001,1,'Personas Morales con Fines no Lucrativos'),
	 (5002,1,'Sueldos y Salarios e Ingresos Asimilados a Salarios'),
	 (5002,2,'Wages, Salaries and Assimilated Income'),
	 (5003,1,'Arrendamiento'),
	 (5003,2,'Leasing'),
	 (5004,1,'Régimen de Enajenación o Adquisición de Bienes'),
	 (5004,2,'Asset Disposal or Acquisition Regime'),
	 (5005,1,'Demás ingresos'),
	 (5005,2,'Other Income'),
	 (5006,1,'Residentes en el Extranjero sin Establecimiento Permanente en México');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (5006,2,'Foreign Residents without Permanent Establishment in Mexico'),
	 (5007,1,'Ingresos por Dividendos (socios y accionistas)'),
	 (5007,2,'Dividend Income (partners and shareholders)'),
	 (5008,1,'Personas Físicas con Actividades Empresariales y Profesionales'),
	 (5008,2,'Individuals with Business and Professional Activities'),
	 (5009,1,'Ingresos por intereses'),
	 (5009,2,'Interest Income'),
	 (5010,1,'Régimen de los ingresos por obtención de premios'),
	 (5010,2,'Prize Income Regime'),
	 (5011,1,'Sin obligaciones fiscales');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (5011,2,'Without Tax Obligations'),
	 (5012,1,'Sociedades Cooperativas de Producción que optan por diferir sus ingresos'),
	 (5012,2,'Production Cooperative Societies opting to defer income'),
	 (5013,1,'Incorporación Fiscal'),
	 (5013,2,'Fiscal Incorporation'),
	 (5014,1,'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'),
	 (5014,2,'Agricultural, Livestock, Forestry and Fishing Activities'),
	 (5015,1,'Opcional para Grupos de Sociedades'),
	 (5015,2,'Optional for Corporate Groups'),
	 (5016,1,'Coordinados');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (5016,2,'Coordinated'),
	 (5017,1,'Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas'),
	 (5017,2,'Business Activities through Technology Platforms Regime'),
	 (5018,1,'Régimen Simplificado de Confianza'),
	 (5018,2,'Simplified Trust Regime'),
	 (5100,1,'Adquisición de mercancías'),
	 (5100,2,'Merchandise acquisition'),
	 (5101,1,'Devoluciones, descuentos o bonificaciones'),
	 (5101,2,'Returns, discounts or bonuses'),
	 (5102,1,'Gastos en general');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (5102,2,'General expenses'),
	 (5103,1,'Construcciones'),
	 (5103,2,'Construction'),
	 (5104,1,'Mobiliario y equipo de oficina por inversiones'),
	 (5104,2,'Office furniture and equipment'),
	 (5105,1,'Equipo de transporte'),
	 (5105,2,'Transport equipment'),
	 (5106,1,'Equipo de cómputo y accesorios'),
	 (5106,2,'Computing equipment and accessories'),
	 (5107,1,'Dados, troqueles, moldes, matrices y herramental');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (5107,2,'Dies, stamps, molds, matrices and tools'),
	 (5108,1,'Comunicaciones telefónicas'),
	 (5108,2,'Telephone communications'),
	 (5109,1,'Comunicaciones satelitales'),
	 (5109,2,'Satellite communications'),
	 (5110,1,'Otra maquinaria y equipo'),
	 (5110,2,'Other machinery and equipment'),
	 (5111,1,'Honorarios médicos, dentales y gastos hospitalarios'),
	 (5111,2,'Medical, dental fees and hospital expenses'),
	 (5112,1,'Gastos médicos por incapacidad o discapacidad');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (5112,2,'Medical expenses for disability'),
	 (5113,1,'Gastos funerales'),
	 (5113,2,'Funeral expenses'),
	 (5114,1,'Donativos'),
	 (5114,2,'Donations'),
	 (5115,1,'Intereses reales efectivamente pagados por créditos hipotecarios (casa habitación)'),
	 (5115,2,'Real interest paid on mortgage loans (housing)'),
	 (5116,1,'Aportaciones voluntarias al SAR'),
	 (5116,2,'Voluntary SAR contributions'),
	 (5117,1,'Primas por seguros de gastos médicos');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (5117,2,'Medical expense insurance premiums'),
	 (5118,1,'Gastos de transportación escolar obligatoria'),
	 (5118,2,'Mandatory school transportation expenses'),
	 (5119,1,'Depósitos en cuentas para el ahorro, primas de pensiones'),
	 (5119,2,'Savings account deposits, pension premiums'),
	 (5120,1,'Pagos por servicios educativos (colegiaturas)'),
	 (5120,2,'Educational service payments (tuition)'),
	 (5121,1,'Sin efectos fiscales'),
	 (5121,2,'Without tax effects'),
	 (5122,1,'Pagos');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (5122,2,'Payments'),
	 (5123,1,'Nómina'),
	 (5123,2,'Payroll'),
	 (5200,1,'IVA Tasa 16%'),
	 (5200,2,'VAT Rate 16%'),
	 (5201,1,'IVA Tasa 8% Región Fronteriza'),
	 (5201,2,'VAT Rate 8% Border Region'),
	 (5202,1,'IVA Tasa 0%'),
	 (5202,2,'VAT Rate 0%'),
	 (5203,1,'IVA Exento');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (5203,2,'VAT Exempt'),
	 (5204,1,'Retención IVA 10.6667%'),
	 (5204,2,'VAT Withholding 10.6667%'),
	 (5205,1,'Retención IVA 4%'),
	 (5205,2,'VAT Withholding 4%'),
	 (5300,1,'Efectivo'),
	 (5300,2,'Cash'),
	 (5301,1,'Cheque nominativo'),
	 (5301,2,'Nominative check'),
	 (5302,1,'Transferencia electrónica de fondos');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (5302,2,'Electronic funds transfer'),
	 (5303,1,'Tarjeta de crédito'),
	 (5303,2,'Credit card'),
	 (5304,1,'Monedero electrónico'),
	 (5304,2,'Electronic wallet'),
	 (5305,1,'Dinero electrónico'),
	 (5305,2,'Electronic money'),
	 (5306,1,'Vales de despensa'),
	 (5306,2,'Grocery vouchers'),
	 (5307,1,'Dación en pago');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (5307,2,'Payment in kind'),
	 (5308,1,'Pago por subrogación'),
	 (5309,1,'Pago por consignación'),
	 (5309,2,'Consignment payment'),
	 (5310,1,'Condonación'),
	 (5310,2,'Remission'),
	 (5311,1,'Compensación'),
	 (5311,2,'Compensation'),
	 (5312,1,'Novación'),
	 (5312,2,'Novation');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (5313,1,'Confusión'),
	 (5313,2,'Confusion'),
	 (5314,1,'Remisión de deuda'),
	 (5314,2,'Debt remission'),
	 (5315,1,'Prescripción o caducidad'),
	 (5315,2,'Prescription or expiration'),
	 (5316,1,'A satisfacción del acreedor'),
	 (5316,2,'To creditor satisfaction'),
	 (5317,1,'Tarjeta de débito'),
	 (5317,2,'Debit card');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (5318,1,'Tarjeta de servicios'),
	 (5318,2,'Services card'),
	 (5319,1,'Aplicación de anticipos'),
	 (5319,2,'Advance payment application'),
	 (5320,1,'Por definir'),
	 (5320,2,'To be defined'),
	 (5400,1,'Pago en una sola exhibición'),
	 (5400,2,'Payment in one installment'),
	 (5401,1,'Pago en parcialidades o diferido'),
	 (5401,2,'Payment in installments or deferred');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (5500,1,'Ingreso'),
	 (5500,2,'Income'),
	 (5501,1,'Egreso'),
	 (5501,2,'Expense'),
	 (5502,1,'Traslado'),
	 (5502,2,'Transfer'),
	 (5503,1,'Nómina'),
	 (5503,2,'Payroll'),
	 (5504,1,'Pago'),
	 (5504,2,'Payment');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (6000,1,'Error de conexion con la base de datos'),
	 (6000,2,'Database connection error'),
	 (6000,3,'Erro de conexao com o banco de dados'),
	 (6001,1,'Error al procesar el parametro {0}'),
	 (6001,2,'Error processing parameter {0}'),
	 (6001,3,'Erro ao processar o parametro {0}'),
	 (6002,1,'Error de validacion en los datos de entrada'),
	 (6002,2,'Validation error in input data'),
	 (6002,3,'Erro de validacao nos dados de entrada'),
	 (6003,1,'El recurso solicitado no fue encontrado');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (6003,2,'The requested resource was not found'),
	 (6003,3,'O recurso solicitado nao foi encontrado'),
	 (6004,1,'Error interno del servidor. Contacte al administrador'),
	 (6004,2,'Internal server error. Contact the administrator'),
	 (6004,3,'Erro interno do servidor. Contate o administrador'),
	 (6005,1,'Tiempo de espera agotado para la operacion'),
	 (6005,2,'Operation timeout exceeded'),
	 (6005,3,'Tempo limite excedido para a operacao'),
	 (6006,1,'Error al serializar/deserializar datos'),
	 (6006,2,'Error serializing/deserializing data');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (6006,3,'Erro ao serializar/deserializar dados'),
	 (6007,1,'Error en la configuracion del sistema'),
	 (6007,2,'System configuration error'),
	 (6007,3,'Erro na configuracao do sistema'),
	 (6020,1,'Ya existe un parametro con el nombre {0} y version {1}'),
	 (6020,2,'A parameter with name {0} and version {1} already exists'),
	 (6020,3,'Ja existe um parametro com o nome {0} e versao {1}'),
	 (6021,1,'El modulo con ID {0} no existe'),
	 (6021,2,'Module with ID {0} does not exist'),
	 (6021,3,'O modulo com ID {0} nao existe');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (6022,1,'El parametro con ID {0} no existe'),
	 (6022,2,'Parameter with ID {0} does not exist'),
	 (6022,3,'O parametro com ID {0} nao existe'),
	 (6023,1,'Ya existe un mensaje con el codigo {0}'),
	 (6023,2,'A message with code {0} already exists'),
	 (6023,3,'Ja existe uma mensagem com o codigo {0}'),
	 (6024,1,'El mensaje con codigo {0} no existe'),
	 (6024,2,'Message with code {0} does not exist'),
	 (6024,3,'A mensagem com codigo {0} nao existe'),
	 (6025,1,'El proceso con ID {0} no existe');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (6025,2,'Process with ID {0} does not exist'),
	 (6025,3,'O processo com ID {0} nao existe'),
	 (6026,1,'El tipo de elemento con ID {0} no existe'),
	 (6026,2,'Item type with ID {0} does not exist'),
	 (6026,3,'O tipo de elemento com ID {0} nao existe'),
	 (6027,1,'El elemento con ID {0} no existe'),
	 (6027,2,'Item with ID {0} does not exist'),
	 (6027,3,'O elemento com ID {0} nao existe'),
	 (6028,1,'El parametro {0} se encuentra inactivo'),
	 (6028,2,'Parameter {0} is inactive');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (6028,3,'O parametro {0} esta inativo'),
	 (6029,1,'El valor del parametro {0} no es valido: {1}'),
	 (6029,2,'Parameter {0} value is not valid: {1}'),
	 (6029,3,'O valor do parametro {0} nao e valido: {1}'),
	 (6030,1,'La relacion mensaje {0} - aplicativo {1} ya existe'),
	 (6030,2,'Message {0} - application {1} relationship already exists'),
	 (6030,3,'A relacao mensagem {0} - aplicativo {1} ja existe'),
	 (6031,1,'El modulo {0} no puede eliminarse porque tiene parametros asociados'),
	 (6031,2,'Module {0} cannot be deleted because it has associated parameters'),
	 (6031,3,'O modulo {0} nao pode ser excluido porque possui parametros associados');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (6050,1,'Parametro {0} creado exitosamente'),
	 (6050,2,'Parameter {0} created successfully'),
	 (6050,3,'Parametro {0} criado com sucesso'),
	 (6051,1,'Parametro {0} actualizado exitosamente'),
	 (6051,2,'Parameter {0} updated successfully'),
	 (6051,3,'Parametro {0} atualizado com sucesso'),
	 (6052,1,'Parametro eliminado exitosamente'),
	 (6052,2,'Parameter deleted successfully'),
	 (6052,3,'Parametro excluido com sucesso'),
	 (6053,1,'Modulo {0} creado exitosamente');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (6053,2,'Module {0} created successfully'),
	 (6053,3,'Modulo {0} criado com sucesso'),
	 (6054,1,'Configuracion guardada exitosamente'),
	 (6054,2,'Configuration saved successfully'),
	 (6054,3,'Configuracao salva com sucesso'),
	 (6070,1,'No se encontraron resultados para la busqueda'),
	 (6070,2,'No results found for the search'),
	 (6070,3,'Nenhum resultado encontrado para a busca'),
	 (6071,1,'La operacion se esta procesando'),
	 (6071,2,'The operation is being processed');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (6071,3,'A operacao esta sendo processada'),
	 (6072,1,'Cache de parametros actualizado'),
	 (6072,2,'Parameters cache updated'),
	 (6072,3,'Cache de parametros atualizado'),
	 (6090,1,'El parametro {0} expira en {1} dias'),
	 (6090,2,'Parameter {0} expires in {1} days'),
	 (6090,3,'O parametro {0} expira em {1} dias'),
	 (6091,1,'La version {0} del parametro {1} esta obsoleta'),
	 (6091,2,'Version {0} of parameter {1} is obsolete'),
	 (6091,3,'A versao {0} do parametro {1} esta obsoleta');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (6092,1,'Se excedio el limite de {0} registros. Mostrando primeros resultados'),
	 (6092,2,'Exceeded limit of {0} records. Showing first results'),
	 (6092,3,'Excedido o limite de {0} registros. Mostrando primeiros resultados'),
	 (7000,1,'Ya existe un proveedor con el numero: {0}'),
	 (7000,2,'A supplier with number {0} already exists'),
	 (7000,3,'Ja existe um fornecedor com o numero: {0}'),
	 (7001,1,'El proveedor con ID {0} no existe'),
	 (7001,2,'Supplier with ID {0} does not exist'),
	 (7001,3,'O fornecedor com ID {0} nao existe'),
	 (7004,1,'El tipo de proveedor con ID {0} no existe');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (7004,2,'Supplier type with ID {0} does not exist'),
	 (7004,3,'O tipo de fornecedor com ID {0} nao existe'),
	 (7005,1,'La condicion de pago con ID {0} no existe'),
	 (7005,2,'Payment condition with ID {0} does not exist'),
	 (7005,3,'A condicao de pagamento com ID {0} nao existe'),
	 (8014,1,'NO SE PUDIERON GUARDAR LAS GUIAS DE EMBARQUE O LOS ARCHIVOS EN EL BUCKET DE GCP.'),
	 (8014,2,'The shipping manifests or files could not be stored in the GCP bucket.'),
	 (8014,3,'Os manifestos ou ficheiros de remessa não puderam ser armazenados no bucket do GCP.'),
	 (7006,1,'El centro de costo con ID {0} no existe'),
	 (7006,2,'Cost center with ID {0} does not exist');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (7006,3,'O centro de custo com ID {0} nao existe'),
	 (7007,1,'El centro de beneficio con ID {0} no existe'),
	 (7007,2,'Benefit center with ID {0} does not exist'),
	 (7007,3,'O centro de beneficio com ID {0} nao existe'),
	 (7008,1,'La cuenta contable con ID {0} no existe'),
	 (7008,2,'Accounting account with ID {0} does not exist'),
	 (7008,3,'A conta contabil com ID {0} nao existe'),
	 (7009,1,'Ya existe un proveedor con el RFC: {0}'),
	 (7009,2,'A supplier with RFC {0} already exists'),
	 (7009,3,'Ja existe um fornecedor com o RFC: {0}');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (7010,1,'El proveedor {0} se encuentra inactivo'),
	 (7010,2,'Supplier {0} is inactive'),
	 (7010,3,'O fornecedor {0} esta inativo'),
	 (7011,1,'El proveedor {0} no puede eliminarse porque tiene roles asociados'),
	 (7011,2,'Supplier {0} cannot be deleted because it has associated roles'),
	 (7011,3,'O fornecedor {0} nao pode ser excluido porque possui funcoes associadas'),
	 (7012,1,'El numero de proveedor es requerido'),
	 (7012,2,'Supplier number is required'),
	 (7012,3,'O numero do fornecedor e obrigatorio'),
	 (7013,1,'La razon social del proveedor es requerida');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (7013,2,'Supplier business name is required'),
	 (7013,3,'A razao social do fornecedor e obrigatoria'),
	 (8015,1,'No se encuentra la Guia para relacionar {0} con la Orden de Compra {1}'),
	 (8015,2,'The guide to link {0} to Purchase Order {1} could not be found.'),
	 (8015,3,'Não foi possível encontrar o guia para ligar {0} ao Pedido de Compra {1}.'),
	 (7014,1,'No existe el tipo de proveedor [{0}] solicitado.'),
	 (7014,2,'Supplier type [{0}] does not exist.'),
	 (7014,3,'O tipo de fornecedor [{0}] nao existe.'),
	 (7002,1,'El proveedor con numero {0} no existe'),
	 (7002,2,'Supplier with number {0} does not exist');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (7002,3,'O fornecedor com numero {0} nao existe'),
	 (7003,1,'El proveedor con RFC {0} no existe'),
	 (7003,2,'Supplier with RFC {0} does not exist'),
	 (7003,3,'O fornecedor com RFC {0} nao existe'),
	 (7058,1,'Orden de Compra creada en el sistema de FBC exitosamente'),
	 (7058,2,'Purchase Order successfully created in the FBC system'),
	 (7058,3,'Pedido de compra criado com sucesso no sistema FBC.'),
	 (8022,1,'Generado'),
	 (8022,2,'Generated'),
	 (8022,3,'Gerado');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (8023,1,'Publicado'),
	 (7030,1,'Proveedor {0} creado exitosamente'),
	 (7030,2,'Supplier {0} created successfully'),
	 (7030,3,'Fornecedor {0} criado com sucesso'),
	 (7031,1,'Proveedor {0} actualizado exitosamente'),
	 (7031,2,'Supplier {0} updated successfully'),
	 (7031,3,'Fornecedor {0} atualizado com sucesso'),
	 (7032,1,'Proveedor {0} eliminado exitosamente'),
	 (7032,2,'Supplier {0} deleted successfully'),
	 (7032,3,'Fornecedor {0} excluido com sucesso');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (7033,1,'Proveedor {0} activado exitosamente'),
	 (7033,2,'Supplier {0} activated successfully'),
	 (7033,3,'Fornecedor {0} ativado com sucesso'),
	 (7034,1,'Proveedor {0} desactivado exitosamente'),
	 (7034,2,'Supplier {0} deactivated successfully'),
	 (7034,3,'Fornecedor {0} desativado com sucesso'),
	 (7050,1,'No se encontraron proveedores'),
	 (7050,2,'No suppliers found'),
	 (7050,3,'Nenhum fornecedor encontrado'),
	 (7051,1,'Se encontraron {0} proveedores');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (7051,2,'{0} suppliers found'),
	 (7051,3,'{0} fornecedores encontrados'),
	 (7070,1,'El proveedor {0} no tiene tipo de proveedor asignado'),
	 (7070,2,'Supplier {0} does not have an assigned supplier type'),
	 (7070,3,'O fornecedor {0} nao possui tipo de fornecedor atribuido'),
	 (7071,1,'El proveedor {0} no tiene condicion de pago asignada'),
	 (7071,2,'Supplier {0} does not have an assigned payment condition'),
	 (7071,3,'O fornecedor {0} nao possui condicao de pagamento atribuida'),
	 (8023,2,'Published'),
	 (8023,3,'Publicado');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (8024,1,'Revisado'),
	 (8024,2,'Reviewed'),
	 (8024,3,'Revisado'),
	 (8025,1,'Rechazado'),
	 (8025,2,'Rejected'),
	 (8025,3,'Rejeitado'),
	 (8026,1,'Reprocesado'),
	 (8026,2,'Reprocessed'),
	 (8026,3,'Reprocessado'),
	 (5600,1,'Nota de crédito de los documentos relacionados');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (5600,2,'Credit note for related documents'),
	 (5600,3,'Nota de crédito dos documentos relacionados'),
	 (5601,1,'Nota de débito de los documentos relacionados'),
	 (5601,2,'Debit note for related documents'),
	 (5601,3,'Nota de débito dos documentos relacionados'),
	 (5602,1,'Devolución de mercancía sobre facturas o traslados previos'),
	 (5602,2,'Merchandise return on previous invoices or transfers'),
	 (5602,3,'Devolução de mercadoria sobre faturas ou transferências anteriores'),
	 (5603,1,'Sustitución de los CFDI previos'),
	 (5603,2,'Substitution of previous CFDIs');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (5603,3,'Substituição dos CFDIs anteriores'),
	 (5604,1,'Traslados de mercancías facturados previamente'),
	 (5604,2,'Previously invoiced merchandise transfers'),
	 (5604,3,'Transferências de mercadorias faturadas anteriormente'),
	 (5605,1,'Factura generada por los traslados previos'),
	 (5605,2,'Invoice generated for previous transfers'),
	 (5605,3,'Fatura gerada pelas transferências anteriores'),
	 (5606,1,'CFDI por aplicación de anticipo'),
	 (5606,2,'CFDI for advance payment application'),
	 (5606,3,'CFDI por aplicação de adiantamento');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (5607,1,'Factura generada por pagos en parcialidades'),
	 (5607,2,'Invoice generated for installment payments'),
	 (5607,3,'Fatura gerada por pagamentos parcelados'),
	 (5608,1,'Factura generada por pagos diferidos'),
	 (5608,2,'Invoice generated for deferred payments'),
	 (5608,3,'Fatura gerada por pagamentos diferidos'),
	 (5700,1,'Addenda Estándar'),
	 (5700,2,'Standard Addenda'),
	 (5700,3,'Addenda Padrão'),
	 (5701,1,'Addenda con Carta Porte');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (5701,2,'Addenda with Bill of Lading'),
	 (5701,3,'Addenda com Carta de Porte'),
	 (5702,1,'Addenda Complemento de Pago'),
	 (5702,2,'Payment Complement Addenda'),
	 (5702,3,'Addenda Complemento de Pagamento'),
	 (5703,1,'Addenda Internacional'),
	 (5703,2,'International Addenda'),
	 (5703,3,'Addenda Internacional'),
	 (5704,1,'Addenda Sodimac'),
	 (5704,2,'Sodimac Addenda');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (5704,3,'Addenda Sodimac'),
	 (1096,1,'Origen pendiente'),
	 (1096,2,'Pending origin'),
	 (1096,3,'Origem pendente'),
	 (1097,1,'Origen local'),
	 (1097,2,'Local origin'),
	 (1097,3,'Origem local'),
	 (1098,1,'Origen foráneo'),
	 (1098,2,'Foreign origin'),
	 (1098,3,'Origem estrangeira');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (1099,1,'Origen mixto'),
	 (1099,2,'Mixed origin'),
	 (1099,3,'Origem mista'),
	 (7072,1,'No existe información con los criterios establecidos'),
	 (7072,2,'No information found with the established criteria'),
	 (7072,3,'Não existem informações com os critérios estabelecidos'),
	 (7073,1,'El estatus de la recepción no permite realizar esta actualización. Por favor, valide la información antes de continuar.'),
	 (7073,2,'The reception status does not allow this update. Please validate the information before continuing.'),
	 (7073,3,'O status da recepção não permite esta atualização. Por favor, valide as informações antes de continuar.'),
	 (8000,2,'An exception occurred while retrieving the Purchase Order list. Please check the error message.');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (8000,3,'Ocorreu uma exceção ao recuperar a lista de Encomendas de Compra. Verifique a mensagem de erro.'),
	 (8000,1,'Se produjuo un excepcion en la obtención del listado de Ordenes de Compra. Verifique el detalle del error.'),
	 (8001,1,'Se produjuo un excepcion al obtener la Orden de Compra. Verifique el detalle del error.'),
	 (8001,2,'An exception occurred when obtaining the Purchase Order. Please check the error detail.'),
	 (8001,3,'Ocorreu uma exceção ao obter a Ordem de Compra. Verifique a detalhe de erro.'),
	 (8002,1,'Se produjuo un excepcion al obtener la Recepción. Verifique el detalle del error.'),
	 (8002,2,'An exception occurred when obtaining the Reception. Please check the error detail.'),
	 (8002,3,'Ocorreu uma exceção ao obter a Recepção. Verifique a detalhe de erro.'),
	 (8003,1,'Se produjuo un excepcion al actualizar la Recepción. Verifique el detalle del error.'),
	 (8003,2,'An exception occurred when updating the Reception. Please check the error detail.');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (8003,3,'Ocorreu uma exceção ao atualizar a Recepção. Verifique a detalhe de erro.'),
	 (8004,1,'Se produjuo un excepcion al actualizar la Orden de Compra. Verifique el detalle del error.'),
	 (8004,2,'An exception occurred when updating the Purchase Order. Please check the error detail.'),
	 (8004,3,'Ocorreu uma exceção ao atualizar a Ordem de Compra. Verifique a detalhe de erro.'),
	 (8005,1,'Se produjuo un excepcion en la obtención del listado de las recepciones. Verifique el detalle del error.'),
	 (8005,2,'An exception occurred while retrieving the Reception list. Please check the error detail.'),
	 (8005,3,'Ocorreu uma exceção ao recuperar a lista de Recepção. Verifique a detalhe de erro.'),
	 (7074,1,'No existe la Orden de compra {0} para el proveedor {1}.'),
	 (7074,2,'Não existe nenhum pedido de compra {0} para o fornecedor {1}.'),
	 (7074,3,'There is no Purchase Order {0} for supplier {1}');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (7075,1,'la Orden de compra {0} para el proveedor {1} no tiene recepciones asignadas.'),
	 (7075,2,'Purchase Order {0} for supplier {1} has no assigned receipts'),
	 (7075,3,'A ordem de compra {0} para o fornecedor {1} não tem recibos atribuídos.'),
	 (7076,1,'Recepción actualizada correctamente'),
	 (7076,2,'Successfully updated reception'),
	 (7076,3,'Receção atualizada com sucesso'),
	 (8006,1,'No fue posible registrar la guía carta porte, Favor de validar. Verifique el detalle del error.'),
	 (8006,2,'It was not possible to register the waybill. Please validate. Check the error details..'),
	 (8006,3,'Não foi possível registar a guia de remessa. Por favor, valide. Verifique os detalhes do erro.'),
	 (8007,1,'No fue posible registrar la orden de compra, Favor de validar. Verifique el detalle del error.');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (8007,2,'It was not possible to register the purchase order. Please validate. Check the error details'),
	 (8007,3,'Não foi possível registar a pedido de compra. Por favor, valide. Verifique os detalhes do erro.'),
	 (8008,1,'No fue posible registrar la Orden de Compra y la documentación, Favor de validar. Verifique el detalle del error.'),
	 (8008,2,'It was not possible to register the purchase order and the documentation. Please validate. Check the error details.'),
	 (8008,3,'Não foi possível registar o Pedido de Compra e a documentação. Por favor, valide. Verifique os detalhes do erro.'),
	 (8009,1,'No fue posible encontrar las guias, Favor de validar. Verifique el detalle del error.'),
	 (8009,2,'The guides could not be found. Please validate. Please validate. Check the error details.'),
	 (8009,3,'Os guias não foram encontrados. Por favor, verifique. Verifique os detalhes do erro.'),
	 (8010,1,'No fue posible encontrar las guias, Favor de validar. Verifique el detalle del error.'),
	 (8010,2,'The guides could not be found. Please validate. Please validate. Check the error details.');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (8010,3,'Os guias não foram encontrados. Por favor, verifique. Verifique os detalhes do erro.'),
	 (8011,1,'No fue posible exportar a csv, Favor de validar. Verifique el detalle del error.'),
	 (8011,2,'Exporting to CSV was not possible. Please validate. Check the error details.'),
	 (8016,1,'La factura requiere una serie y folio para publicar el documento. Por favor, valide la información antes de continuar.'),
	 (8011,3,'Não foi possível exportar para CSV. Por favor, verifique Verifique os detalhes do erro.'),
	 (8012,1,'No fue posible Listar las guias de embarque, Favor de validar. Verifique el detalle del error.'),
	 (8012,2,'It was not possible to list the shipping guides. Please validate. Check the error details.'),
	 (8012,3,'Não foi possível listar os guias de envio. Por favor. Por favor, verifique. Verifique os detalhes do erro.'),
	 (8013,1,'No fue posible actualizar la guia, Favor de validar. Verifique el detalle del error.'),
	 (8013,2,'It was not possible to update the shipping guides. Please validate. Check the error details.');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (8013,3,'Não foi possível atualizar o guia. Por favor, verifique. Verifique os detalhes do erro.'),
	 (7052,1,'Guia de embarque no encontrada'),
	 (7052,2,'Waybill not found'),
	 (7052,3,'Guia de remessa não encontrada'),
	 (7053,1,'No se pudieron registrar los documentos en google storage'),
	 (7053,2,'The documents could not be registered in Google Storage'),
	 (7053,3,'Os documentos não puderam ser registados no Google Storage.'),
	 (7054,1,'El registro de la guía de embarque se realizó exitosamente'),
	 (7054,2,'The shipping guide registration was successful'),
	 (7054,3,'O registo no guia de envio foi realizado com sucesso.');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (7055,1,'Guia de embarque no actualizada'),
	 (7055,2,'The shipping guide not updated'),
	 (7055,3,'Conhecimento de embarque não atualizado.'),
	 (7056,1,'Guia de embarque actualizada exitosamente'),
	 (7056,2,'The shipping guide updated'),
	 (7056,3,'Conhecimento de embarque não atualizado.'),
	 (7057,1,'Orden de Compra y Guias Registradas en el sistema de FBC exitosamente'),
	 (7057,2,'Purchase Order and shipping guied successfully registered in the FBC system'),
	 (7057,3,'As ordens de compra e os conhecimentos de embarque registados com sucesso no sistema FBC.'),
	 (8016,2,'The invoice requires a series and folio to publish the document. Please validate the information before continuing.');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (8016,3,'A fatura requer uma série e folio para publicar o documento. Por favor, valide as informações antes de continuar.'),
	 (8017,1,'La factura se encuentra previamente registrada con la misma serie y folio. Por favor, valide la información antes de continuar.'),
	 (8017,2,'The invoice is already registered with the same series and folio. Please validate the information before continuing.'),
	 (8017,3,'A fatura já está registrada com a mesma série e folio. Por favor, valide as informações antes de continuar.'),
	 (8018,1,'La factura se encuentra previamente registrada con el mismo UUID. Por favor, valide la información antes de continuar.'),
	 (8018,2,'The invoice is already registered with the same UUID. Please validate the information before continuing.'),
	 (8018,3,'A fatura já está registrada com o mesmo UUID. Por favor, valide as informações antes de continuar.'),
	 (8019,1,'La nota de crédito requiere una serie y folio para publicar el documento. Por favor, valide la información antes de continuar.'),
	 (8019,2,'The credit note requires a series and folio to publish the document. Please validate the information before continuing.'),
	 (8019,3,'A nota de crédito requer uma série e folio para publicar o documento. Por favor, valide as informações antes de continuar.');
INSERT INTO shared_catalogs.dictionary_lang (dict_id,lang_id,description) VALUES
	 (8020,1,'La nota de crédito se encuentra previamente registrada con la misma serie y folio. Por favor, valide la información antes de continuar.'),
	 (8020,2,'The credit note is already registered with the same series and folio. Please validate the information before continuing.'),
	 (8020,3,'A nota de crédito já está registrada com a mesma série e folio. Por favor, valide as informações antes de continuar.'),
	 (8021,1,'La nota de crédito se encuentra previamente registrada con el mismo UUID. Por favor, valide la información antes de continuar.'),
	 (8021,2,'The credit note is already registered with the same UUID. Please validate the information before continuing.'),
	 (8021,3,'A nota de crédito já está registrada com o mesmo UUID. Por favor, valide as informações antes de continuar.');
