apiVersion: apps/v1
kind: Deployment

metadata:
  name: ${PROJECT_NAME}

spec:
  selector:
    matchLabels:
      app: ${PROJECT_NAME}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: ${PROJECT_NAME}

    spec:
      automountServiceAccountToken: false

      containers:
        - name: ${PROJECT_NAME}
          image: foo/bar

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false

          resources:
            requests:
              cpu: "25m"
              memory: "512Mi"
              ephemeral-storage: "256Mi"
            limits:
              cpu: "250m"
              memory: "1Gi"

          env:
            - name: CI_JOB_ID
              value: "${CI_JOB_ID}"

          startupProbe:
            httpGet:
              path: /healthz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 40
            failureThreshold: 60
            periodSeconds: 5
            timeoutSeconds: 2

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
              scheme: HTTP
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
              scheme: HTTP
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
