##### FACTURAS_TO_BCT #####
factutas.to.bct.dias=15
factutas.to.bct.rango.fechas=false
factutas.to.bct.fecha.inicio=2023-01-01
factutas.to.bct.fecha.fin=2023-07-12

####### VENTA CAB ######
venta.cab.dias=15
venta.cab.rango.fechas=false
venta.cab.fecha.inicio=2024-11-12
venta.cab.fecha.fin=2024-11-14

##### FACTURAS_TO_FISCAL #####
factutas.to.fiscal.dias=15
factutas.to.fiscal.rango.fechas=false
factutas.to.fiscal.fecha.inicio=2023-07-14
factutas.to.fiscal.fecha.fin=2023-08-13

##### FACTURACION GLOBAL #####
global.anio.fijo=false
global.anio=2023

global.ventas.activo=true
global.ventas.numtrimestre=4
global.devolucion.activo=false
global.devolucion.numtrimestre=4
global.notacredito.activo=false
global.notacredito.numtrimestre=4
global.devolucion.fdc.activo=false
global.devolucion.fdc.numtrimestre=4
global.proceso.dias=3

#global.ventas.sql=D:\\BctFacturacion\\global\\timbradoGlobal-venta.sql
#global.devolucion.sql=D:\\BctFacturacion\\global\\timbradoGlobal-devolucion.sql
#global.nota.credito.sql=D:\\BctFacturacion\\global\\timbradoGlobal-notaCredito.sql
#global.devolucion.fdc.sql=D:\\BctFacturacion\\global\\timbradoGlobal-devolucionFDC.sql
#global.ventas.file=D:\\FacturacionGlobalBatch\\facturadorProd_40\\sucursal_fecha_reproceso.txt

global.ventas.sql=C:\\Users\\iscortesz\\OneDrive - Falabella\\Sodimac\\Fuente\\finanzas_bctfacturacion\\src\\main\\resources\\timbradoGlobal-venta.sql
global.devolucion.sql=C:\\Users\\iscortesz\\OneDrive - Falabella\\Sodimac\\Fuente\\finanzas_bctfacturacion\\src\\main\\resources\\timbradoGlobal-devolucion.sql
global.nota.credito.sql=C:\\Users\\iscortesz\\OneDrive - Falabella\\Sodimac\\Fuente\\finanzas_bctfacturacion\\src\\main\\resources\\timbradoGlobal-notaCredito.sql
global.devolucion.fdc.sql=C:\\Users\\iscortesz\\OneDrive - Falabella\\Sodimac\\Fuente\\finanzas_bctfacturacion\\src\\main\\resources\\timbradoGlobal-devolucionFDC.sql
global.ventas.file=C:\\Users\\iscortesz\\OneDrive - Falabella\\Sodimac\\Fuente\\sucursal_fecha_reproceso.txt


####### PUNTOS CES ######
puntos.ces.dias=15
puntos.ces.rango.fechas=true
puntos.ces.fecha.inicio=2025-01-01
puntos.ces.fecha.fin=2025-02-23

####### PUNTOS CES - TICKETS PUNTUALES (modo exclusivo, solo TRANSACTIONTYPE='sale') ######
puntos.ces.tickets.activo=false
puntos.ces.tickets.lista=


############################ PORTAL IN HOUSE #####################################

jdbc.driverClassName=org.mariadb.jdbc.Driver

### PRODUCCION ####
#jdbc.url=jdbc:mysql://10.138.150.77:3306/facturacion

jdbc.url=97fa82ef7a6718fac327ae724fa824e6a999e2fdcbc748a412d94cde3f4a546e2c639355ef7f242adf127f078b91ea0b
jdbc.user=73e8dcc391c87efe9a1c2389762db10a
jdbc.pass=73e8dcc391c87efe9a1c2389762db10a

# hibernate.X
hibernate.dialect=org.hibernate.dialect.MariaDBDialect
hibernate.show_sql=true
hibernate.hbm2ddl.auto=validate
hibernate.cache.use_second_level_cache=false
hibernate.cache.use_query_cache=false

############################ BCT #####################################
jdbc.bct.driverClassName=oracle.jdbc.driver.OracleDriver

### DESAROLLO ###
#jdbc.bct.url=5732699850965d977f559cbeda4cf269b81b8e4f9585f90929b8d131bac53a55da40c94c24ecc97b895d5863065d683709c098233e4cc3516466aecfbf029127
#jdbc.bct.user=34637caa6556dd4adf6a8ce4b3465d68
#jdbc.bct.pass=95e783fcab04e42a8da401fea040beb0

### PRODUCCION ####
#jdbc.bct.url=jdbc:oracle:thin:@ramsay.falabella.cl:1531/arsmxpr
#jdbc.bct.user=BATSW_FAC

jdbc.bct.url=5732699850965d977f559cbeda4cf269668663bb5c27875e4a561afe0abca0e444f4bb99946d7ab6570625ad6437e0a32f902e3734c7e19c924e6e5b19da7b8f
jdbc.bct.user=34637caa6556dd4adf6a8ce4b3465d68
jdbc.bct.pass=229b42c9f981ab35d153d1ebdd641bd4

# hibernate.X
hibernate.bct.dialect=org.hibernate.dialect.Oracle10gDialect
hibernate.bct.show_sql=true
hibernate.bct.hbm2ddl.auto=none
hibernate.bct.cache.use_second_level_cache=false
hibernate.bct.cache.use_query_cache=false

# c3p0.X
c3p0.bct.min_size=5
c3p0.bct.max_size=20
c3p0.bct.acquire_increment=5
c3p0.bct.timeout=1800
c3p0.bct.testConnectionOnCheckout=false
c3p0.bct.testConnectionOnCheckin=true
c3p0.bct.preferredTestQuery=SELECT 1 from dual
c3p0.bct.idleConnectionTestPeriod=300
c3p0.bct.privilegeSpawnedThreads=true
c3p0.bct.contextClassLoaderSource=library


############################ FISCAL #####################################
jdbc.fiscal.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

### DESAROLLO ###

#jdbc.fiscal.url=jdbc:sqlserver://10.138.153.10:5319;databaseName=SODIMAC_REBATES_DEV;encrypt=true;trustServerCertificate=true
#jdbc.fiscal.user=SodimacDevUsr

jdbc.fiscal.url=315dacbe6d7418ee3011d7c4a85e9c210b9ab5c1e6e6a78cd17b15f079b86f685d66d92aeb9288c368230096541b4d99cd6d7eb899b82734b63cd2ab9bd8b16d92ed9046109e799ecf96ecf966b8587acac8ee621487681ea7167e78bc3485faa7ce860ff7f5723c737e576e2169e681
jdbc.fiscal.user=7050fca7378222483a68bff94e152310
jdbc.fiscal.pass=a2506f404f285b76f1f24f3b1b599310

### PRODUCCION ####
#jdbc.fiscal.url=jdbc:sqlserver://10.138.150.124:5319;databaseName=SODIMAC_FISCAL_PROD;encrypt=true;trustServerCertificate=true
#jdbc.fiscal.user=UserBatchFinanzas

#jdbc.fiscal.url=315dacbe6d7418ee3011d7c4a85e9c217cd0dda46a5eea4741495b15c479375673513d00b3ed738ea71c85eea2618265bc7ef37ef7e6e17275a97d9932b7597a39a9e5ad881a6a65c554c649f5b2bd0ff2cc9932059f699f2335418648f15071689362fcb2a06b4255dbe0d587e503c5
#jdbc.fiscal.user=f24ca2f276214cded4eb4d354ee5e066597529d2c67df5f4cd9323bdeb861a0b
#jdbc.fiscal.pass=13194557815871078fc6b4ccf397ab73b23660ba51ce8d14d1470b5e4c5706b7

# hibernate.X
hibernate.fiscal.dialect=org.hibernate.dialect.SQLServer2012Dialect
hibernate.fiscal.show_sql=true
hibernate.fiscal.hbm2ddl.auto=none
hibernate.fiscal.cache.use_second_level_cache=false
hibernate.fiscal.cache.use_query_cache=false

# c3p0.X
c3p0.fiscal.min_size=5
c3p0.fiscal.max_size=20
c3p0.fiscal.acquire_increment=5
c3p0.fiscal.timeout=1800
c3p0.fiscal.testConnectionOnCheckout=false
c3p0.fiscal.testConnectionOnCheckin=true
c3p0.fiscal.preferredTestQuery=SELECT 1
c3p0.fiscal.idleConnectionTestPeriod=300
c3p0.fiscal.privilegeSpawnedThreads=true
c3p0.fiscal.contextClassLoaderSource=library


############################ CES #####################################
jdbc.ces.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

### DESAROLLO ###
#jdbc.ces.url=jdbc:sqlserver://10.138.153.10;databaseName=SODIMAC_SAP_DEV;encrypt=true;trustServerCertificate=true
#jdbc.ces.user=SodimacDevUsr

#jdbc.ces.url=315dacbe6d7418ee3011d7c4a85e9c2138f5e1cd06b40f90cfdf1ac3065ca0e82e5fd46c8350061fa4acb40ae21ba924b6d1bf863dce1ef9b536e73720f5aab5d820125091e52e91ce9a3bddf9a767220866adf0afebc33f8b7fb087686c1c3d0854f8699b9b923ecdf6fcf486fd21a7
#jdbc.ces.user=7050fca7378222483a68bff94e152310
#jdbc.ces.pass=a2506f404f285b76f1f24f3b1b599310

### PRODUCCION ####
#jdbc.ces.url=jdbc:sqlserver://10.138.150.124:5319;databaseName=SODIMAC_SAP_PROD;encrypt=true;trustServerCertificate=true
#jdbc.ces.user=SodimacEtlUsr

jdbc.ces.url=315dacbe6d7418ee3011d7c4a85e9c217cd0dda46a5eea4741495b15c479375673513d00b3ed738ea71c85eea2618265b71e85c8f62cdae1123a1ca8a9feb6eec5e13f46e76610749ee1b4e7563ad1804141d9ccbbe83f1dfdb6330f2d43074ee817d8173ab95a4ed1f273bf6494aa68
jdbc.ces.user=4b57108bdd3c74f4c70cb0e643ac3c07
jdbc.ces.pass=71bcbea33ac16c5e30297b74c505f898

# hibernate.X
hibernate.ces.dialect=org.hibernate.dialect.SQLServer2012Dialect
hibernate.ces.show_sql=true
hibernate.ces.hbm2ddl.auto=none
hibernate.ces.cache.use_second_level_cache=false
hibernate.ces.cache.use_query_cache=false

# c3p0.X
c3p0.ces.min_size=5
c3p0.ces.max_size=20
c3p0.ces.acquire_increment=5
c3p0.ces.timeout=1800
c3p0.ces.testConnectionOnCheckout=false
c3p0.ces.testConnectionOnCheckin=true
c3p0.ces.preferredTestQuery=SELECT 1
c3p0.ces.idleConnectionTestPeriod=300
c3p0.ces.privilegeSpawnedThreads=true
c3p0.ces.contextClassLoaderSource=library



spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true