SELECT NUM_TIENDA,FECHA_TRX,TIPO
FROM (
WITH VW_FACTURAS AS(
	SELECT A.UUID
		 , B.NUM_TRX
	FROM FAC_HDR A
	   , FAC_DET_TICKETS B
	WHERE A.ID_PROCESO = B.ID_PROCESO
	AND A.TIPO_OPERACION = 'V' 
    AND A.F_VENTA BETWEEN :pFechaInicio AND :pFechaFinal
    AND A.UUID IS NOT NULL
) 
	SELECT A.NUM_TIENDA
	     , TO_CHAR(A.FECHA_TRX, 'DD/MM/YYYY') FECHA_TRX
		 , 'V' TIPO, COUNT(1) TOTAL 
	FROM TRX_HDR A
    INNER JOIN TRX_DET B
    ON A.NUM_TRX = B.NUM_TRX
    AND A.NUM_TIENDA = B.NUM_TIENDA
	WHERE A.TIPO_TRX = 1 
    AND B.NUM_DOC_CANAL NOT LIKE '26%'
	AND A.FECHA_TRX BETWEEN :pFechaInicio  AND :pFechaFinal
	AND NOT EXISTS (
        SELECT 1
        FROM VW_FACTURAS D
        WHERE D.NUM_TRX = A.NUM_TRX
        AND D.UUID IS NOT NULL
    ) 
GROUP BY A.NUM_TIENDA,TO_CHAR(A.FECHA_TRX, 'DD/MM/YYYY') 
ORDER BY COUNT(1) DESC
)