--SELECT 1010,'01/01/2023','D' FROM DUAL
SELECT A.NUM_TIENDA,TO_CHAR(A.FECHA_TRX,'DD/MM/YYYY'),'D',COUNT(1) REGISTRO
FROM (
WITH VW_TIMBRADO AS (
   SELECT A.UUID
   , B.NUM_TRX
   FROM FAC_HDR A
   INNER JOIN FAC_DET_TICKETS B
   ON A.ID_PROCESO = B.ID_PROCESO
   WHERE A.F_VENTA BETWEEN  TO_DATE('01/01/' || TO_CHAR(SYSDATE,'YYYY')   ,'DD/MM/YYYY')  AND :pFechaFinal
   AND A.TIPO_OPERACION='V'
   AND A.UUID IS NOT NULL
), VW_TIMBRADO_DEV AS (
   SELECT A.UUID
   , B.NUM_TRX
   FROM FAC_HDR A
   INNER JOIN FAC_DET_TICKETS B
   ON A.ID_PROCESO = B.ID_PROCESO
   WHERE A.F_VENTA BETWEEN  :pFechaInicio  AND :pFechaFinal
   AND A.TIPO_OPERACION='D'
   AND A.UUID IS NOT NULL
)
SELECT A.NUM_TIENDA,A.NUM_TRX,A.FECHA_TRX,A.TRX_ORIGINAL
FROM TRX_HDR A
WHERE A.TIPO_TRX IN (9,10)
AND A.FECHA_TRX BETWEEN :pFechaInicio  AND :pFechaFinal
AND EXISTS (
  SELECT 1
  FROM VW_TIMBRADO C
  WHERE C.NUM_TRX = A.TRX_ORIGINAL
)
AND NOT EXISTS (
  SELECT 1
  FROM VW_TIMBRADO_DEV C
  WHERE C.NUM_TRX = A.NUM_TRX
)

) A
WHERE NOT EXISTS (
   SELECT 1
   FROM EST_FACTURAS B
   WHERE A.NUM_TRX = B.NUM_TRX
   AND B.NUM_FACTURA IS NOT NULL
   AND TRUNC(B.FECHA) <= TRUNC(SYSDATE-1)
) AND NOT EXISTS (
   SELECT 1
   FROM EST_FACTURAS B
   WHERE B.NUM_TRX =  A.TRX_ORIGINAL
   AND B.NUM_FACTURA IS NOT NULL
   AND TRUNC(B.FECHA) <= TRUNC(SYSDATE-1)
)
GROUP BY A.NUM_TIENDA,TO_CHAR(A.FECHA_TRX,'DD/MM/YYYY'),'D'