WITH VW_TIMBRADO AS (
   SELECT A.UUID
   , B.NUM_TRX
   FROM FAC_HDR A
   INNER JOIN FAC_DET_TICKETS B
   ON A.ID_PROCESO = B.ID_PROCESO
   WHERE A.F_VENTA BETWEEN  :pFechaInicio  AND :pFechaFinal
   AND A.TIPO_OPERACION='V'
   AND A.UUID IS NOT NULL
   AND A.VERSION NOT IN ('3.3')
), VW_TIMBRADO_FNC AS (
   SELECT A.UUID
   , B.NUM_TRX
   FROM FAC_HDR A
   INNER JOIN FAC_DET_TICKETS B
   ON A.ID_PROCESO = B.ID_PROCESO
   WHERE A.F_VENTA BETWEEN  :pFechaInicio  AND :pFechaFinal
   AND A.TIPO_OPERACION='FD'
   AND A.UUID IS NOT NULL
   AND A.VERSION NOT IN ('3.3')
)
SELECT A.NUM_TIENDA,TO_CHAR(A.FECHA_TRX,'DD/MM/YYYY') FECHA_TRX,'FD' TIPO,COUNT(1) REGISTROS
FROM TRX_HDR A
WHERE A.TIPO_TRX=1
AND A.FECHA_TRX BETWEEN :pFechaInicio  AND :pFechaFinal
AND EXISTS (
   SELECT 1
   FROM EST_FACTURAS B
   WHERE A.NUM_TRX = B.NUM_TRX
   AND B.NUM_FACTURA IS NOT NULL
   AND TRUNC(B.FECHA) <= TRUNC(SYSDATE-1)
) 
AND EXISTS (
  SELECT 1
  FROM VW_TIMBRADO C
  WHERE C.NUM_TRX = A.NUM_TRX
) 
AND NOT EXISTS (
  SELECT 1
  FROM VW_TIMBRADO_FNC C
  WHERE C.NUM_TRX = A.NUM_TRX
)
GROUP BY A.NUM_TIENDA,TO_CHAR(A.FECHA_TRX,'DD/MM/YYYY'),'FD'
ORDER BY A.NUM_TIENDA,TO_CHAR(A.FECHA_TRX,'DD/MM/YYYY') DESC