
export const CatalogException = {
CATALOGS_API_EXCEPTION: "/catalog/CatMsgExcepcion",
CATALOGS_API_EXCEPTION_DETAILS_KEY_EXC001: "/details/EXC001",
CATALOGS_API_EXCEPTION_DETAILS_KEY_EXC002: "/details/EXC002",
CATALOGS_API_EXCEPTION_DETAILS_KEY_EXC003: "/details/EXC003",
CATALOGS_API_EXCEPTION_DETAILS_KEY_EXC004: "/details/EXC004",
CATALOGS_API_EXCEPTION_DETAILS_KEY_EXC005: "/details/EXC005",
CATALOGS_API_EXCEPTION_DETAILS_KEY_EXC006: "/details/EXC006",
CATALOGS_API_EXCEPTION_DETAILS_KEY_EXC007: "/details/EXC007",
CATALOGS_API_EXCEPTION_DETAILS_KEY_EXC008: "/details/EXC008",
CATALOGS_API_EXCEPTION_DETAILS_KEY_EXC009: "/details/EXC009",
CATALOGS_API_EXCEPTION_DETAILS_KEY_EXC010: "/details/EXC010",
CATALOGS_API_EXCEPTION_DETAILS_KEY_EXC011: "/details/EXC011",
CATALOGS_API_EXCEPTION_DETAILS_KEY_EXC012: "/details/EXC012",
CATALOGS_API_EXCEPTION_DETAILS_KEY_EXC013: "/details/EXC013",
CATALOGS_API_EXCEPTION_DETAILS_KEY_EXC014: "/details/EXC014",
CATALOGS_API_EXCEPTION_DETAILS_KEY_EXC015: "/details/EXC015",
CATALOGS_API_EXCEPTION_DETAILS_KEY_EXC016: "/details/EXC016",
CATALOGS_API_EXCEPTION_DETAILS_KEY_EXC017: "/details/EXC017",
CATALOGS_API_EXCEPTION_DETAILS_KEY_EXC018: "/details/EXC018",
CATALOGS_API_EXCEPTION_DETAILS_KEY_EXC019: "/details/EXC019",
CATALOGS_API_EXCEPTION_DETAILS_KEY_EXC020: "/details/EXC020",
CATALOGS_API_EXCEPTION_DETAILS_KEY_EXC021: "/details/EXC021",
} as const;


export const CatalogSupplierUrls = {
CATALOGS_API_GET_ALL_SUPPLIERS: "/suppliers",
CATALOGS_API_GET_SUPPLIER: "/suppliers/number", 
CATALOGS_API_ESTATUS_CARTAPORTE_FBC: "/catalog/CatEstatusCartaPorteFBC",
CATALOGS_API_TIPO_PROVEEDOR: "/catalog/CatTipoProveedor",
CATALOGS_API_TIPO_ENTREGA_GUIA: "/catalog/CatTipoEntregaGuia",
CATALOGS_API_ORIGEN_CARTA_PORTE: "/catalog/CatOrigenCartaPorte",
CATALOGS_API_TIPO_RECEPCION_SODIMAC: "/catalog/CatTipoOrigenRecepcionSodimac",
} as const;


export const CatalogStatusTrain = {
CATALOGS_API_STATUS_TRAIN: "/status-train",
CATALOGS_API_VALID_TRAIN: "/validate",
} as const;

export const CatEstatusRecepcion = {
CATALOGS_API_STATUS_RECEPTION: "/catalog/CatEstatusRecepcion/details",
} as const;

export const CatalogAdvertencia = {
CATALOGS_API_ADVERTENCIA: "/catalog/CatMsgAdvertencia",
CATALOGS_API_ADVERTENCIA_DETAILS_KEY_WRN103: "/details/WRN103",
CATALOGS_API_ADVERTENCIA_DETAILS_KEY_WRN301: "/details/WRN301",
CATALOGS_API_ADVERTENCIA_DETAILS_KEY_WRN302: "/details/WRN302",
} as const;

export const CatalogStores = {
CATALOGS_API_STORES: "/catalog/CatStores/details",
} as const;

export const CatalogExitoso = {
CATALOGS_API_EXITOSO: "/catalog/CatMsgExitoso",
CATALOGS_API_EXITOSO_DETAILS_KEY_RES205: "/details/RES205",
} as const;


export const CatalogNegocio = {
CATALOGS_API_NEGOCIO: "/catalog/CatMsgNegocio",
CATALOGS_API_NEGOCIO_DETAILS_KEY_BUS206: "/details/BUS206",
CATALOGS_API_NEGOCIO_DETAILS_KEY_BUS207: "/details/BUS207",
CATALOGS_API_NEGOCIO_DETAILS_KEY_BUS208: "/details/BUS208",
CATALOGS_API_NEGOCIO_DETAILS_KEY_BUS209: "/details/BUS209",
CATALOGS_API_NEGOCIO_DETAILS_KEY_BUS210: "/details/BUS210",
CATALOGS_API_NEGOCIO_DETAILS_KEY_BUS211: "/details/BUS211",
CATALOGS_API_NEGOCIO_DETAILS_KEY_BUS212: "/details/BUS212",
} as const;