-- public.activity_logs definition

-- Drop table

-- DROP TABLE public.activity_logs;

CREATE TABLE public.activity_logs (
	activity_logs_uuid uuid DEFAULT gen_random_uuid() NOT NULL,
	trace_id uuid NOT NULL,
	duration_ms numeric(18, 6) NULL,
	is_error bool NOT NULL,
	modulo varchar(100) NULL,
	service_name varchar(100) NOT NULL,
	"action" varchar(100) NOT NULL,
	message varchar(100) NOT NULL,
	message_detail varchar NULL,
	user_id varchar(50) NULL,
	"timestamp" timestamp NOT NULL,
	details jsonb NULL,
	CONSTRAINT activity_logs_pkey PRIMARY KEY (activity_logs_uuid)
);


-- public.catapplication definition

-- Drop table

-- DROP TABLE public.catapplication;

CREATE TABLE public.catapplication (
	idapplication int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	createdat timestamp(6) NULL,
	idusercreated int4 NULL,
	iduserupdated int4 NULL,
	updatedat timestamp(6) NULL,
	description varchar(255) NULL,
	"name" varchar(255) NULL,
	status int4 NULL,
	CONSTRAINT catapplication_pkey PRIMARY KEY (idapplication)
);


-- public.catinvoiceversion definition

-- Drop table

-- DROP TABLE public.catinvoiceversion;

CREATE TABLE public.catinvoiceversion (
	idinvoiceversion int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	createdat timestamp(6) NULL,
	idusercreated int4 NULL,
	iduserupdated int4 NULL,
	updatedat timestamp(6) NULL,
	description varchar(255) NULL,
	status int4 NULL,
	"version" varchar(255) NULL,
	CONSTRAINT catinvoiceversion_pkey PRIMARY KEY (idinvoiceversion)
);


-- public.catitemtype definition

-- Drop table

-- DROP TABLE public.catitemtype;

CREATE TABLE public.catitemtype (
	idcatitemtype int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	createdat timestamp(6) NULL,
	idusercreated int4 NULL,
	iduserupdated int4 NULL,
	updatedat timestamp(6) NULL,
	description varchar(255) NULL,
	"name" varchar(255) NULL,
	status int4 NULL,
	CONSTRAINT catitemtype_pkey PRIMARY KEY (idcatitemtype)
);


-- public.catmessagetype definition

-- Drop table

-- DROP TABLE public.catmessagetype;

CREATE TABLE public.catmessagetype (
	idmessagetype int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	createdat timestamp(6) NULL,
	idusercreated int4 NULL,
	iduserupdated int4 NULL,
	updatedat timestamp(6) NULL,
	description varchar(255) NULL,
	"name" varchar(255) NULL,
	status int4 NULL,
	CONSTRAINT catmessagetype_pkey PRIMARY KEY (idmessagetype)
);


-- public.catmodule definition

-- Drop table

-- DROP TABLE public.catmodule;

CREATE TABLE public.catmodule (
	idmodule int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	createdat timestamp(6) NULL,
	idusercreated int4 NULL,
	iduserupdated int4 NULL,
	updatedat timestamp(6) NULL,
	description varchar(255) NULL,
	"name" varchar(255) NULL,
	status int4 NULL,
	CONSTRAINT catmodule_pkey PRIMARY KEY (idmodule)
);


-- public.catparametertype definition

-- Drop table

-- DROP TABLE public.catparametertype;

CREATE TABLE public.catparametertype (
	idparametertype int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	createdat timestamp(6) NULL,
	idusercreated int4 NULL,
	iduserupdated int4 NULL,
	updatedat timestamp(6) NULL,
	description varchar(255) NULL,
	"name" varchar(255) NULL,
	status int4 NULL,
	CONSTRAINT catparametertype_pkey PRIMARY KEY (idparametertype)
);


-- public.catprocess definition

-- Drop table

-- DROP TABLE public.catprocess;

CREATE TABLE public.catprocess (
	idprocess int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	createdat timestamp(6) NULL,
	idusercreated int4 NULL,
	iduserupdated int4 NULL,
	updatedat timestamp(6) NULL,
	description varchar(255) NULL,
	"name" varchar(255) NULL,
	status int4 NULL,
	CONSTRAINT catprocess_pkey PRIMARY KEY (idprocess)
);


-- public.catsupplier definition

-- Drop table

-- DROP TABLE public.catsupplier;

CREATE TABLE public.catsupplier (
	suppliernumber int8 NOT NULL,
	"name" varchar(128) NULL,
	CONSTRAINT catsupplier_pkey PRIMARY KEY (suppliernumber)
);


-- public.faq_category definition

-- Drop table

-- DROP TABLE public.faq_category;

CREATE TABLE public.faq_category (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz(6) NOT NULL,
	description varchar(256) NOT NULL,
	icon_path varchar(255) NULL,
	image_data bytea NULL,
	image_name varchar(255) NULL,
	is_active bool NOT NULL,
	"name" varchar(64) NOT NULL,
	updated_at timestamptz(6) NOT NULL,
	CONSTRAINT faq_category_pkey PRIMARY KEY (id)
);


-- public.feedback definition

-- Drop table

-- DROP TABLE public.feedback;

CREATE TABLE public.feedback (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	created_by varchar(100) NULL,
	is_active bool NOT NULL,
	question varchar(200) NOT NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(100) NULL,
	CONSTRAINT feedback_pkey PRIMARY KEY (id)
);
CREATE INDEX ix_feedback_is_active ON public.feedback USING btree (is_active);


-- public.module_resolver definition

-- Drop table

-- DROP TABLE public.module_resolver;

CREATE TABLE public.module_resolver (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	area varchar(128) NULL,
	module_id int4 NOT NULL,
	module_name varchar(128) NOT NULL,
	person_name varchar(128) NOT NULL,
	resolver_email varchar(160) NOT NULL,
	CONSTRAINT module_resolver_pkey PRIMARY KEY (id)
);


-- public.related_information definition

-- Drop table

-- DROP TABLE public.related_information;

CREATE TABLE public.related_information (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	business_unit_id int4 NULL,
	country_id int4 NULL,
	created_at timestamp(6) NOT NULL,
	image_data bytea NULL,
	image_path varchar(255) NULL,
	is_active bool DEFAULT true NOT NULL,
	link varchar(256) NOT NULL,
	title varchar(64) NOT NULL,
	updated_at timestamp(6) NOT NULL,
	CONSTRAINT related_information_pkey PRIMARY KEY (id)
);


-- public.shippingguide_hist definition

-- Drop table

-- DROP TABLE public.shippingguide_hist;

CREATE TABLE public.shippingguide_hist (
	idhist int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	totalamount numeric(18, 2) NULL,
	archived_at timestamp(6) NULL,
	archived_by varchar(64) NULL,
	cartaportecsv oid NULL,
	cartaportexml oid NULL,
	"comments" varchar(2000) NULL,
	createdat timestamp(6) NULL,
	deliverydate date NULL,
	deliverytype varchar(255) NULL,
	shippingguide varchar(255) NULL,
	idshippingguide int8 NULL,
	origin varchar(255) NULL,
	licenseplate varchar(255) NULL,
	idpurchaseorder int8 NULL,
	sentdate date NULL,
	status int4 NULL,
	suppliernumber int8 NULL,
	trailerplate varchar(255) NULL,
	updatedat timestamp(6) NULL,
	idusercreated int8 NULL,
	CONSTRAINT shippingguide_hist_pkey PRIMARY KEY (idhist)
);


-- public.shipping_status definition

-- Drop table

-- DROP TABLE public.shipping_status;

CREATE TABLE public.shipping_status (
	id int4 NOT NULL,
	description varchar(64) NULL,
	CONSTRAINT shipping_status_pkey PRIMARY KEY (id)
);


-- public.v_issuer_uuid definition

-- Drop table

-- DROP TABLE public.v_issuer_uuid;

CREATE TABLE public.v_issuer_uuid (
	issuer_uuid uuid NULL
);


-- public.applicationmsg definition

-- Drop table

-- DROP TABLE public.applicationmsg;

CREATE TABLE public.applicationmsg (
	idapplicationmsg int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	createdat timestamp(6) NULL,
	idusercreated int4 NULL,
	iduserupdated int4 NULL,
	updatedat timestamp(6) NULL,
	status int4 NULL,
	idapplication int4 NOT NULL,
	CONSTRAINT applicationmsg_pkey PRIMARY KEY (idapplicationmsg),
	CONSTRAINT fk96312fyyiuygby6ul0f0pc6ki FOREIGN KEY (idapplication) REFERENCES public.catapplication(idapplication)
);


-- public."catalog" definition

-- Drop table

-- DROP TABLE public."catalog";

CREATE TABLE public."catalog" (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	active bool NOT NULL,
	creation_time timestamp(6) NOT NULL,
	status int4 NOT NULL,
	"type" int4 NOT NULL,
	update_time timestamp(6) NULL,
	area varchar(128) NULL,
	description varchar(64) NOT NULL,
	parent_id int4 NULL,
	CONSTRAINT catalog_pkey PRIMARY KEY (id),
	CONSTRAINT fk2n9sihbblanh07i8girqltn1m FOREIGN KEY (parent_id) REFERENCES public."catalog"(id)
);


-- public.catitem definition

-- Drop table

-- DROP TABLE public.catitem;

CREATE TABLE public.catitem (
	iditem int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	createdat timestamp(6) NULL,
	idusercreated int4 NULL,
	iduserupdated int4 NULL,
	updatedat timestamp(6) NULL,
	description varchar(255) NULL,
	"name" varchar(255) NULL,
	status int4 NULL,
	idcatitemtype int4 NOT NULL,
	CONSTRAINT catitem_pkey PRIMARY KEY (iditem),
	CONSTRAINT fka6kqvp0283wiw37qjpf6ncthu FOREIGN KEY (idcatitemtype) REFERENCES public.catitemtype(idcatitemtype)
);


-- public.catmessage definition

-- Drop table

-- DROP TABLE public.catmessage;

CREATE TABLE public.catmessage (
	idmessage int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	createdat timestamp(6) NULL,
	idusercreated int4 NULL,
	iduserupdated int4 NULL,
	updatedat timestamp(6) NULL,
	description varchar(255) NULL,
	messagecode varchar(255) NULL,
	status int4 NULL,
	idmessagetype int4 NOT NULL,
	CONSTRAINT catmessage_pkey PRIMARY KEY (idmessage),
	CONSTRAINT fkpm063qogkmodbbp7ke6wkam4b FOREIGN KEY (idmessagetype) REFERENCES public.catmessagetype(idmessagetype)
);


-- public.catparameter definition

-- Drop table

-- DROP TABLE public.catparameter;

CREATE TABLE public.catparameter (
	idparameter int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	createdat timestamp(6) NULL,
	idusercreated int4 NULL,
	iduserupdated int4 NULL,
	updatedat timestamp(6) NULL,
	description varchar(255) NULL,
	enddate timestamp(6) NULL,
	"name" varchar(255) NULL,
	startdate timestamp(6) NULL,
	status int4 NULL,
	value varchar(255) NULL,
	"version" int4 NULL,
	idmodule int4 NOT NULL,
	idparametertype int4 NOT NULL,
	CONSTRAINT catparameter_pkey PRIMARY KEY (idparameter),
	CONSTRAINT fk558732p5knr226fxtfcc1rj6h FOREIGN KEY (idparametertype) REFERENCES public.catparametertype(idparametertype),
	CONSTRAINT fkl7dypdc4udhcwx40bh9748s1e FOREIGN KEY (idmodule) REFERENCES public.catmodule(idmodule)
);


-- public.company definition

-- Drop table

-- DROP TABLE public.company;

CREATE TABLE public.company (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	active bool NOT NULL,
	creation_time timestamp(6) NOT NULL,
	status int4 NOT NULL,
	"type" int4 NOT NULL,
	update_time timestamp(6) NULL,
	"name" varchar(32) NOT NULL,
	rut varchar(32) NOT NULL,
	business_unit int4 NOT NULL,
	country int4 NOT NULL,
	CONSTRAINT company_pkey PRIMARY KEY (id),
	CONSTRAINT fk16uetgf2n2411xrnhb9kv1ud6 FOREIGN KEY (business_unit) REFERENCES public."catalog"(id),
	CONSTRAINT fkoayia5m767cr4g9md4jt5gx58 FOREIGN KEY (country) REFERENCES public."catalog"(id)
);


-- public.faq definition

-- Drop table

-- DROP TABLE public.faq;

CREATE TABLE public.faq (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	is_active bool NOT NULL,
	answer varchar(512) NOT NULL,
	created_at timestamp(6) NOT NULL,
	question varchar(512) NOT NULL,
	updated_at timestamp(6) NOT NULL,
	"views" int4 NOT NULL,
	category_id int8 NOT NULL,
	CONSTRAINT faq_pkey PRIMARY KEY (id),
	CONSTRAINT fk9ed0hfwvyse7c1w8u79hs8cyp FOREIGN KEY (category_id) REFERENCES public.faq_category(id)
);


-- public.faq_alias definition

-- Drop table

-- DROP TABLE public.faq_alias;

CREATE TABLE public.faq_alias (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	is_active bool NOT NULL,
	question varchar(512) NOT NULL,
	updated_at timestamp(6) NOT NULL,
	faq_id int8 NOT NULL,
	CONSTRAINT faq_alias_pkey PRIMARY KEY (id),
	CONSTRAINT fkbm2de18hpx2642ryg7w8t3975 FOREIGN KEY (faq_id) REFERENCES public.faq(id)
);


-- public.faq_attachment definition

-- Drop table

-- DROP TABLE public.faq_attachment;

CREATE TABLE public.faq_attachment (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	content_type varchar(120) NOT NULL,
	created_at timestamp(6) NOT NULL,
	"data" oid NULL,
	file_name varchar(255) NOT NULL,
	file_path varchar(1024) NULL,
	is_active bool NOT NULL,
	size_kb int4 NOT NULL,
	updated_at timestamp(6) NOT NULL,
	faq_id int8 NOT NULL,
	CONSTRAINT faq_attachment_pkey PRIMARY KEY (id),
	CONSTRAINT fk7nwbd8yy9llojddjwii16bxx9 FOREIGN KEY (faq_id) REFERENCES public.faq(id)
);


-- public.faq_category_link definition

-- Drop table

-- DROP TABLE public.faq_category_link;

CREATE TABLE public.faq_category_link (
	created_at timestamp(6) NOT NULL,
	category_id int8 NOT NULL,
	faq_id int8 NOT NULL,
	CONSTRAINT faq_category_link_pkey PRIMARY KEY (category_id, faq_id),
	CONSTRAINT fk64fhklhrlxr80rt3txeoqt0nk FOREIGN KEY (category_id) REFERENCES public.faq_category(id),
	CONSTRAINT fko3dnkfllj2ajtc3bx0t5j13o8 FOREIGN KEY (faq_id) REFERENCES public.faq(id)
);


-- public.faq_related definition

-- Drop table

-- DROP TABLE public.faq_related;

CREATE TABLE public.faq_related (
	faq_id int8 NOT NULL,
	related_id int8 NOT NULL,
	CONSTRAINT fk6ki5w9lifswnc24rfsauduxf FOREIGN KEY (faq_id) REFERENCES public.faq(id),
	CONSTRAINT fkl2638l7yobdo4qtr529f23rbm FOREIGN KEY (related_id) REFERENCES public.faq(id)
);


-- public.faq_related_information_link definition

-- Drop table

-- DROP TABLE public.faq_related_information_link;

CREATE TABLE public.faq_related_information_link (
	created_at timestamp(6) NOT NULL,
	faq_id int8 NOT NULL,
	related_information_id int8 NOT NULL,
	CONSTRAINT faq_related_information_link_pkey PRIMARY KEY (faq_id, related_information_id),
	CONSTRAINT fk2y7adgp6cago6j8s864roywgh FOREIGN KEY (related_information_id) REFERENCES public.related_information(id),
	CONSTRAINT fkduh0txl090d1wtj7qqrmvsf FOREIGN KEY (faq_id) REFERENCES public.faq(id)
);


-- public.feedback_answer definition

-- Drop table

-- DROP TABLE public.feedback_answer;

CREATE TABLE public.feedback_answer (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"position" int4 NOT NULL,
	"text" varchar(200) NOT NULL,
	feedback_id int8 NOT NULL,
	CONSTRAINT feedback_answer_pkey PRIMARY KEY (id),
	CONSTRAINT fk_feedback_answer_feedback FOREIGN KEY (feedback_id) REFERENCES public.feedback(id)
);
CREATE INDEX ix_feedback_answer_feedback ON public.feedback_answer USING btree (feedback_id);


-- public."notice" definition

-- Drop table

-- DROP TABLE public."notice";

CREATE TABLE public."notice" (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	active bool NOT NULL,
	creation_time timestamp(6) NOT NULL,
	status int4 NOT NULL,
	"type" int4 NOT NULL,
	update_time timestamp(6) NULL,
	description varchar(128) NOT NULL,
	link varchar(256) NOT NULL,
	"name" varchar(32) NOT NULL,
	business_unit int4 NOT NULL,
	country int4 NOT NULL,
	"position" int4 NOT NULL,
	CONSTRAINT notice_pkey PRIMARY KEY (id),
	CONSTRAINT fk28b504pj5ntq1v5ns9ryleh7h FOREIGN KEY (country) REFERENCES public."catalog"(id),
	CONSTRAINT fkbpv4t2ndpry3qip83t44r1d0 FOREIGN KEY ("position") REFERENCES public."catalog"(id),
	CONSTRAINT fkr2a245f6941e4h3qpuoywt51x FOREIGN KEY (business_unit) REFERENCES public."catalog"(id)
);


-- public.shippingguide definition

-- Drop table

-- DROP TABLE public.shippingguide;

CREATE TABLE public.shippingguide (
	idshippingguide int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	totalamount numeric(18, 2) NULL,
	cartaportecsv oid NULL,
	cartaportexml oid NULL,
	"comments" varchar(2000) NULL,
	createdat timestamp(6) NULL,
	deliverydate date NULL,
	deliverytype varchar(64) NULL,
	shippingguide varchar(64) NOT NULL,
	origin varchar(128) NULL,
	licenseplate varchar(32) NULL,
	idpurchaseorder int8 NULL,
	sentdate date NULL,
	suppliernumber int8 NOT NULL,
	trailerplate varchar(32) NULL,
	updatedat timestamp(6) NULL,
	idusercreated int8 NULL,
	status int4 NULL,
	CONSTRAINT shippingguide_pkey PRIMARY KEY (idshippingguide),
	CONSTRAINT fkoy0y0o5txkmqjkgihaxjprqrp FOREIGN KEY (status) REFERENCES public.shipping_status(id),
	CONSTRAINT fkrwu7svffdlr7haurhyqtl8qsf FOREIGN KEY (suppliernumber) REFERENCES public.catsupplier(suppliernumber)
);


-- public.sla definition

-- Drop table

-- DROP TABLE public.sla;

CREATE TABLE public.sla (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	active bool NOT NULL,
	creation_time timestamp(6) NOT NULL,
	status int4 NOT NULL,
	"type" int4 NOT NULL,
	update_time timestamp(6) NULL,
	manager varchar(128) NOT NULL,
	business_unit int4 NOT NULL,
	country int4 NOT NULL,
	first_response_level int4 NOT NULL,
	"module" int4 NOT NULL,
	priority int4 NOT NULL,
	reason int4 NOT NULL,
	resolution_level int4 NOT NULL,
	CONSTRAINT sla_pkey PRIMARY KEY (id),
	CONSTRAINT fk7losme6v9ty9gp33hbe09heo1 FOREIGN KEY (priority) REFERENCES public."catalog"(id),
	CONSTRAINT fkcgje1x36u3guq7vm3agh687my FOREIGN KEY ("module") REFERENCES public."catalog"(id),
	CONSTRAINT fke8nabifg7lie6ito38aum2kxf FOREIGN KEY (first_response_level) REFERENCES public."catalog"(id),
	CONSTRAINT fke9y217so3lfnpk8vb6rf45xk FOREIGN KEY (business_unit) REFERENCES public."catalog"(id),
	CONSTRAINT fkeofq2kspyvul86wqgykf9mqxo FOREIGN KEY (resolution_level) REFERENCES public."catalog"(id),
	CONSTRAINT fkpeuoamdji8k51gf8bcblnfura FOREIGN KEY (reason) REFERENCES public."catalog"(id),
	CONSTRAINT fkrdlj6pmpdf77755huduobnx2v FOREIGN KEY (country) REFERENCES public."catalog"(id)
);


-- public.author definition

-- Drop table

-- DROP TABLE public.author;

CREATE TABLE public.author (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	active bool NOT NULL,
	creation_time timestamp(6) NOT NULL,
	status int4 NOT NULL,
	"type" int4 NOT NULL,
	update_time timestamp(6) NULL,
	email varchar(64) NOT NULL,
	"name" varchar(32) NOT NULL,
	reason int4 NULL,
	CONSTRAINT author_pkey PRIMARY KEY (id),
	CONSTRAINT ukgrm3merlhi91rac0mu26swyhf UNIQUE (email),
	CONSTRAINT fk4cjlgxd5i7yos82q3tn90usp7 FOREIGN KEY (reason) REFERENCES public."catalog"(id)
);


-- public.request definition

-- Drop table

-- DROP TABLE public.request;

CREATE TABLE public.request (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	active bool NOT NULL,
	creation_time timestamp(6) NOT NULL,
	status int4 NOT NULL,
	"type" int4 NOT NULL,
	update_time timestamp(6) NULL,
	description varchar(256) NOT NULL,
	order_id varchar(32) NOT NULL,
	clazz int4 NULL,
	company_id int4 NULL,
	detail int4 NOT NULL,
	"module" int4 NOT NULL,
	"operator" int4 NULL,
	priority int4 NULL,
	progress int4 NULL,
	reason int4 NOT NULL,
	repeatitiveness int4 NULL,
	requester int4 NOT NULL,
	CONSTRAINT request_pkey PRIMARY KEY (id),
	CONSTRAINT fk2660x5jpahtslib4r5ac7msx7 FOREIGN KEY ("module") REFERENCES public."catalog"(id),
	CONSTRAINT fk5w6no964jn5lpg4tpeugv8xx7 FOREIGN KEY (company_id) REFERENCES public.company(id),
	CONSTRAINT fk6h9a5rm5pq1d2bq4m4w24g1fh FOREIGN KEY (requester) REFERENCES public.author(id),
	CONSTRAINT fkb8qfx7n8wp8djpp4kak8k5buc FOREIGN KEY (repeatitiveness) REFERENCES public."catalog"(id),
	CONSTRAINT fklsomifkx2jjyh58ud2irmvntw FOREIGN KEY (reason) REFERENCES public."catalog"(id),
	CONSTRAINT fkojg2lx8gpkvyrw0jgdbrq3dh9 FOREIGN KEY (priority) REFERENCES public."catalog"(id),
	CONSTRAINT fkr3j1c2gdbqsxa5fqclshev1a5 FOREIGN KEY (clazz) REFERENCES public."catalog"(id),
	CONSTRAINT fkt0v2c1dcflijc0t95l3l23po8 FOREIGN KEY ("operator") REFERENCES public.author(id),
	CONSTRAINT fktqqvu4efl0uupk904p84ccbyg FOREIGN KEY (detail) REFERENCES public."catalog"(id),
	CONSTRAINT fku84wxxbw2w05g43mfqg3xfb FOREIGN KEY (progress) REFERENCES public."catalog"(id)
);


-- public.attachment definition

-- Drop table

-- DROP TABLE public.attachment;

CREATE TABLE public.attachment (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	active bool NOT NULL,
	creation_time timestamp(6) NOT NULL,
	status int4 NOT NULL,
	"type" int4 NOT NULL,
	update_time timestamp(6) NULL,
	"name" varchar(32) NOT NULL,
	"path" varchar(128) NOT NULL,
	author_id int4 NULL,
	request_id int4 NULL,
	CONSTRAINT attachment_pkey PRIMARY KEY (id),
	CONSTRAINT fk8owhh20tu3ram34js63ku0tvr FOREIGN KEY (author_id) REFERENCES public.author(id),
	CONSTRAINT fkn21vacvtt2qcbv784hbfh9jha FOREIGN KEY (request_id) REFERENCES public.request(id)
);


-- public."comment" definition

-- Drop table

-- DROP TABLE public."comment";

CREATE TABLE public."comment" (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	active bool NOT NULL,
	creation_time timestamp(6) NOT NULL,
	status int4 NOT NULL,
	"type" int4 NOT NULL,
	update_time timestamp(6) NULL,
	"comment" varchar(256) NOT NULL,
	author_id int4 NULL,
	request_id int4 NULL,
	CONSTRAINT comment_pkey PRIMARY KEY (id),
	CONSTRAINT fk1jjloo6xwf7kl33cho74gtmi5 FOREIGN KEY (author_id) REFERENCES public.author(id),
	CONSTRAINT fkr7sn827lv8orfsni6pu70lm3s FOREIGN KEY (request_id) REFERENCES public.request(id)
);